# Generated by Django 5.0.6 on 2026-07-03 18:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_permission_rolepermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('status', models.CharField(db_index=True, default='active', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tracer_members',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('loan_application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(db_index=True, default='draft', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='tracer.member')),
            ],
            options={
                'db_table': 'tracer_loan_applications',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('loan_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(db_index=True, default='pending_disbursement', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_account', to='tracer.loanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_accounts', to='tracer.member')),
            ],
            options={
                'db_table': 'tracer_loan_accounts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('repayment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(db_index=True, default='posted', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='tracer.loanaccount')),
            ],
            options={
                'db_table': 'tracer_repayments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('workflow_event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(db_index=True, max_length=100)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('from_state', models.CharField(blank=True, max_length=100, null=True)),
                ('to_state', models.CharField(db_index=True, max_length=100)),
                ('trigger_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.user')),
            ],
            options={
                'db_table': 'workflow_events',
                'ordering': ['created_at'],
            },
        ),
    ]
