# Generated by Django 5.0.6 on 2026-07-22 12:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0020_approvalaction_approver_display_name'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('loans', '0009_dpd_pointer_integrity'),
        ('recovery', '0001_initial'),
        ('workflows', '0001_canonical_workflow_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryAction',
            fields=[
                ('recovery_action_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_index=True, max_length=100)),
                ('action_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('source_security_type', models.CharField(max_length=60)),
                ('source_security_id', models.UUIDField()),
                ('source_security_evidence_json', models.JSONField(default=dict)),
                ('initiated_by_role_code', models.CharField(max_length=100)),
                ('initiated_at', models.DateTimeField()),
                ('initiation_evidence_document_ids_json', models.JSONField(default=list)),
                ('initiation_remarks', models.TextField()),
                ('interaction_log_json', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('amount_recovered', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('completion_evidence_document_ids_json', models.JSONField(default=list)),
                ('completion_remarks', models.TextField(blank=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('ledger_posting_json', models.JSONField(default=dict)),
                ('external_sap_status', models.CharField(default='pending', max_length=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_actions', to='approvals.approvalcase')),
                ('completed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_recovery_actions', to='identity.user')),
                ('completion_workflow_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_recovery_action', to='workflows.workflowevent')),
                ('initiated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_recovery_actions', to='identity.user')),
                ('initiation_workflow_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_recovery_action', to='workflows.workflowevent')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_actions', to='loans.loanaccount')),
                ('recovery_decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_action', to='recovery.recoverydecision')),
            ],
            options={
                'db_table': 'recovery_actions',
                'ordering': ['-initiated_at', '-recovery_action_id'],
                'indexes': [models.Index(fields=['loan_account', 'action_status'], name='idx_recovery_action_account'), models.Index(fields=['source_security_type', 'source_security_id'], name='idx_recovery_action_security')],
            },
        ),
        migrations.AddConstraint(
            model_name='recoveryaction',
            constraint=models.CheckConstraint(check=models.Q(('action_status__in', ('pending', 'completed', 'failed'))), name='recovery_action_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='recoveryaction',
            constraint=models.CheckConstraint(check=models.Q(('amount_recovered__isnull', True), ('amount_recovered__gte', 0), _connector='OR'), name='recovery_action_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='recoveryaction',
            constraint=models.CheckConstraint(check=models.Q(('external_sap_status', 'pending')), name='recovery_action_sap_pending_only'),
        ),
        migrations.AddConstraint(
            model_name='recoveryaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action_status', 'pending'), ('amount_recovered__isnull', True), ('completed_at__isnull', True), ('completed_by_user__isnull', True), ('completion_workflow_event__isnull', True), ('failed_at__isnull', True), ('failure_reason', ''), ('ledger_posting_json', {})), models.Q(('action_status', 'completed'), ('amount_recovered__isnull', False), ('completed_at__isnull', False), ('completed_by_user__isnull', False), ('completion_workflow_event__isnull', False), ('failed_at__isnull', True), ('failure_reason', '')), models.Q(('action_status', 'failed'), ('amount_recovered__isnull', True), ('completed_at__isnull', True), ('completed_by_user__isnull', True), ('completion_workflow_event__isnull', True), ('failed_at__isnull', False), ('ledger_posting_json', {})), _connector='OR'), name='recovery_action_terminal_evidence'),
        ),
    ]
