# Generated by Django 5.0.6 on 2026-07-16 06:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0017_bank_decision_terminal_sanction_snapshots'),
        ('approvals', '0020_approvalaction_approver_display_name'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('finance', '0003_sap_delivery_replay_contract'),
        ('identity', '0003_portal_member_auth'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('loan_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_account_number', models.CharField(max_length=80)),
                ('loan_account_number_normalized', models.CharField(max_length=80, unique=True)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('loan_type', models.CharField(db_index=True, max_length=60)),
                ('tenure_start_date', models.DateField(blank=True, null=True)),
                ('tenure_end_date', models.DateField(blank=True, null=True)),
                ('interest_rate_type', models.CharField(max_length=60)),
                ('current_interest_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('repayment_date', models.DateField(db_index=True)),
                ('principal_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('interest_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('charges_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('loan_account_status', models.CharField(db_index=True, default='sanctioned', max_length=80)),
                ('current_dpd_status_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_account', to='applications.loanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_accounts', to='members.member')),
                ('sanction_decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_account', to='approvals.sanctiondecision')),
                ('sap_customer_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_accounts', to='finance.sapcustomercode')),
            ],
            options={
                'db_table': 'loan_accounts',
            },
        ),
        migrations.CreateModel(
            name='LoanStatusHistory',
            fields=[
                ('loan_status_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=80, null=True)),
                ('to_status', models.CharField(db_index=True, max_length=80)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_application_id_snapshot', models.UUIDField()),
                ('member_id_snapshot', models.UUIDField()),
                ('sanction_decision_id_snapshot', models.UUIDField()),
                ('sap_customer_code_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('loan_terms_id_snapshot', models.UUIDField()),
                ('replay_flag', models.BooleanField(default=False)),
                ('outcome', models.CharField(default='created', max_length=40)),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_status_changes', to='identity.user')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='loans.loanaccount')),
            ],
            options={
                'db_table': 'loan_status_histories',
                'ordering': ['changed_at', 'loan_status_history_id'],
            },
        ),
        migrations.CreateModel(
            name='LoanTerms',
            fields=[
                ('loan_terms_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower_details_snapshot_json', models.JSONField()),
                ('nominee_details_snapshot_json', models.JSONField()),
                ('shareholding_snapshot_json', models.JSONField()),
                ('facility_type', models.CharField(max_length=60)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('purpose', models.TextField()),
                ('rate_of_interest', models.DecimalField(decimal_places=4, max_digits=8)),
                ('interest_rate_type', models.CharField(max_length=60)),
                ('interest_tenure', models.CharField(max_length=120)),
                ('repayment_date', models.DateField()),
                ('penalty_interest_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('other_charges_fees_json', models.JSONField()),
                ('security_details_json', models.JSONField()),
                ('dispute_resolution_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='loans.loanaccount')),
                ('loan_agreement_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_agreement_loan_terms', to='documents.documentfile')),
                ('term_sheet_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='term_sheet_loan_terms', to='documents.documentfile')),
            ],
            options={
                'db_table': 'loan_terms',
            },
        ),
        migrations.AddIndex(
            model_name='loanaccount',
            index=models.Index(fields=['member', 'loan_account_status'], name='idx_loan_member_status'),
        ),
        migrations.AddIndex(
            model_name='loanaccount',
            index=models.Index(fields=['loan_type', 'repayment_date'], name='idx_loan_type_repay'),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(check=models.Q(('sanctioned_amount__gt', 0)), name='loan_account_sanction_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(check=models.Q(('disbursed_amount__gte', 0)), name='loan_account_disbursed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(check=models.Q(('principal_outstanding__gte', 0)), name='loan_account_principal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(check=models.Q(('interest_outstanding__gte', 0)), name='loan_account_interest_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(check=models.Q(('charges_outstanding__gte', 0)), name='loan_account_charges_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(check=models.Q(('total_outstanding__gte', 0)), name='loan_account_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(check=models.Q(('loan_type__in', ('short_term', 'long_term'))), name='loan_account_type_bounded'),
        ),
        migrations.AddConstraint(
            model_name='loanaccount',
            constraint=models.CheckConstraint(check=models.Q(('disbursed_amount__lte', models.F('sanctioned_amount'))), name='loan_account_disbursed_lte_sanction'),
        ),
        migrations.AddIndex(
            model_name='loanstatushistory',
            index=models.Index(fields=['loan_account', 'changed_at'], name='idx_loan_status_time'),
        ),
        migrations.AddConstraint(
            model_name='loanterms',
            constraint=models.CheckConstraint(check=models.Q(('loan_amount__gt', 0)), name='loan_terms_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanterms',
            constraint=models.CheckConstraint(check=models.Q(('facility_type__in', ('short_term', 'long_term'))), name='loan_terms_facility_bounded'),
        ),
    ]
