# Generated by Django 5.0.6 on 2026-07-19 17:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0013_exception_provider_vocabulary'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('loans', '0002_repayment_schedule'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('repayment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repayment_source', models.CharField(db_index=True, default='direct_farmer', max_length=60)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=18)),
                ('received_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(max_length=60)),
                ('bank_reference_number', models.CharField(max_length=120)),
                ('bank_reference_number_normalized', models.CharField(max_length=120, unique=True)),
                ('bank_statement_line_id', models.UUIDField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=2000)),
                ('allocation_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('sap_posting_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('payload_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('capture_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='captured_repayment', to='identity.auditlog')),
                ('captured_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_repayments', to='identity.user')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loanaccount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='members.member')),
            ],
            options={
                'db_table': 'repayments',
            },
        ),
        migrations.CreateModel(
            name='RepaymentSapPostingObligation',
            fields=[
                ('obligation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('sap_entry_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_repayment_sap_obligations', to='identity.user')),
                ('posting_audit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_repayment_sap_obligation', to='identity.auditlog')),
                ('repayment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sap_posting_obligation', to='loans.repayment')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_sap_posting_obligation', to='communications.notification')),
            ],
            options={
                'db_table': 'repayment_sap_posting_obligations',
            },
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['loan_account', 'received_date'], name='idx_repay_account_date'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['member', 'received_date'], name='idx_repay_member_date'),
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.CheckConstraint(check=models.Q(('amount_received__gt', 0)), name='repayment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.CheckConstraint(check=models.Q(('repayment_source__in', ('direct_farmer', 'subsidiary_deduction'))), name='repayment_source_bounded'),
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.CheckConstraint(check=models.Q(('payment_method__in', ('rtgs', 'neft', 'subsidiary_transfer'))), name='repayment_method_bounded'),
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.CheckConstraint(check=models.Q(('allocation_status', 'pending')), name='repayment_allocation_pending'),
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.CheckConstraint(check=models.Q(('sap_posting_status__in', ('pending', 'posted'))), name='repayment_sap_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bank_reference_number', ''), _negated=True), models.Q(('bank_reference_number_normalized', ''), _negated=True), models.Q(('remarks', ''), _negated=True)), name='repayment_required_text'),
        ),
        migrations.AddConstraint(
            model_name='repaymentsappostingobligation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('posted_at__isnull', True), ('posted_by_user__isnull', True), ('posting_audit__isnull', True), ('sap_entry_reference__isnull', True), ('status', 'pending')), models.Q(('posted_at__isnull', False), ('posted_by_user__isnull', False), ('posting_audit__isnull', False), ('sap_entry_reference__isnull', False), ('status', 'posted')), _connector='OR'), name='repayment_sap_evidence_complete'),
        ),
        migrations.AddConstraint(
            model_name='repaymentsappostingobligation',
            constraint=models.CheckConstraint(check=models.Q(('sap_entry_reference__isnull', True), models.Q(('sap_entry_reference', ''), _negated=True), _connector='OR'), name='repayment_sap_reference_present'),
        ),
    ]
