# Generated by Django 5.0.6 on 2026-07-19 17:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('loans', '0003_repayment_repaymentsappostingobligation_and_more'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentAllocation',
            fields=[
                ('repayment_allocation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_to_principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocated_to_interest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocated_to_charges', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('principal_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('principal_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('charges_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('charges_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocation_rule', models.CharField(default='principal_first', max_length=80)),
                ('allocation_rule_version', models.CharField(default='v1', max_length=40)),
                ('exception_reason', models.CharField(blank=True, max_length=120, null=True)),
                ('allocated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'repayment_allocations',
            },
        ),
        migrations.CreateModel(
            name='RepaymentLedgerEntry',
            fields=[
                ('repayment_ledger_entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(db_index=True)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('principal_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('charges_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_outstanding', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actor_display_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'repayment_ledger_entries',
                'ordering': ['created_at', 'repayment_ledger_entry_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='repayment',
            name='repayment_allocation_pending',
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.CheckConstraint(check=models.Q(('allocation_status__in', ('pending', 'allocated', 'allocated_with_exception'))), name='repayment_allocation_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='repaymentschedule',
            constraint=models.CheckConstraint(check=models.Q(('paid_principal__lte', models.F('principal_due'))), name='schedule_paid_principal_lte_due'),
        ),
        migrations.AddConstraint(
            model_name='repaymentschedule',
            constraint=models.CheckConstraint(check=models.Q(('paid_interest__lte', models.F('interest_due'))), name='schedule_paid_interest_lte_due'),
        ),
        migrations.AddConstraint(
            model_name='repaymentschedule',
            constraint=models.CheckConstraint(check=models.Q(('paid_charges__lte', models.F('charges_due'))), name='schedule_paid_charges_lte_due'),
        ),
        migrations.AddField(
            model_name='repaymentallocation',
            name='allocated_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_allocations', to='identity.user'),
        ),
        migrations.AddField(
            model_name='repaymentallocation',
            name='allocation_audit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_allocation', to='identity.auditlog'),
        ),
        migrations.AddField(
            model_name='repaymentallocation',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_allocations', to='loans.loanaccount'),
        ),
        migrations.AddField(
            model_name='repaymentallocation',
            name='repayment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='allocation', to='loans.repayment'),
        ),
        migrations.AddField(
            model_name='repaymentallocation',
            name='repayment_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repayment_allocations', to='loans.repaymentschedule'),
        ),
        migrations.AddField(
            model_name='repaymentledgerentry',
            name='actor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_ledger_entries', to='identity.user'),
        ),
        migrations.AddField(
            model_name='repaymentledgerentry',
            name='allocation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='loans.repaymentallocation'),
        ),
        migrations.AddField(
            model_name='repaymentledgerentry',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_ledger_entries', to='loans.loanaccount'),
        ),
        migrations.AddConstraint(
            model_name='repaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocated_to_principal__gte', 0), ('allocated_to_interest__gte', 0), ('allocated_to_charges__gte', 0), ('unallocated_amount__gte', 0), ('principal_before__gte', 0), ('principal_after__gte', 0), ('interest_before__gte', 0), ('interest_after__gte', 0), ('charges_before__gte', 0), ('charges_after__gte', 0), ('total_before__gte', 0), ('total_after__gte', 0)), name='repayment_allocation_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='repaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocation_rule', 'principal_first'), ('allocation_rule_version', 'v1')), name='repayment_allocation_rule_v1'),
        ),
        migrations.AddConstraint(
            model_name='repaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('allocated_to_charges', 0)), name='repayment_allocation_no_unconfigured_charges'),
        ),
        migrations.AddConstraint(
            model_name='repaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('principal_before', models.F('principal_after') + models.F('allocated_to_principal'))), name='repay_alloc_principal_arithmetic'),
        ),
        migrations.AddConstraint(
            model_name='repaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('interest_before', models.F('interest_after') + models.F('allocated_to_interest'))), name='repay_alloc_interest_arithmetic'),
        ),
        migrations.AddConstraint(
            model_name='repaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('charges_before', models.F('charges_after') + models.F('allocated_to_charges'))), name='repay_alloc_charges_arithmetic'),
        ),
        migrations.AddConstraint(
            model_name='repaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('total_before', models.F('principal_before') + models.F('interest_before') + models.F('charges_before'))), name='repay_alloc_total_before_parts'),
        ),
        migrations.AddConstraint(
            model_name='repaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('total_after', models.F('principal_after') + models.F('interest_after') + models.F('charges_after'))), name='repay_alloc_total_after_parts'),
        ),
        migrations.AddConstraint(
            model_name='repaymentledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('credit_amount__gte', 0), ('principal_balance__gte', 0), ('interest_balance__gte', 0), ('charges_balance__gte', 0), ('total_outstanding__gte', 0)), name='repayment_ledger_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='repaymentledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('total_outstanding', models.F('principal_balance') + models.F('interest_balance') + models.F('charges_balance'))), name='repayment_ledger_total_parts'),
        ),
    ]
