# Generated by Django 5.0.6 on 2026-07-19 18:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('loans', '0004_principal_first_allocation'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('bank_statement_import_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sfpcl_bank_account', models.CharField(db_index=True, max_length=120)),
                ('source_checksum_sha256', models.CharField(max_length=64)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('payload_digest', models.CharField(max_length=64)),
                ('import_status', models.CharField(db_index=True, default='parsed', max_length=40)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bank_statement_imports',
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('bank_statement_line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('transaction_date', models.DateField(blank=True, db_index=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('narration', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('reference_normalized', models.CharField(blank=True, db_index=True, max_length=120)),
                ('loan_account_reference', models.CharField(blank=True, max_length=120)),
                ('parse_status', models.CharField(db_index=True, default='parsed', max_length=40)),
                ('match_status', models.CharField(db_index=True, default='unmatched', max_length=40)),
                ('match_reason_code', models.CharField(max_length=80)),
                ('match_decision_reason', models.CharField(blank=True, max_length=500)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bank_statement_lines',
                'ordering': ['statement_import_id', 'line_number', 'bank_statement_line_id'],
            },
        ),
        migrations.AddField(
            model_name='repayment',
            name='statement_match_status',
            field=models.CharField(db_index=True, default='not_linked', max_length=40),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='bank_statement_line_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.CheckConstraint(check=models.Q(('statement_match_status__in', ('not_linked', 'matched_exact', 'manual_match_exception'))), name='repayment_statement_match_status_bounded'),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='imported_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_imports', to='identity.user'),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='source_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_import', to='documents.documentfile'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='match_audit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_match', to='identity.auditlog'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_bank_statement_lines', to='identity.user'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_repayment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_bank_statement_line', to='loans.repayment'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='statement_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='loans.bankstatementimport'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementimport',
            constraint=models.UniqueConstraint(fields=('sfpcl_bank_account', 'source_checksum_sha256'), name='uniq_bank_statement_account_checksum'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementimport',
            constraint=models.CheckConstraint(check=models.Q(('import_status__in', ('parsed', 'parsed_with_exceptions'))), name='bank_statement_import_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementimport',
            constraint=models.CheckConstraint(check=models.Q(('sfpcl_bank_account', ''), _negated=True), name='bank_statement_import_account_required'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.UniqueConstraint(fields=('statement_import', 'line_number'), name='uniq_bank_statement_import_line'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(check=models.Q(('line_number__gt', 0)), name='bank_statement_line_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(check=models.Q(('amount__isnull', True), ('amount__gt', 0), _connector='OR'), name='bank_statement_line_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(check=models.Q(('parse_status__in', ('parsed', 'parse_failed'))), name='bank_statement_parse_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(check=models.Q(('match_status__in', ('unmatched', 'matched', 'exception'))), name='bank_statement_match_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('match_audit__isnull', False), ('match_status', 'matched'), ('matched_at__isnull', False), ('matched_by_user__isnull', False), ('matched_repayment__isnull', False)), models.Q(models.Q(('match_status', 'matched'), _negated=True), ('matched_repayment__isnull', True), ('match_audit__isnull', True), ('matched_at__isnull', True)), _connector='OR'), name='bank_statement_match_evidence_coherent'),
        ),
    ]
