# Generated by Django 5.0.6 on 2026-07-19 21:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


_COLLECTION_ACCOUNT_CONTEXT = "loans.bank_statement_import.legacy_collection_account"


def migrate_statement_evidence_forward(apps, schema_editor):
    from sfpcl_credit.shared.encryption import FieldEncryption

    BankStatementImport = apps.get_model("loans", "BankStatementImport")
    BankStatementLine = apps.get_model("loans", "BankStatementLine")
    Repayment = apps.get_model("loans", "Repayment")
    MigrationException = apps.get_model("loans", "StatementLinkMigrationException")
    SourceBankGovernance = apps.get_model(
        "configurations", "SourceBankAccountGovernance"
    )

    active_bank_ids = set(
        SourceBankGovernance.objects.filter(status="active").values_list(
            "bank_account_id", flat=True
        )
    )
    for statement_import in BankStatementImport.objects.all().iterator():
        raw = statement_import.sfpcl_bank_account
        try:
            candidate_id = uuid.UUID(str(raw))
        except (TypeError, ValueError, AttributeError):
            candidate_id = None
        if candidate_id in active_bank_ids:
            statement_import.collection_bank_account_id = candidate_id
        else:
            statement_import.legacy_collection_account_encrypted = (
                FieldEncryption.encrypt(_COLLECTION_ACCOUNT_CONTEXT, raw)
            )
            statement_import.import_status = "parsed_with_exceptions"
        statement_import.save(
            update_fields=[
                "collection_bank_account",
                "legacy_collection_account_encrypted",
                "import_status",
            ]
        )

    for repayment in Repayment.objects.exclude(
        bank_statement_line_id__isnull=True
    ).iterator():
        line = BankStatementLine.objects.filter(
            pk=repayment.bank_statement_line_id
        ).first()
        if line is None:
            reason = "legacy_statement_line_orphan"
        elif line.matched_repayment_id is None:
            reason = "legacy_statement_link_incomplete"
        elif line.matched_repayment_id != repayment.pk:
            reason = "legacy_statement_link_contradiction"
        else:
            continue
        MigrationException.objects.create(
            repayment_id=repayment.pk,
            legacy_statement_line_id=repayment.bank_statement_line_id,
            reason_code=reason,
        )


def migrate_statement_evidence_backward(apps, schema_editor):
    from sfpcl_credit.shared.encryption import FieldEncryption

    BankStatementImport = apps.get_model("loans", "BankStatementImport")
    BankStatementLine = apps.get_model("loans", "BankStatementLine")
    Repayment = apps.get_model("loans", "Repayment")
    MigrationException = apps.get_model("loans", "StatementLinkMigrationException")

    for statement_import in BankStatementImport.objects.all().iterator():
        if statement_import.collection_bank_account_id:
            raw = str(statement_import.collection_bank_account_id)
        else:
            raw = FieldEncryption.decrypt(
                _COLLECTION_ACCOUNT_CONTEXT,
                statement_import.legacy_collection_account_encrypted,
            )
        statement_import.sfpcl_bank_account = raw
        statement_import.save(update_fields=["sfpcl_bank_account"])

    exceptions = {
        row.repayment_id: row
        for row in MigrationException.objects.all().iterator()
    }
    canonical = {
        line.matched_repayment_id: line
        for line in BankStatementLine.objects.exclude(
            matched_repayment_id__isnull=True
        ).iterator()
    }
    for repayment in Repayment.objects.all().iterator():
        line = canonical.get(repayment.pk)
        exception = exceptions.get(repayment.pk)
        repayment.bank_statement_line_id = (
            line.pk if line is not None else exception.legacy_statement_line_id
            if exception is not None
            else None
        )
        repayment.statement_match_status = (
            "manual_match_exception"
            if line is not None
            and line.match_reason_code == "authorised_manual_evidence_match"
            else "matched_exact"
            if line is not None
            else "not_linked"
        )
        repayment.save(
            update_fields=["bank_statement_line_id", "statement_match_status"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_source_bank_reviewable_rationale'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('loans', '0006_repayment_allocation_admission'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementLinkMigrationException',
            fields=[
                ('statement_link_migration_exception_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_statement_line_id', models.UUIDField()),
                ('reason_code', models.CharField(max_length=80)),
                ('resolution_status', models.CharField(default='unresolved', max_length=40)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'statement_link_migration_exceptions',
            },
        ),
        migrations.RemoveConstraint(
            model_name='bankstatementimport',
            name='uniq_bank_statement_account_checksum',
        ),
        migrations.RemoveConstraint(
            model_name='bankstatementimport',
            name='bank_statement_import_account_required',
        ),
        migrations.RemoveConstraint(
            model_name='bankstatementline',
            name='bank_statement_match_evidence_coherent',
        ),
        migrations.RemoveConstraint(
            model_name='repayment',
            name='repayment_statement_match_status_bounded',
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='collection_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_imports', to='members.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='legacy_collection_account_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='statementlinkmigrationexception',
            name='repayment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='statement_link_migration_exception', to='loans.repayment'),
        ),
        migrations.AlterField(
            model_name='bankstatementimport',
            name='sfpcl_bank_account',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.RunPython(
            migrate_statement_evidence_forward,
            migrate_statement_evidence_backward,
        ),
        migrations.RemoveField(
            model_name='bankstatementimport',
            name='sfpcl_bank_account',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='bank_statement_line_id',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='statement_match_status',
        ),
        migrations.AddConstraint(
            model_name='bankstatementimport',
            constraint=models.UniqueConstraint(fields=('collection_bank_account', 'source_checksum_sha256'), name='uniq_bank_statement_account_checksum'),
        ),
        migrations.AddConstraint(
            model_name='statementlinkmigrationexception',
            constraint=models.CheckConstraint(check=models.Q(('reason_code__in', ('legacy_statement_line_orphan', 'legacy_statement_link_incomplete', 'legacy_statement_link_contradiction'))), name='statement_link_migration_reason_bounded'),
        ),
        migrations.AddConstraint(
            model_name='statementlinkmigrationexception',
            constraint=models.CheckConstraint(check=models.Q(('resolution_status', 'unresolved')), name='statement_link_migration_unresolved'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(
                        match_status='matched',
                        matched_repayment__isnull=False,
                        matched_by_user__isnull=False,
                        match_audit__isnull=False,
                        matched_at__isnull=False,
                    )
                    | (
                        ~models.Q(match_status='matched')
                        & models.Q(matched_repayment__isnull=True)
                        & (
                            models.Q(
                                match_status='exception',
                                match_audit__isnull=False,
                                matched_by_user__isnull=False,
                                matched_at__isnull=False,
                            )
                            | models.Q(
                                match_audit__isnull=True,
                                matched_at__isnull=True,
                            )
                        )
                    )
                ),
                name='bank_statement_match_evidence_coherent',
            ),
        ),
    ]
