# Generated by Django 5.0.6 on 2026-07-19 22:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('legal_documents', '0015_checklist_constraint_state_owner_anchor'),
        ('loans', '0007_statement_evidence_owner_scope_closure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidiaryDeductionEvidence',
            fields=[
                ('subsidiary_deduction_evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subsidiary_company_id', models.UUIDField(db_index=True)),
                ('produce_payment_reference', models.CharField(max_length=255)),
                ('produce_payment_reference_normalized', models.CharField(max_length=255)),
                ('transfer_reference', models.CharField(max_length=120)),
                ('transfer_reference_normalized', models.CharField(max_length=120, unique=True)),
                ('reconciliation_status', models.CharField(db_index=True, default='pending_statement', max_length=60)),
                ('treasury_verification_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('treasury_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('repayment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subsidiary_deduction_evidence', to='loans.repayment')),
                ('treasury_verification_audit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsidiary_treasury_verification', to='identity.auditlog')),
                ('treasury_verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_subsidiary_deductions', to='identity.user')),
                ('tri_party_agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsidiary_deduction_evidence', to='legal_documents.loandocument')),
            ],
            options={
                'db_table': 'subsidiary_deduction_evidence',
            },
        ),
        migrations.AddConstraint(
            model_name='subsidiarydeductionevidence',
            constraint=models.UniqueConstraint(fields=('subsidiary_company_id', 'produce_payment_reference_normalized'), name='uniq_subsidiary_produce_reference'),
        ),
        migrations.AddConstraint(
            model_name='subsidiarydeductionevidence',
            constraint=models.CheckConstraint(check=models.Q(('reconciliation_status__in', ('pending_statement', 'reconciled', 'exception'))), name='subsidiary_reconciliation_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='subsidiarydeductionevidence',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('treasury_verification_audit__isnull', True), ('treasury_verification_status', 'pending'), ('treasury_verified_at__isnull', True), ('treasury_verified_by_user__isnull', True)), models.Q(('treasury_verification_audit__isnull', False), ('treasury_verification_status', 'verified'), ('treasury_verified_at__isnull', False), ('treasury_verified_by_user__isnull', False)), _connector='OR'), name='subsidiary_treasury_evidence_coherent'),
        ),
        migrations.AddConstraint(
            model_name='subsidiarydeductionevidence',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('produce_payment_reference', ''), _negated=True), models.Q(('produce_payment_reference_normalized', ''), _negated=True), models.Q(('transfer_reference', ''), _negated=True), models.Q(('transfer_reference_normalized', ''), _negated=True)), name='subsidiary_references_required'),
        ),
    ]
