# Generated by Django 5.0.6 on 2026-07-20 19:35

import django.db.models.deletion
from django.db import migrations, models


def validate_retained_dpd_pointers(apps, schema_editor):
    LoanAccount = apps.get_model("loans", "LoanAccount")
    DpdStatus = apps.get_model("monitoring", "DpdStatus")
    DpdOperationalBucketScheme = apps.get_model(
        "monitoring", "DpdOperationalBucketScheme"
    )
    database = schema_editor.connection.alias
    pointers = (
        LoanAccount.objects.using(database)
        .exclude(current_dpd_status_id__isnull=True)
        .values_list("loan_account_id", "current_dpd_status_id")
    )
    for loan_account_id, dpd_status_id in pointers.iterator():
        if not DpdStatus.objects.using(database).filter(
            pk=dpd_status_id,
            loan_account_id=loan_account_id,
        ).exists():
            raise RuntimeError(
                "Cannot add DPD pointer integrity: loan account "
                f"{loan_account_id} references missing or foreign snapshot {dpd_status_id}."
            )
    snapshots = DpdStatus._base_manager.using(database).values(
        "dpd_status_id",
        "operational_scheme_id",
        "calculation_inputs_json",
    )
    for snapshot in snapshots.iterator():
        inputs = dict(snapshot["calculation_inputs_json"] or {})
        if "policy_decision" in inputs:
            continue
        scheme = None
        if snapshot["operational_scheme_id"] is not None:
            scheme = (
                DpdOperationalBucketScheme._base_manager.using(database)
                .filter(pk=snapshot["operational_scheme_id"])
                .values(
                    "dpd_operational_bucket_scheme_id",
                    "version",
                    "effective_from",
                    "effective_to",
                    "first_upper_days",
                    "second_upper_days",
                    "third_upper_days",
                )
                .first()
            )
            if scheme is None:
                raise RuntimeError(
                    "Cannot freeze DPD policy provenance: retained operational scheme "
                    f"{snapshot['operational_scheme_id']} is missing."
                )
        inputs["policy_decision"] = {
            "sop_policy_version": "SFPCL-SOP-DPD-1",
            "sop_boundary_convention": {
                "anniversary_basis": "calendar_anniversary",
                "leap_day_anniversary": "february_28",
                "first_anniversary_inclusive": True,
                "second_anniversary_inclusive": True,
                "third_anniversary_inclusive": True,
                "after_third_anniversary_bucket": "more_than_three_years",
            },
            "operational_scheme_id": (
                str(scheme["dpd_operational_bucket_scheme_id"])
                if scheme is not None
                else None
            ),
            "operational_scheme_version": scheme["version"] if scheme else None,
            "operational_effective_from": (
                scheme["effective_from"].isoformat() if scheme else None
            ),
            "operational_effective_to": (
                scheme["effective_to"].isoformat()
                if scheme and scheme["effective_to"] is not None
                else None
            ),
            "operational_boundaries": (
                {
                    "first_upper_days": scheme["first_upper_days"],
                    "second_upper_days": scheme["second_upper_days"],
                    "third_upper_days": scheme["third_upper_days"],
                }
                if scheme
                else None
            ),
        }
        DpdStatus._base_manager.using(database).filter(
            pk=snapshot["dpd_status_id"]
        ).update(calculation_inputs_json=inputs)


def create_immediate_dpd_pointer_guard(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE FUNCTION enforce_current_dpd_pointer_exists()
            RETURNS trigger AS $$
            BEGIN
                IF NEW.current_dpd_status_id IS NOT NULL
                   AND NOT EXISTS (
                       SELECT 1 FROM dpd_statuses
                       WHERE dpd_status_id = NEW.current_dpd_status_id
                         AND loan_account_id = NEW.loan_account_id
                   )
                THEN
                    RAISE EXCEPTION 'current DPD snapshot does not exist for this loan'
                        USING ERRCODE = '23503';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        schema_editor.execute(
            """
            CREATE TRIGGER loan_account_current_dpd_exists
            BEFORE INSERT OR UPDATE OF current_dpd_status_id ON loan_accounts
            FOR EACH ROW EXECUTE FUNCTION enforce_current_dpd_pointer_exists();
            """
        )
    elif vendor == "sqlite":
        for action in ("INSERT", "UPDATE OF current_dpd_status_id"):
            suffix = "insert" if action == "INSERT" else "update"
            schema_editor.execute(
                f"""
                CREATE TRIGGER loan_account_current_dpd_exists_{suffix}
                BEFORE {action} ON loan_accounts
                FOR EACH ROW
                WHEN NEW.current_dpd_status_id IS NOT NULL
                     AND NOT EXISTS (
                         SELECT 1 FROM dpd_statuses
                         WHERE dpd_status_id = NEW.current_dpd_status_id
                           AND loan_account_id = NEW.loan_account_id
                     )
                BEGIN
                    SELECT RAISE(ABORT, 'current DPD snapshot does not exist for this loan');
                END;
                """
            )


def drop_immediate_dpd_pointer_guard(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS loan_account_current_dpd_exists ON loan_accounts;"
        )
        schema_editor.execute(
            "DROP FUNCTION IF EXISTS enforce_current_dpd_pointer_exists();"
        )
    elif vendor == "sqlite":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS loan_account_current_dpd_exists_insert;"
        )
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS loan_account_current_dpd_exists_update;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_subsidiary_deduction_reconciliation'),
        ('monitoring', '0002_reminder_queue'),
    ]

    operations = [
        migrations.RunPython(validate_retained_dpd_pointers, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name="loanaccount",
                    name="current_dpd_status_id",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="current_dpd_status_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_for_loan_accounts",
                        to="monitoring.dpdstatus",
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="loanaccount",
                    name="current_dpd_status_id",
                ),
                migrations.AddField(
                    model_name="loanaccount",
                    name="current_dpd_status",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="current_dpd_status_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_for_loan_accounts",
                        to="monitoring.dpdstatus",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_immediate_dpd_pointer_guard,
            drop_immediate_dpd_pointer_guard,
        ),
    ]
