# Generated by Django 5.0.6 on 2026-07-11 03:37

import django.db.models.deletion
from django.db import migrations, models


def link_unambiguous_sanction_events(apps, schema_editor):
    ApprovalCase = apps.get_model('approvals', 'ApprovalCase')
    WorkflowEvent = apps.get_model('workflows', 'WorkflowEvent')
    for case in ApprovalCase.objects.filter(workflow_event_id__isnull=True).iterator():
        candidates = WorkflowEvent.objects.filter(
            workflow_name='sanction_submission',
            entity_type='loan_application',
            entity_id=case.loan_application_id,
            trigger_reason__contains=f'approval case {case.pk}',
        )
        if candidates.count() == 1:
            case.workflow_event_id = candidates.values_list(
                'workflow_event_id', flat=True
            ).get()
            case.save(update_fields=['workflow_event'])


def unlink_sanction_events(apps, schema_editor):
    apps.get_model('approvals', 'ApprovalCase').objects.update(workflow_event=None)


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('workflows', '0001_canonical_workflow_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalcase',
            name='workflow_event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanction_approval_case', to='workflows.workflowevent'),
        ),
        migrations.RunPython(link_unambiguous_sanction_events, unlink_sanction_events),
    ]
