# Generated by Django 5.0.6 on 2026-07-12 22:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


def seed_approval_matrix_rules(apps, schema_editor):
    apps.get_model('approvals', 'ApprovalConfigurationLock').objects.get_or_create(
        lock_name='approval_matrix'
    )
    Rule = apps.get_model('approvals', 'ApprovalMatrixRule')
    rules = [
        {
            'decision_type': 'loan_sanction', 'amount_min': Decimal('0.00'),
            'amount_max': Decimal('500000.00'), 'condition_code': None,
            'required_approver_roles_json': ['cfo', 'director'],
            'required_director_count': 1, 'register_required': 'credit_sanction_register',
            'version_number': 'seed-2026-up-to-5l',
        },
        {
            'decision_type': 'loan_sanction', 'amount_min': Decimal('500000.01'),
            'amount_max': None, 'condition_code': None,
            'required_approver_roles_json': ['cfo', 'director'],
            'required_director_count': 2, 'register_required': 'credit_sanction_register',
            'version_number': 'seed-2026-above-5l',
        },
        {
            'decision_type': 'loan_sanction', 'amount_min': Decimal('0.00'),
            'amount_max': None, 'condition_code': 'exceeds_permissible_limit',
            'required_approver_roles_json': ['cfo', 'director'],
            'required_director_count': 2, 'register_required': 'exception_register',
            'version_number': 'seed-2026-exceeds-limit',
        },
    ]
    for values in rules:
        Rule.objects.get_or_create(
            version_number=values.pop('version_number'),
            defaults={**values, 'joint_approval_required_flag': True,
                      'effective_from': '2026-04-01', 'status': 'active'},
        )


def unseed_approval_matrix_rules(apps, schema_editor):
    apps.get_model('approvals', 'ApprovalMatrixRule').objects.filter(
        version_number__startswith='seed-2026-'
    ).delete()
    apps.get_model('approvals', 'ApprovalConfigurationLock').objects.filter(
        lock_name='approval_matrix'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approvalcase_workflow_event'),
        ('identity', '0003_portal_member_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalConfigurationLock',
            fields=[('lock_name', models.CharField(max_length=40, primary_key=True, serialize=False))],
            options={'db_table': 'approval_configuration_locks'},
        ),
        migrations.CreateModel(
            name='ApprovalMatrixRule',
            fields=[
                ('approval_matrix_rule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(db_index=True, max_length=80)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('condition_code', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('required_approver_roles_json', models.JSONField(default=list)),
                ('required_director_count', models.PositiveSmallIntegerField(default=0)),
                ('joint_approval_required_flag', models.BooleanField(default=True)),
                ('register_required', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=40)),
                ('version_number', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'approval_matrix_rules',
                'ordering': ['decision_type', 'condition_code', 'amount_min', 'effective_from'],
                'indexes': [models.Index(fields=['decision_type', 'condition_code', 'status'], name='idx_matrix_route_status')],
            },
        ),
        migrations.CreateModel(
            name='SanctionCommittee',
            fields=[
                ('sanction_committee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('committee_name', models.CharField(max_length=150)),
                ('board_meeting_reference', models.CharField(max_length=255)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=40)),
                ('version_number', models.CharField(max_length=40)),
                ('cfo_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cfo_committees', to='identity.user')),
                ('director_1_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director_1_committees', to='identity.user')),
                ('director_2_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director_2_committees', to='identity.user')),
            ],
            options={
                'db_table': 'sanction_committees',
                'ordering': ['-effective_from', '-sanction_committee_id'],
            },
        ),
        migrations.RunPython(seed_approval_matrix_rules, unseed_approval_matrix_rules),
    ]
