# Generated by Django 5.0.6 on 2026-07-13 08:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal, InvalidOperation
from django.db import migrations, models


def seed_source_read_scope_grants(apps, schema_editor):
    Role = apps.get_model("identity", "Role")
    Grant = apps.get_model("approvals", "ApprovalCaseReadScopeGrant")
    for role_code, scope_type in (
        ("company_secretary", "legal_readonly"),
        ("internal_auditor", "audit_readonly"),
    ):
        role = Role.objects.filter(role_code=role_code).first()
        if role is not None:
            Grant.objects.get_or_create(
                role=role,
                scope_type=scope_type,
                defaults={"status": "active"},
            )


def remove_source_read_scope_grants(apps, schema_editor):
    Grant = apps.get_model("approvals", "ApprovalCaseReadScopeGrant")
    Grant.objects.filter(
        role__role_code="company_secretary", scope_type="legal_readonly"
    ).delete()
    Grant.objects.filter(
        role__role_code="internal_auditor", scope_type="audit_readonly"
    ).delete()


def _same_amount(first, second):
    try:
        return Decimal(str(first)) == Decimal(str(second))
    except (InvalidOperation, TypeError, ValueError):
        return False


def _amount_inside_projection(amount, matrix):
    try:
        amount = Decimal(str(amount))
        minimum = Decimal(str(matrix["amount_min"]))
        maximum = (
            Decimal(str(matrix["amount_max"]))
            if matrix.get("amount_max") is not None
            else None
        )
    except (KeyError, InvalidOperation, TypeError, ValueError):
        return False
    return amount >= minimum and (maximum is None or amount <= maximum)


def _matrix_projection_is_coherent(case, matrix):
    condition = matrix.get("condition_code") or ""
    roles = matrix.get("required_approver_roles")
    director_count = matrix.get("required_director_count")
    return (
        case.approval_type == "sanction"
        and case.related_entity_type == "loan_application"
        and str(case.related_entity_id) == str(case.loan_application_id)
        and matrix.get("decision_type") == "loan_sanction"
        and _same_amount(matrix.get("amount"), case.amount)
        and _amount_inside_projection(case.amount, matrix)
        and condition == (case.exception_condition_code or "")
        and condition in ("", "exceeds_permissible_limit")
        and (
            (not condition and not case.exception_reason)
            or (
                condition
                and bool(case.exception_reason.strip())
                and case.exception_reason == case.reason_for_approval
            )
        )
        and isinstance(roles, list)
        and roles == ["cfo", "director"]
        and isinstance(director_count, int)
        and director_count in (1, 2)
        and matrix.get("joint_approval_required") is True
        and isinstance(matrix.get("register_required"), str)
        and bool(matrix["register_required"].strip())
        and case.loan_appraisal_note.reviewed_at is not None
        and case.decision_date
        == django.utils.timezone.localdate(case.loan_appraisal_note.reviewed_at)
        and case.amount == case.loan_appraisal_note.recommended_amount
    )


def _approver_snapshot_is_coherent(required, matrix, committee):
    cfo_id = str(committee.get("cfo_user_id") or "")
    director_ids = committee.get("director_user_ids")
    if (
        not cfo_id
        or not isinstance(director_ids, list)
        or len(director_ids) != 2
        or any(not item for item in director_ids)
    ):
        return False
    director_ids = [str(item) for item in director_ids]
    committee_ids = [cfo_id, *director_ids]
    if len(set(committee_ids)) != 3:
        return False
    expected = [("cfo", cfo_id)] + [
        ("director", user_id)
        for user_id in director_ids[: matrix["required_director_count"]]
    ]
    if len(required) != len(expected):
        return False
    actual = []
    for item in required:
        if (
            not isinstance(item, dict)
            or not isinstance(item.get("full_name"), str)
            or not item["full_name"].strip()
        ):
            return False
        actual.append((item.get("role_code"), str(item.get("user_id") or "")))
    return actual == expected and len({user_id for _, user_id in actual}) == len(actual)


def _loan_limit_provenance_is_complete(case):
    provenance = case.loan_limit_provenance_json
    required = (
        "loan_limit_assessment_id",
        "loan_application_id",
        "exception_required_flag",
        "calculation_rule_version",
        "policy_config_id",
        "policy_name",
        "calculated_at",
    )
    snapshot = case.loan_appraisal_note.loan_limit_snapshot_json
    condition_requires_exception = bool(case.exception_condition_code)
    return (
        isinstance(provenance, dict)
        and all(provenance.get(key) not in (None, "") for key in required)
        and str(provenance["loan_limit_assessment_id"])
        == str(case.loan_appraisal_note.loan_limit_assessment_id_snapshot)
        and str(provenance["loan_application_id"]) == str(case.loan_application_id)
        and isinstance(provenance["exception_required_flag"], bool)
        and provenance["exception_required_flag"] == case.exception_required_flag
        and (not provenance["exception_required_flag"] or condition_requires_exception)
        and isinstance(snapshot, dict)
        and all(provenance.get(key) == snapshot.get(key) for key in required)
    )


def _is_routable_approval_case(case):
    required = case.required_approvers_json
    matrix = case.matrix_projection_json
    committee = case.committee_projection_json
    return (
        case.version >= 2
        and case.approval_matrix_rule_id is not None
        and bool(case.approval_matrix_rule_version)
        and case.sanction_committee_id is not None
        and bool(case.sanction_committee_version)
        and case.decision_date is not None
        and case.amount is not None
        and bool(case.related_entity_type)
        and case.related_entity_id is not None
        and isinstance(required, list)
        and bool(required)
        and isinstance(case.excluded_approvers_json, list)
        and all(
            isinstance(item, dict)
            and item.get("role_code")
            and item.get("user_id")
            and item.get("full_name")
            for item in required
        )
        and isinstance(matrix, dict)
        and matrix.get("approval_matrix_rule_id") == str(case.approval_matrix_rule_id)
        and matrix.get("version_number") == case.approval_matrix_rule_version
        and matrix.get("decision_date") == case.decision_date.isoformat()
        and _matrix_projection_is_coherent(case, matrix)
        and isinstance(committee, dict)
        and committee.get("sanction_committee_id") == str(case.sanction_committee_id)
        and committee.get("version_number") == case.sanction_committee_version
        and committee.get("decision_date") == case.decision_date.isoformat()
        and _approver_snapshot_is_coherent(required, matrix, committee)
        and _loan_limit_provenance_is_complete(case)
    )


def backfill_routing_snapshot_coherence(apps, schema_editor):

    ApprovalCase = apps.get_model("approvals", "ApprovalCase")
    RequiredApprover = apps.get_model("approvals", "ApprovalCaseRequiredApprover")
    for case in ApprovalCase.objects.select_related(
        "loan_application", "loan_appraisal_note"
    ).iterator():
        ApprovalCase.objects.filter(pk=case.pk).update(
            routing_snapshot_is_coherent=_is_routable_approval_case(case)
        )
        indexed_user_ids = set()
        if isinstance(case.required_approvers_json, list):
            for item in case.required_approvers_json:
                try:
                    indexed_user_ids.add(uuid.UUID(str(item.get("user_id"))))
                except (AttributeError, TypeError, ValueError):
                    continue
        RequiredApprover.objects.bulk_create(
            [
                RequiredApprover(approval_case=case, user_id=user_id)
                for user_id in indexed_user_ids
            ],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0009_sanction_decision_and_case_closure'),
        ('credit', '0007_eligibility_active_member_snapshot'),
        ('identity', '0003_portal_member_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalcase',
            name='routing_snapshot_is_coherent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ApprovalCaseRequiredApprover',
            fields=[
                ('approval_case_required_approver_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('approval_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_approver_index', to='approvals.approvalcase')),
            ],
            options={
                'db_table': 'approval_case_required_approvers',
            },
        ),
        migrations.CreateModel(
            name='ApprovalCaseReadScopeGrant',
            fields=[
                ('approval_case_read_scope_grant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('legal_readonly', 'Legal read-only'), ('audit_readonly', 'Audit read-only'), ('management_readonly', 'Management read-only')], max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_case_read_scope_grants', to='identity.role')),
            ],
            options={
                'db_table': 'approval_case_read_scope_grants',
                'indexes': [models.Index(fields=['role', 'status', 'scope_type'], name='idx_case_read_role_scope')],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalcaserequiredapprover',
            constraint=models.UniqueConstraint(fields=('approval_case', 'user_id'), name='unique_case_required_approver'),
        ),
        migrations.AddConstraint(
            model_name='approvalcasereadscopegrant',
            constraint=models.UniqueConstraint(fields=('role', 'scope_type'), name='unique_case_read_role_scope'),
        ),
        migrations.AddConstraint(
            model_name='approvalcasereadscopegrant',
            constraint=models.CheckConstraint(check=models.Q(('scope_type__in', ['legal_readonly', 'audit_readonly', 'management_readonly'])), name='case_read_scope_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='approvalcasereadscopegrant',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'inactive'])), name='case_read_scope_status_valid'),
        ),
        migrations.RunPython(
            seed_source_read_scope_grants,
            remove_source_read_scope_grants,
        ),
        migrations.RunPython(
            backfill_routing_snapshot_coherence,
            migrations.RunPython.noop,
        ),
    ]
