# Generated by Django 5.0.6 on 2026-07-13 09:34

import django.db.models.deletion
from django.db import migrations, models


def backfill_first_approval_cycle(apps, schema_editor):
    ApprovalCase = apps.get_model("approvals", "ApprovalCase")
    AppraisalReviewDecision = apps.get_model("credit", "AppraisalReviewDecision")
    for case in ApprovalCase.objects.select_related(
        "loan_application", "loan_appraisal_note__risk_assessment"
    ).iterator():
        note = case.loan_appraisal_note
        application = case.loan_application
        review = (
            AppraisalReviewDecision.objects.filter(
                loan_appraisal_note_id=note.pk,
                decision="reviewed",
                decided_at__lte=case.submitted_at,
            )
            .order_by("decided_at", "appraisal_review_decision_id")
            .last()
        )
        eligibility = note.eligibility_snapshot_json or {}
        loan_limit = note.loan_limit_snapshot_json or {}
        risk = note.risk_assessment
        case.cycle_number = 1
        case.appraisal_revision = 1
        case.appraisal_review_decision_id = review.pk if review else None
        case.appraisal_facts_json = {
            "eligibility": eligibility,
            "loan_amounts": {
                "requested_amount": (
                    f"{application.required_loan_amount:.2f}"
                    if application.required_loan_amount is not None
                    else None
                ),
                "eligible_amount": loan_limit.get("final_eligible_loan_amount"),
                "recommended_amount": f"{note.recommended_amount:.2f}",
            },
            "purpose": {
                "category": application.purpose_category or None,
                "description": application.declared_purpose or None,
            },
            "compliance_checks": {
                key: eligibility.get(key)
                for key in (
                    "member_active_check",
                    "default_check",
                    "terms_acceptance_check",
                    "purpose_check",
                )
            },
            "borrowing_history": note.borrower_summary,
            "risk": {
                "risk_assessment_id": str(risk.pk),
                "market_risk_rating": risk.market_risk_rating,
                "operational_risk_rating": risk.operational_risk_rating,
                "borrower_risk_rating": risk.borrower_risk_rating,
                "overall_risk_rating": risk.overall_risk_rating,
                "risk_mitigation_notes": risk.risk_mitigation_notes,
            },
            "documentation_completeness": {
                "status": application.completeness_status,
                "document_check": eligibility.get("document_check"),
            },
            "source_references": {
                "application": f"/api/v1/loan-applications/{application.pk}/",
                "appraisal": f"/api/v1/loan-applications/{application.pk}/appraisal-note/",
                "eligibility": f"/api/v1/loan-applications/{application.pk}/eligibility-assessment/",
                "loan_limit": f"/api/v1/loan-applications/{application.pk}/loan-limit-assessment/",
            },
        }
        case.save(
            update_fields=[
                "cycle_number",
                "appraisal_revision",
                "appraisal_review_decision",
                "appraisal_facts_json",
            ]
        )


def clear_first_approval_cycle_backfill(apps, schema_editor):
    ApprovalCase = apps.get_model("approvals", "ApprovalCase")
    ApprovalCase.objects.update(
        appraisal_review_decision=None,
        appraisal_revision=1,
        appraisal_facts_json={},
        cycle_number=1,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_witness'),
        ('approvals', '0010_approvalcasereadscopegrant_and_more'),
        ('credit', '0007_eligibility_active_member_snapshot'),
        ('identity', '0003_portal_member_auth'),
        ('workflows', '0001_canonical_workflow_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalcase',
            name='appraisal_facts_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='approvalcase',
            name='appraisal_review_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanction_approval_cases', to='credit.appraisalreviewdecision'),
        ),
        migrations.AddField(
            model_name='approvalcase',
            name='appraisal_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='approvalcase',
            name='cycle_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='approvalcase',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanction_approval_cases', to='applications.loanapplication'),
        ),
        migrations.AlterField(
            model_name='approvalcase',
            name='loan_appraisal_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanction_approval_cases', to='credit.loanappraisalnote'),
        ),
        migrations.RunPython(
            backfill_first_approval_cycle,
            clear_first_approval_cycle_backfill,
        ),
        migrations.AddConstraint(
            model_name='approvalcase',
            constraint=models.CheckConstraint(check=models.Q(('cycle_number__gte', 1)), name='approval_case_cycle_positive'),
        ),
        migrations.AddConstraint(
            model_name='approvalcase',
            constraint=models.CheckConstraint(check=models.Q(('appraisal_revision__gte', 1)), name='approval_case_appraisal_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='approvalcase',
            constraint=models.CheckConstraint(check=models.Q(('cycle_number', 1), ('appraisal_review_decision__isnull', False), _connector='OR'), name='approval_later_cycle_review_required'),
        ),
        migrations.AddConstraint(
            model_name='approvalcase',
            constraint=models.UniqueConstraint(fields=('loan_application', 'cycle_number'), name='unique_application_approval_cycle'),
        ),
        migrations.AddConstraint(
            model_name='approvalcase',
            constraint=models.UniqueConstraint(condition=models.Q(('current_status', 'pending')), fields=('loan_application',), name='unique_pending_application_approval_cycle'),
        ),
    ]
