# Generated by Django 5.0.6 on 2026-07-13 10:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def backfill_cycle_maker_facts(apps, schema_editor):
    ApprovalCase = apps.get_model('approvals', 'ApprovalCase')
    for case in ApprovalCase.objects.select_related(
        'loan_application', 'loan_appraisal_note', 'appraisal_review_decision'
    ).iterator():
        facts = dict(case.appraisal_facts_json or {})
        if facts.get('maker_checker'):
            continue
        application = case.loan_application
        note = case.loan_appraisal_note
        review = case.appraisal_review_decision
        facts['maker_checker'] = {
            'application_created_by_user_id': (
                str(application.created_by_user_id)
                if application.created_by_user_id else None
            ),
            'application_received_by_user_id': str(application.received_by_user_id),
            'application_submitted_by_user_id': (
                str(application.submitted_by_user_id)
                if application.submitted_by_user_id else None
            ),
            'appraisal_prepared_by_user_id': str(note.prepared_by_user_id),
            'appraisal_reviewed_by_user_id': (
                str(review.reviewer_user_id)
                if review else (
                    str(note.reviewed_by_user_id) if note.reviewed_by_user_id else None
                )
            ),
        }
        ApprovalCase.objects.filter(pk=case.pk).update(appraisal_facts_json=facts)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_witness'),
        ('approvals', '0011_approvalcase_appraisal_facts_json_and_more'),
        ('identity', '0003_portal_member_auth'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalaction',
            name='approval_action_valid_decision',
        ),
        migrations.AddConstraint(
            model_name='approvalaction',
            constraint=models.CheckConstraint(check=models.Q(('decision__in', ['approved', 'rejected', 'returned', 'abstained'])), name='approval_action_valid_decision'),
        ),
        migrations.AddField(
            model_name='approvalcase',
            name='general_meeting_evidence_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalcase',
            name='conflict_block_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ApprovalConflictDeclaration',
            fields=[
                ('approval_conflict_declaration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('borrower', 'Borrower'), ('director_relative', 'Director relative'), ('material_interest', 'Material interest')], max_length=40)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('declared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_approval_conflicts', to='identity.user')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_conflict_declarations', to='applications.loanapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_conflict_declarations', to='identity.user')),
            ],
            options={
                'db_table': 'approval_conflict_declarations',
                'indexes': [models.Index(fields=['loan_application', 'is_active'], name='idx_conflict_app_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalconflictdeclaration',
            constraint=models.UniqueConstraint(fields=('loan_application', 'user', 'conflict_type'), name='unique_application_user_conflict'),
        ),
        migrations.AddConstraint(
            model_name='approvalconflictdeclaration',
            constraint=models.CheckConstraint(check=models.Q(('conflict_type__in', ['borrower', 'director_relative', 'material_interest'])), name='approval_conflict_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='approvalconflictdeclaration',
            constraint=models.CheckConstraint(check=models.Q(('reason', ''), _negated=True), name='approval_conflict_reason_nonblank'),
        ),
        migrations.RunPython(backfill_cycle_maker_facts, noop_reverse),
    ]
