# Generated by Django 5.0.6 on 2026-07-13 12:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # LoanApplication already exists here. Depending on the current applications
        # leaf would force unrelated witness migrations during historical migration tests.
        ('applications', '0011_witness'),
        ('approvals', '0013_conflict_projection_scope_closure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionRegisterEntry',
            fields=[
                ('exception_register_entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_account_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('exception_type', models.CharField(choices=[('exceeds_loan_limit', 'Exceeds loan limit'), ('stage_bypass', 'Stage bypass'), ('waiver', 'Waiver')], db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('business_reason', models.TextField()),
                ('risk_assessment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=60)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exception_register_entry', to='approvals.approvalcase')),
                ('loan_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exception_register_entries', to='applications.loanapplication')),
            ],
            options={
                'db_table': 'exception_register_entries',
                'ordering': ['-created_at', '-exception_register_entry_id'],
                'indexes': [models.Index(fields=['exception_type', 'status', 'created_at'], name='idx_exception_type_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='exceptionregisterentry',
            constraint=models.CheckConstraint(check=models.Q(('exception_type__in', ['exceeds_loan_limit', 'stage_bypass', 'waiver'])), name='exception_register_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='exceptionregisterentry',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'approved', 'rejected'])), name='exception_register_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='exceptionregisterentry',
            constraint=models.CheckConstraint(check=models.Q(('description__regex', '\\S')), name='exception_register_description_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='exceptionregisterentry',
            constraint=models.CheckConstraint(check=models.Q(('business_reason__regex', '\\S')), name='exception_register_reason_nonblank'),
        ),
    ]
