# Generated by Django 5.0.6 on 2026-07-13 13:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # This migration needs only LoanApplication, already present in the
        # approvals graph. Keeping the dependency at 0011 lets historical
        # applications migration tests roll back independently.
        ('applications', '0011_witness'),
        ('approvals', '0014_exceptionregisterentry_and_more'),
        ('documents', '0001_initial'),
        ('identity', '0003_portal_member_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMeetingApproval',
            fields=[
                ('general_meeting_approval_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_party_type', models.CharField(choices=[('director', 'Director'), ('director_relative', 'Director relative'), ('committee_member', 'Sanction Committee member')], max_length=80)),
                ('relationship_description', models.TextField()),
                ('meeting_date', models.DateField()),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, max_length=60)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_meeting_approvals', to='applications.loanapplication')),
                ('minutes_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_meeting_minutes_records', to='documents.documentfile')),
                ('notice_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_meeting_notice_records', to='documents.documentfile')),
                ('recorded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_general_meeting_approvals', to='identity.user')),
                ('related_party_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_general_meeting_approvals', to='identity.user')),
                ('resolution_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_meeting_resolution_records', to='documents.documentfile')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='approvals.generalmeetingapproval')),
            ],
            options={
                'db_table': 'general_meeting_approvals',
                'ordering': ['-recorded_at', '-general_meeting_approval_id'],
            },
        ),
        migrations.AddField(
            model_name='approvalcase',
            name='general_meeting_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consuming_approval_cases', to='approvals.generalmeetingapproval'),
        ),
        migrations.AddIndex(
            model_name='generalmeetingapproval',
            index=models.Index(fields=['loan_application', 'recorded_at'], name='idx_gm_application_time'),
        ),
        migrations.AddConstraint(
            model_name='generalmeetingapproval',
            constraint=models.CheckConstraint(check=models.Q(('related_party_type__in', ['director', 'director_relative', 'committee_member'])), name='gm_related_party_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='generalmeetingapproval',
            constraint=models.CheckConstraint(check=models.Q(('approval_status__in', ['pending', 'approved', 'rejected'])), name='gm_approval_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='generalmeetingapproval',
            constraint=models.CheckConstraint(check=models.Q(('relationship_description__regex', '\\S')), name='gm_relationship_nonblank'),
        ),
    ]
