// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'; import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import DocumentationHub from './DocumentationHub'; import { fetchStaffApplications } from '../../services/applicationIntakeApi';
import { AuthSessionError } from '../../services/authSession';
import { fetchDocumentationWorkspace, submitDocumentationAction, type DocumentationWorkspace } from '../../services/documentationWorkspaceApi';
import hubSource from './DocumentationHub.tsx?raw'; import checklistSource from '../../components/loan/DocumentChecklist.tsx?raw'; import packSource from '../../components/loan/DocumentPackModal.tsx?raw'; import auditSource from '../../components/loan/AuditTimeline.tsx?raw'; import apiSource from '../../services/documentationWorkspaceApi.ts?raw';
vi.mock('../../services/applicationIntakeApi', () => ({ fetchStaffApplications: vi.fn() })); vi.mock('../../services/documentationWorkspaceApi', async importOriginal => ({ ...await importOriginal<typeof import('../../services/documentationWorkspaceApi')>(), fetchDocumentationWorkspace: vi.fn(), submitDocumentationAction: vi.fn(), downloadStaffDocument: vi.fn(), openStaffDocumentBlob: vi.fn() }));

const approvalAction = { action: 'approve_as_company_secretary', action_url: '/api/v1/document-checklists/checklist-1/approve-as-company-secretary/' };
const item = (code: string, label: string) => ({ checklist_item_id: 'item-' + code, item_code: code, item_label: label, required: true, applicable: true, status: 'pending', blocker: null, stamp_status: null, notarisation_status: null, poa_status: null, document: null, available_actions: [] });
const workspace: DocumentationWorkspace = {
  snapshot_id: 'snapshot-1', loan_application_id: 'application-1', application_reference_number: 'LO000001', borrower_name: 'API Borrower', checklist_status: 'in_progress',
  pack_summary: { status: 'incomplete', available_count: 1, missing_count: 1, pending_review_count: 0 }, blockers: [{ item_code: 'poa', label: 'Power of Attorney', reason: 'notarisation_pending' }],
  items: [{ ...item('term_sheet', 'Term Sheet'), status: 'complete', document: { loan_document_id: 'doc-1', version: '2.0', generation_status: 'generated', execution_status: 'executed', verification_status: 'verified', download: { file_name: 'term-sheet.pdf', mime_type: 'application/pdf', action_url: '/api/v1/loan-applications/application-1/documentation-workspace/term_sheet/download/' } } }, { ...item('poa', 'Power of Attorney'), blocker: 'notarisation_pending', stamp_status: 'adequate', notarisation_status: 'pending', poa_status: 'draft', available_actions: [{ action: 'generate_document', action_url: '/api/v1/loan-applications/application-1/loan-documents/generate/', document_type: 'power_of_attorney', template_id: 'template-1', template_version: '3.0', output_formats: ['pdf', 'docx'] }] }],
  security_workflows: Object.fromEntries([['power_of_attorney', true, 'draft'], ['tri_party_agreement', true, 'pending'], ['sh4', true, 'held_in_custody'], ['cdsl_pledge', false, 'not_required'], ['blank_dated_cheque', true, 'held'], ['cancelled_cheque', true, 'complete']].map(([code, required, status]) => [code, { required, status, available_actions: [] }])) as DocumentationWorkspace['security_workflows'],
  approval_stages: ['company_secretary', 'credit_manager', 'sanction_committee', 'senior_manager_finance'].map((role, index) => ({ role, status: index === 3 ? 'blocked_until_disbursement' : 'pending' })), available_actions: [approvalAction],
}; const renderHub = async () => { render(<DocumentationHub onOpenApplication={vi.fn()} />); await screen.findByText('API Borrower'); };
const approve = async () => { await userEvent.click(screen.getByRole('button', { name: 'Approvals' })); await userEvent.click(screen.getByRole('button', { name: 'Approve as Company Secretary' })); fireEvent.change(screen.getByLabelText('Action comments'), { target: { value: 'All documents verified.' } }); await userEvent.click(screen.getByRole('button', { name: 'Confirm action' })); };
describe('008M documentation workspace wiring', () => {
  beforeEach(() => {
    vi.mocked(fetchStaffApplications).mockResolvedValue({ items: [{ loan_application_id: 'application-1', application_reference_number: 'LO000001', member: { display_name: 'Queue Borrower' } }], pagination: {} } as never);
    vi.mocked(fetchDocumentationWorkspace).mockResolvedValue(workspace); vi.mocked(submitDocumentationAction).mockResolvedValue({ checklist_action_id: 'action-1' });
  });
  afterEach(() => { cleanup(); vi.clearAllMocks(); });
  it('uses one closed server snapshot with no owned mock or composed-request seam', () => { for (const source of [hubSource, checklistSource, packSource, auditSource]) expect(source).not.toContain('data/mockData'); expect(apiSource).not.toContain('Promise.all'); expect(apiSource).not.toContain('/api/v1/document-files/'); expect(apiSource).toContain('/documentation-workspace/'); });
  it('renders blockers, all security workflows, and terminal status beside Download', async () => { await renderHub(); expect(screen.getByText(/Power of Attorney: notarisation pending/i)).toBeTruthy(); expect(screen.getByText('Complete')).toBeTruthy(); expect(screen.getByRole('button', { name: 'Download' })).toBeTruthy(); await userEvent.click(screen.getByRole('button', { name: 'Securities' })); for (const label of ['Power of Attorney', 'Tri-Party Agreement', 'SH-4', 'CDSL Pledge', 'Blank-Dated Cheque', 'Cancelled Cheque']) expect(screen.getByText(label)).toBeTruthy(); });
  it('posts server-owned approval and refetches once without optimism', async () => { await renderHub(); await approve(); await waitFor(() => expect(submitDocumentationAction).toHaveBeenCalledWith(approvalAction, { comments: 'All documents verified.' })); expect(fetchDocumentationWorkspace).toHaveBeenCalledTimes(2); expect(screen.getByRole('button', { name: 'Approve as Company Secretary' })).toBeTruthy(); });
  it('posts the exact server-selected generation option and refetches once', async () => { await renderHub(); await userEvent.click(screen.getByRole('button', { name: 'Generate document' })); expect(submitDocumentationAction).toHaveBeenCalledWith(workspace.items[1].available_actions[0], { document_type: 'power_of_attorney', template_id: 'template-1', output_format: 'pdf' }); expect(fetchDocumentationWorkspace).toHaveBeenCalledTimes(2); });
  it('renders a server-restricted item without content or mutation controls', async () => { vi.mocked(fetchDocumentationWorkspace).mockResolvedValueOnce({ ...workspace, items: [{ ...workspace.items[0], document: { ...workspace.items[0].document!, download: null }, available_actions: [] }] }); await renderHub(); expect(screen.getByText('Restricted or no action available')).toBeTruthy(); expect(screen.queryByRole('button', { name: 'Download' })).toBeNull(); expect(screen.queryByRole('button', { name: 'Generate document' })).toBeNull(); });
  it('keeps a conflict visible with no optimistic change, retry, or refetch', async () => { vi.mocked(submitDocumentationAction).mockRejectedValueOnce(new AuthSessionError('CHECKLIST_APPROVAL_OUT_OF_ORDER', 'Approval facts changed.', 409)); await renderHub(); await approve(); expect(await screen.findByText('Approval facts changed.')).toBeTruthy(); expect(submitDocumentationAction).toHaveBeenCalledTimes(1); expect(fetchDocumentationWorkspace).toHaveBeenCalledTimes(1); expect(screen.getByRole('button', { name: 'Approve as Company Secretary' })).toBeTruthy(); });
});
