# Generated by Django 5.0.6 on 2026-07-10 14:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def repair_provenance_and_backfill_latest_review(apps, schema_editor):
    Appraisal = apps.get_model("credit", "LoanAppraisalNote")
    Eligibility = apps.get_model("credit", "EligibilityAssessment")
    LoanLimit = apps.get_model("credit", "LoanLimitAssessment")
    Decision = apps.get_model("credit", "AppraisalReviewDecision")
    AuditLog = apps.get_model("identity", "AuditLog")

    for appraisal in Appraisal.objects.all().iterator():
        if appraisal.prerequisite_provenance == "verified":
            eligibility = Eligibility.objects.filter(
                pk=appraisal.eligibility_assessment_id_snapshot,
                loan_application_id=appraisal.loan_application_id,
            ).first()
            loan_limit = LoanLimit.objects.filter(
                pk=appraisal.loan_limit_assessment_id_snapshot,
                loan_application_id=appraisal.loan_application_id,
            ).first()
            proven = eligibility is not None and loan_limit is not None
            if proven:
                source_times_are_safe = (
                    eligibility.assessed_at <= appraisal.prepared_at
                    and loan_limit.calculated_at <= appraisal.prepared_at
                )
                eligibility_audits = AuditLog.objects.filter(
                    action="eligibility.assessed",
                    entity_type="eligibility_assessment",
                    entity_id=eligibility.pk,
                )
                loan_limit_audits = AuditLog.objects.filter(
                    action="loan_limit.calculated",
                    entity_type="loan_limit_assessment",
                    entity_id=loan_limit.pk,
                )
                positive_audits_exist = (
                    eligibility_audits.filter(
                        created_at__lte=appraisal.prepared_at
                    ).exists()
                    and loan_limit_audits.filter(
                        created_at__lte=appraisal.prepared_at
                    ).exists()
                )
                no_later_success = not (
                    eligibility_audits.filter(
                        created_at__gt=appraisal.prepared_at
                    ).exists()
                    or loan_limit_audits.filter(
                        created_at__gt=appraisal.prepared_at
                    ).exists()
                )
                proven = (
                    source_times_are_safe
                    and positive_audits_exist
                    and no_later_success
                )
            if not proven:
                appraisal.prerequisite_provenance = "legacy_unverified"
                appraisal.save(update_fields=["prerequisite_provenance"])

        expected_to_state = {
            "reviewed": "reviewed",
            "returned": "draft",
            "rejected": "rejected",
        }.get(appraisal.last_review_decision)
        if (
            expected_to_state is not None
            and appraisal.appraisal_status == expected_to_state
            and appraisal.review_comments.strip()
            and appraisal.reviewed_by_user_id is not None
            and appraisal.reviewed_at is not None
        ):
            Decision.objects.create(
                loan_appraisal_note_id=appraisal.pk,
                decision=appraisal.last_review_decision,
                review_comments=appraisal.review_comments,
                reviewer_user_id=appraisal.reviewed_by_user_id,
                decided_at=appraisal.reviewed_at,
                from_state="review_pending",
                to_state=expected_to_state,
                history_provenance="legacy_latest_only",
            )


def preserve_conservative_provenance_on_reverse(apps, schema_editor):
    # Relabelling unproven rows as verified would recreate the historical defect.
    # The reverse schema operation drops the derived latest-only history table.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_appraisal_review_facts'),
        ('identity', '0003_portal_member_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalReviewDecision',
            fields=[
                ('appraisal_review_decision_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=60)),
                ('review_comments', models.TextField()),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_state', models.CharField(max_length=60)),
                ('to_state', models.CharField(max_length=60)),
                ('history_provenance', models.CharField(default='native', max_length=60)),
                ('loan_appraisal_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='credit.loanappraisalnote')),
                ('reviewer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisal_review_decisions', to='identity.user')),
            ],
            options={
                'db_table': 'appraisal_review_decisions',
                'ordering': ['decided_at', 'appraisal_review_decision_id'],
                'indexes': [models.Index(fields=['loan_appraisal_note', 'decided_at'], name='idx_appraisal_review_time')],
            },
        ),
        migrations.RunPython(
            repair_provenance_and_backfill_latest_review,
            preserve_conservative_provenance_on_reverse,
        ),
    ]
