# Generated by Django 5.0.6 on 2026-07-17 01:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0017_bank_decision_terminal_sanction_snapshots'),
        ('communications', '0003_notification'),
        ('identity', '0003_portal_member_auth'),
        ('loans', '0001_initial'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
        ('workflows', '0001_canonical_workflow_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('disbursement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disbursement_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('initiation_status', models.CharField(db_index=True, default='initiated', max_length=60)),
                ('authorisation_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('bank_transfer_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('payment_method', models.CharField(default='manual', max_length=40)),
                ('final_verification_comments', models.TextField()),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('payload_digest', models.CharField(max_length=64)),
                ('readiness_digest', models.CharField(max_length=64)),
                ('readiness_evidence_json', models.JSONField()),
                ('maker_role_code', models.CharField(max_length=80)),
                ('maker_team_codes_json', models.JSONField(default=list)),
                ('initiated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bank_reference_number', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('loan_register_updated_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorised_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorised_disbursements', to='identity.user')),
                ('borrower_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_disbursements', to='members.bankaccount')),
                ('cfc_task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_initiation', to='communications.notification')),
                ('disbursement_advice_communication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advised_disbursements', to='communications.communication')),
                ('initiated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_disbursements', to='identity.user')),
                ('initiation_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_initiation', to='identity.auditlog')),
                ('initiation_workflow_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_initiation', to='workflows.workflowevent')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='loans.loanaccount')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='applications.loanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='members.member')),
                ('source_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_disbursements', to='members.bankaccount')),
            ],
            options={
                'db_table': 'disbursements',
                'indexes': [models.Index(fields=['loan_account', 'initiation_status'], name='idx_disb_account_status'), models.Index(fields=['authorisation_status', 'created_at'], name='idx_disb_auth_created')],
            },
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(check=models.Q(('disbursement_amount__gt', 0)), name='disb_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(check=models.Q(('initiation_status__in', ('pending', 'initiated'))), name='disb_init_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(check=models.Q(('authorisation_status__in', ('pending', 'approved', 'rejected'))), name='disb_auth_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(check=models.Q(('bank_transfer_status__in', ('pending', 'processing', 'successful', 'failed', 'reversed'))), name='disb_transfer_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(check=models.Q(('payment_method', 'manual')), name='disb_method_manual'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(check=models.Q(('authorised_by_user__isnull', True), models.Q(('authorised_by_user', models.F('initiated_by_user')), _negated=True), _connector='OR'), name='disb_maker_checker_distinct'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.UniqueConstraint(condition=models.Q(('authorisation_status__in', ('pending', 'approved')), ('bank_transfer_status__in', ('pending', 'processing'))), fields=('loan_account',), name='uniq_active_disb_account'),
        ),
    ]
