# Generated by Django 5.0.6 on 2026-07-17 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0017_bank_decision_terminal_sanction_snapshots"),
        ("communications", "0003_notification"),
        ("disbursements", "0001_initial"),
        ("identity", "0003_portal_member_auth"),
        ("loans", "0001_initial"),
        (
            "members",
            "0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more",
        ),
        ("workflows", "0001_canonical_workflow_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="disbursement",
            name="authorisation_action_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="authorisation_audit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disbursement_authorisation",
                to="identity.auditlog",
            ),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="authorisation_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="authorisation_evidence_digest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="authorisation_ip_address",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="authorisation_request_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="authorisation_user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="authorisation_workflow_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disbursement_authorisation",
                to="workflows.workflowevent",
            ),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="authorised_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="checker_role_code",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="checker_team_codes_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="disbursement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("authorisation_action_id__isnull", True),
                        ("authorisation_audit__isnull", True),
                        ("authorisation_status", "pending"),
                        ("authorisation_workflow_event__isnull", True),
                        ("authorised_at__isnull", True),
                        ("authorised_by_user__isnull", True),
                    ),
                    models.Q(
                        ("authorisation_action_id__isnull", False),
                        ("authorisation_audit__isnull", False),
                        ("authorisation_status__in", ("approved", "rejected")),
                        ("authorisation_workflow_event__isnull", False),
                        ("authorised_at__isnull", False),
                        ("authorised_by_user__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="disb_auth_terminal_evidence",
            ),
        ),
    ]
