# Generated by Django 5.0.6 on 2026-07-17 08:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_bank_decision_terminal_sanction_snapshots'),
        ('communications', '0003_notification'),
        ('disbursements', '0003_authorisation_aggregate_integrity'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0003_portal_member_auth'),
        ('loans', '0001_initial'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
        ('workflows', '0001_canonical_workflow_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('bank_transfer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_type', models.CharField(default='disbursement', max_length=60)),
                ('related_entity_type', models.CharField(default='disbursement', max_length=80)),
                ('related_entity_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_method', models.CharField(default='manual', max_length=60)),
                ('bank_reference_number', models.CharField(max_length=120)),
                ('bank_reference_number_normalized', models.CharField(max_length=120, unique=True)),
                ('bank_status', models.CharField(db_index=True, default='successful', max_length=60)),
                ('initiated_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bank_transfers',
            },
        ),
        migrations.AddField(
            model_name='disbursement',
            name='bank_transfer_evidence_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidenced_disbursements', to='documents.documentfile'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_action_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successful_disbursement_transfers', to='identity.user'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_audit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_transfer_success', to='identity.auditlog'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_evidence_digest',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_idempotency_key_digest',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_ip_address',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_loan_status_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_transfer_success', to='loans.loanstatushistory'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_payload_digest',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_role_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_team_codes_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transfer_success_workflow_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_transfer_success', to='workflows.workflowevent'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('authorisation_status', 'approved'), ('bank_reference_number__isnull', False), ('bank_transfer_evidence_document__isnull', False), ('bank_transfer_status', 'successful'), ('disbursed_at__isnull', False), ('transfer_success_action_id__isnull', False), ('transfer_success_actor_user__isnull', False), ('transfer_success_audit__isnull', False), ('transfer_success_evidence_digest__isnull', False), ('transfer_success_idempotency_key_digest__isnull', False), ('transfer_success_ip_address__isnull', False), ('transfer_success_loan_status_history__isnull', False), ('transfer_success_payload_digest__isnull', False), ('transfer_success_request_id__isnull', False), ('transfer_success_role_code__isnull', False), ('transfer_success_team_codes_json__isnull', False), ('transfer_success_user_agent__isnull', False), ('transfer_success_workflow_event__isnull', False)), models.Q(('bank_transfer_evidence_document__isnull', True), ('bank_transfer_status__in', ('pending', 'processing', 'failed', 'reversed')), ('transfer_success_action_id__isnull', True), ('transfer_success_actor_user__isnull', True), ('transfer_success_audit__isnull', True), ('transfer_success_evidence_digest__isnull', True), ('transfer_success_idempotency_key_digest__isnull', True), ('transfer_success_ip_address__isnull', True), ('transfer_success_loan_status_history__isnull', True), ('transfer_success_payload_digest__isnull', True), ('transfer_success_request_id__isnull', True), ('transfer_success_role_code__isnull', True), ('transfer_success_team_codes_json__isnull', True), ('transfer_success_user_agent__isnull', True), ('transfer_success_workflow_event__isnull', True)), _connector='OR'), name='disb_success_evidence_complete'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bank_transfer_status', 'pending'), _negated=True), models.Q(('bank_reference_number__isnull', True), ('bank_transfer_evidence_document__isnull', True), ('disbursed_at__isnull', True)), _connector='OR'), name='disb_pending_has_no_transfer'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='destination_bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_bank_transfers', to='members.bankaccount'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='disbursement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfer', to='disbursements.disbursement'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='evidence_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidenced_bank_transfers', to='documents.documentfile'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='loan_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='successful_bank_transfer', to='loans.loanaccount'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='source_bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_bank_transfers', to='members.bankaccount'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['transfer_type', 'related_entity_id'], name='idx_bank_transfer_related'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['bank_status', 'completed_at'], name='idx_bank_transfer_status'),
        ),
        migrations.AddConstraint(
            model_name='banktransfer',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='bank_transfer_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='banktransfer',
            constraint=models.CheckConstraint(check=models.Q(('bank_status', 'successful'), ('payment_method', 'manual'), ('related_entity_type', 'disbursement'), ('transfer_type', 'disbursement')), name='bank_transfer_manual_success'),
        ),
        migrations.AddConstraint(
            model_name='banktransfer',
            constraint=models.CheckConstraint(check=models.Q(('completed_at__gte', models.F('initiated_at'))), name='bank_transfer_time_order'),
        ),
        migrations.AddConstraint(
            model_name='banktransfer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bank_reference_number', ''), _negated=True), models.Q(('bank_reference_number_normalized', ''), _negated=True)), name='bank_transfer_reference_present'),
        ),
    ]
