# Generated by Django 5.0.6 on 2026-07-17 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class RemoveLegalChecklistConstraint(Operation):
    reduces_to_sql = True
    reversible = True

    def __init__(self, name):
        self.name = name

    def state_forwards(self, app_label, state):
        model_state = state.models[("legal_documents", "documentchecklist")]
        model_state.options["constraints"] = [
            constraint
            for constraint in model_state.options.get("constraints", [])
            if constraint.name != self.name
        ]
        state.reload_model("legal_documents", "documentchecklist", delay=True)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        old_model = from_state.apps.get_model("legal_documents", "DocumentChecklist")
        model = to_state.apps.get_model("legal_documents", "DocumentChecklist")
        constraint = next(
            item for item in old_model._meta.constraints if item.name == self.name
        )
        schema_editor.remove_constraint(model, constraint)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model("legal_documents", "DocumentChecklist")
        constraint = next(
            item for item in model._meta.constraints if item.name == self.name
        )
        schema_editor.add_constraint(model, constraint)

    def describe(self):
        return f"Remove legal checklist constraint {self.name}"


class AddLegalChecklistConstraint(Operation):
    reduces_to_sql = True
    reversible = True

    def __init__(self, constraint):
        self.constraint = constraint

    def state_forwards(self, app_label, state):
        model_state = state.models[("legal_documents", "documentchecklist")]
        model_state.options.setdefault("constraints", []).append(self.constraint)
        state.reload_model("legal_documents", "documentchecklist", delay=True)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model("legal_documents", "DocumentChecklist")
        schema_editor.add_constraint(model, self.constraint)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model("legal_documents", "DocumentChecklist")
        schema_editor.remove_constraint(model, self.constraint)

    def describe(self):
        return f"Add legal checklist constraint {self.constraint.name}"


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_bank_decision_terminal_sanction_snapshots'),
        ('communications', '0003_notification'),
        ('disbursements', '0004_transfer_success'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0003_portal_member_auth'),
        ('legal_documents', '0014_staff_documentation_durable_actions'),
        ('loans', '0001_initial'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
        ('workflows', '0001_canonical_workflow_event'),
    ]

    operations = [
        RemoveLegalChecklistConstraint("checklist_account_requires_epic_009"),
        RemoveLegalChecklistConstraint("checklist_finance_requires_epic_009"),
        AddLegalChecklistConstraint(
            models.CheckConstraint(
                check=models.Q(
                    ("senior_manager_finance_signature_id__isnull", True),
                    ("sanction_committee_signature_id__isnull", False),
                    _connector="OR",
                ),
                name="checklist_finance_requires_sanction",
            )
        ),
        AddLegalChecklistConstraint(
            models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("checklist_status", "ready"),
                        ("loan_account_id__isnull", False),
                        ("senior_manager_finance_signature_id__isnull", False),
                    ),
                    models.Q(
                        models.Q(("checklist_status", "ready"), _negated=True),
                        ("loan_account_id__isnull", True),
                        ("senior_manager_finance_signature_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="checklist_ready_evidence_complete",
            )
        ),
        migrations.CreateModel(
            name='DisbursementAdviceIntent',
            fields=[
                ('advice_intent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bank_reference_digest', models.CharField(max_length=64)),
                ('evidence_checksum_sha256', models.CharField(max_length=128)),
                ('transfer_action_id', models.UUIDField(unique=True)),
                ('transfer_evidence_digest', models.CharField(max_length=64)),
                ('delivery_status', models.CharField(default='pending', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'disbursement_advice_intents',
            },
        ),
        migrations.CreateModel(
            name='LoanRegisterUpdate',
            fields=[
                ('loan_register_update_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bank_reference_digest', models.CharField(max_length=64)),
                ('evidence_checksum_sha256', models.CharField(max_length=128)),
                ('transfer_action_id', models.UUIDField(unique=True)),
                ('transfer_evidence_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'loan_register_updates',
            },
        ),
        migrations.RemoveConstraint(
            model_name='disbursement',
            name='disb_success_evidence_complete',
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('authorisation_status', 'approved'), ('bank_reference_number__isnull', False), ('bank_transfer_evidence_document__isnull', False), ('bank_transfer_status', 'successful'), ('disbursed_at__isnull', False), ('loan_register_updated_flag', True), ('transfer_success_action_id__isnull', False), ('transfer_success_actor_user__isnull', False), ('transfer_success_audit__isnull', False), ('transfer_success_evidence_digest__isnull', False), ('transfer_success_idempotency_key_digest__isnull', False), ('transfer_success_ip_address__isnull', False), ('transfer_success_loan_status_history__isnull', False), ('transfer_success_payload_digest__isnull', False), ('transfer_success_request_id__isnull', False), ('transfer_success_role_code__isnull', False), ('transfer_success_team_codes_json__isnull', False), ('transfer_success_user_agent__isnull', False), ('transfer_success_workflow_event__isnull', False)), models.Q(('bank_transfer_evidence_document__isnull', True), ('bank_transfer_status__in', ('pending', 'processing', 'failed', 'reversed')), ('loan_register_updated_flag', False), ('transfer_success_action_id__isnull', True), ('transfer_success_actor_user__isnull', True), ('transfer_success_audit__isnull', True), ('transfer_success_evidence_digest__isnull', True), ('transfer_success_idempotency_key_digest__isnull', True), ('transfer_success_ip_address__isnull', True), ('transfer_success_loan_status_history__isnull', True), ('transfer_success_payload_digest__isnull', True), ('transfer_success_request_id__isnull', True), ('transfer_success_role_code__isnull', True), ('transfer_success_team_codes_json__isnull', True), ('transfer_success_user_agent__isnull', True), ('transfer_success_workflow_event__isnull', True)), _connector='OR'), name='disb_success_evidence_complete'),
        ),
        migrations.AddField(
            model_name='disbursementadviceintent',
            name='bank_transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='advice_intent', to='disbursements.banktransfer'),
        ),
        migrations.AddField(
            model_name='disbursementadviceintent',
            name='disbursement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='advice_intent', to='disbursements.disbursement'),
        ),
        migrations.AddField(
            model_name='disbursementadviceintent',
            name='evidence_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_advice_intents', to='documents.documentfile'),
        ),
        migrations.AddField(
            model_name='disbursementadviceintent',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_advice_intents', to='loans.loanaccount'),
        ),
        migrations.AddField(
            model_name='disbursementadviceintent',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_advice_intents', to='applications.loanapplication'),
        ),
        migrations.AddField(
            model_name='disbursementadviceintent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_advice_intents', to='members.member'),
        ),
        migrations.AddField(
            model_name='disbursementadviceintent',
            name='transfer_audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_advice_intents', to='identity.auditlog'),
        ),
        migrations.AddField(
            model_name='disbursementadviceintent',
            name='transfer_workflow_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_advice_intents', to='workflows.workflowevent'),
        ),
        migrations.AddField(
            model_name='loanregisterupdate',
            name='bank_transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_register_update', to='disbursements.banktransfer'),
        ),
        migrations.AddField(
            model_name='loanregisterupdate',
            name='disbursement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_register_update', to='disbursements.disbursement'),
        ),
        migrations.AddField(
            model_name='loanregisterupdate',
            name='evidence_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_register_updates', to='documents.documentfile'),
        ),
        migrations.AddField(
            model_name='loanregisterupdate',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_register_updates', to='loans.loanaccount'),
        ),
        migrations.AddField(
            model_name='loanregisterupdate',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_register_updates', to='applications.loanapplication'),
        ),
        migrations.AddField(
            model_name='loanregisterupdate',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_register_updates', to='members.member'),
        ),
        migrations.AddField(
            model_name='loanregisterupdate',
            name='transfer_audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_register_updates', to='identity.auditlog'),
        ),
        migrations.AddField(
            model_name='loanregisterupdate',
            name='transfer_workflow_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_register_updates', to='workflows.workflowevent'),
        ),
        migrations.AddConstraint(
            model_name='disbursementadviceintent',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='advice_intent_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='disbursementadviceintent',
            constraint=models.CheckConstraint(check=models.Q(('delivery_status__in', ('pending', 'sent'))), name='advice_intent_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='disbursementadviceintent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bank_reference_digest', ''), _negated=True), models.Q(('evidence_checksum_sha256', ''), _negated=True)), name='advice_intent_evidence_present'),
        ),
        migrations.AddConstraint(
            model_name='loanregisterupdate',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='loan_register_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanregisterupdate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bank_reference_digest', ''), _negated=True), models.Q(('evidence_checksum_sha256', ''), _negated=True)), name='loan_register_evidence_present'),
        ),
    ]
