# Generated by Django 5.0.6 on 2026-07-17 15:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0017_bank_decision_terminal_sanction_snapshots"),
        ("disbursements", "0005_disbursementadviceintent_loanregisterupdate_and_more"),
        ("documents", "0005_deterministic_document_template_constraints"),
        ("identity", "0003_portal_member_auth"),
        ("loans", "0001_initial"),
        (
            "members",
            "0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more",
        ),
        ("workflows", "0001_canonical_workflow_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisbursementAdviceDeliveryReceipt",
            fields=[
                (
                    "delivery_receipt_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("payload_digest", models.CharField(max_length=64)),
                (
                    "external_message_id",
                    models.CharField(max_length=120, unique=True),
                ),
                ("delivery_status", models.CharField(max_length=40)),
                ("accepted_at", models.DateTimeField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={"db_table": "disbursement_advice_delivery_receipts"},
        ),
        migrations.AddField(
            model_name="disbursementadviceintent",
            name="delivery_action_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="disbursementadviceintent",
            name="delivery_audit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivered_disbursement_advice_intents",
                to="identity.auditlog",
            ),
        ),
        migrations.AddField(
            model_name="disbursementadviceintent",
            name="delivery_evidence_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="disbursementadviceintent",
            name="delivery_workflow_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivered_disbursement_advice_intents",
                to="workflows.workflowevent",
            ),
        ),
        migrations.AddConstraint(
            model_name="disbursementadviceintent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("delivery_action_id__isnull", True),
                        ("delivery_audit__isnull", True),
                        ("delivery_evidence_digest", ""),
                        ("delivery_status", "pending"),
                        ("delivery_workflow_event__isnull", True),
                    ),
                    models.Q(
                        ("delivery_action_id__isnull", False),
                        ("delivery_audit__isnull", False),
                        ("delivery_status", "sent"),
                        ("delivery_workflow_event__isnull", False),
                        models.Q(("delivery_evidence_digest", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="advice_intent_delivery_evidence_complete",
            ),
        ),
        migrations.AddField(
            model_name="disbursementadvicedeliveryreceipt",
            name="advice_intent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_receipt",
                to="disbursements.disbursementadviceintent",
            ),
        ),
        migrations.AddConstraint(
            model_name="disbursementadvicedeliveryreceipt",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("idempotency_key", ""), _negated=True),
                    models.Q(("payload_digest", ""), _negated=True),
                    models.Q(("external_message_id", ""), _negated=True),
                    ("delivery_status", "sent"),
                ),
                name="advice_delivery_receipt_complete",
            ),
        ),
    ]
