# Generated by Django 5.0.6 on 2026-07-17 16:39

import hashlib

import django.db.models.deletion
from django.db import migrations, models


def link_coherent_register_updates(apps, schema_editor):
    Disbursement = apps.get_model("disbursements", "Disbursement")
    BankTransfer = apps.get_model("disbursements", "BankTransfer")
    AdviceIntent = apps.get_model("disbursements", "DisbursementAdviceIntent")
    RegisterUpdate = apps.get_model("disbursements", "LoanRegisterUpdate")
    DocumentFile = apps.get_model("documents", "DocumentFile")

    if RegisterUpdate.objects.exclude(
        disbursement__bank_transfer_status="successful"
    ).exists():
        raise RuntimeError(
            "Cannot link Loan Register evidence to a non-successful disbursement."
        )

    for row in Disbursement.objects.filter(
        bank_transfer_status="successful"
    ).iterator():
        registers = list(
            RegisterUpdate.objects.filter(disbursement_id=row.pk)[:2]
        )
        transfers = list(BankTransfer.objects.filter(disbursement_id=row.pk)[:2])
        intents = list(AdviceIntent.objects.filter(disbursement_id=row.pk)[:2])
        if len(registers) != 1 or len(transfers) != 1 or len(intents) != 1:
            raise RuntimeError(
                "Cannot link ambiguous or incomplete successful disbursement evidence."
            )

        register = registers[0]
        transfer = transfers[0]
        intent = intents[0]
        document = DocumentFile.objects.filter(
            pk=row.bank_transfer_evidence_document_id
        ).first()
        reference_digest = hashlib.sha256(
            transfer.bank_reference_number_normalized.encode("utf-8")
        ).hexdigest()
        coherent = bool(
            row.loan_register_updated_flag
            and document is not None
            and transfer.loan_account_id == row.loan_account_id
            and transfer.related_entity_id == row.pk
            and transfer.evidence_document_id
            == row.bank_transfer_evidence_document_id
            and transfer.amount == row.disbursement_amount
            and transfer.bank_reference_number_normalized
            == row.bank_reference_number
            and register.bank_transfer_id == transfer.pk
            and register.loan_account_id == row.loan_account_id
            and register.loan_application_id == row.loan_application_id
            and register.member_id == row.member_id
            and register.amount == row.disbursement_amount
            and register.bank_reference_digest == reference_digest
            and register.evidence_document_id
            == row.bank_transfer_evidence_document_id
            and register.evidence_checksum_sha256 == document.checksum_sha256
            and register.transfer_action_id == row.transfer_success_action_id
            and register.transfer_evidence_digest
            == row.transfer_success_evidence_digest
            and register.transfer_audit_id == row.transfer_success_audit_id
            and register.transfer_workflow_event_id
            == row.transfer_success_workflow_event_id
            and intent.bank_transfer_id == transfer.pk
            and intent.loan_account_id == row.loan_account_id
            and intent.loan_application_id == row.loan_application_id
            and intent.member_id == row.member_id
            and intent.amount == row.disbursement_amount
            and intent.bank_reference_digest == reference_digest
            and intent.evidence_document_id == row.bank_transfer_evidence_document_id
            and intent.evidence_checksum_sha256 == document.checksum_sha256
            and intent.transfer_action_id == row.transfer_success_action_id
            and intent.transfer_evidence_digest == row.transfer_success_evidence_digest
            and intent.transfer_audit_id == row.transfer_success_audit_id
            and intent.transfer_workflow_event_id
            == row.transfer_success_workflow_event_id
        )
        if not coherent:
            raise RuntimeError(
                "Cannot link incoherent successful disbursement evidence."
            )
        Disbursement.objects.filter(pk=row.pk).update(register_update_id=register.pk)


def unlink_register_updates(apps, schema_editor):
    Disbursement = apps.get_model("disbursements", "Disbursement")
    Disbursement.objects.update(register_update_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_bank_decision_terminal_sanction_snapshots'),
        ('communications', '0003_notification'),
        ('disbursements', '0006_disbursementadvicedeliveryreceipt_and_more'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0003_portal_member_auth'),
        ('loans', '0001_initial'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
        ('workflows', '0001_canonical_workflow_event'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='disbursement',
            name='disb_success_evidence_complete',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='register_update',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_by_successful_disbursement', to='disbursements.loanregisterupdate'),
        ),
        migrations.RunPython(link_coherent_register_updates, unlink_register_updates),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('authorisation_status', 'approved'), ('bank_reference_number__isnull', False), ('bank_transfer_evidence_document__isnull', False), ('bank_transfer_status', 'successful'), ('disbursed_at__isnull', False), ('loan_register_updated_flag', True), ('register_update__isnull', False), ('transfer_success_action_id__isnull', False), ('transfer_success_actor_user__isnull', False), ('transfer_success_audit__isnull', False), ('transfer_success_evidence_digest__isnull', False), ('transfer_success_idempotency_key_digest__isnull', False), ('transfer_success_ip_address__isnull', False), ('transfer_success_loan_status_history__isnull', False), ('transfer_success_payload_digest__isnull', False), ('transfer_success_request_id__isnull', False), ('transfer_success_role_code__isnull', False), ('transfer_success_team_codes_json__isnull', False), ('transfer_success_user_agent__isnull', False), ('transfer_success_workflow_event__isnull', False)), models.Q(('bank_transfer_evidence_document__isnull', True), ('bank_transfer_status__in', ('pending', 'processing', 'failed', 'reversed')), ('loan_register_updated_flag', False), ('register_update__isnull', True), ('transfer_success_action_id__isnull', True), ('transfer_success_actor_user__isnull', True), ('transfer_success_audit__isnull', True), ('transfer_success_evidence_digest__isnull', True), ('transfer_success_idempotency_key_digest__isnull', True), ('transfer_success_ip_address__isnull', True), ('transfer_success_loan_status_history__isnull', True), ('transfer_success_payload_digest__isnull', True), ('transfer_success_request_id__isnull', True), ('transfer_success_role_code__isnull', True), ('transfer_success_team_codes_json__isnull', True), ('transfer_success_user_agent__isnull', True), ('transfer_success_workflow_event__isnull', True)), _connector='OR'), name='disb_success_evidence_complete'),
        ),
    ]
