# Generated by Django 5.0.6 on 2026-07-19 01:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_bank_decision_terminal_sanction_snapshots'),
        ('disbursements', '0007_remove_disbursement_disb_success_evidence_complete_and_more'),
        ('loans', '0001_initial'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialLoanPaymentSapPosting',
            fields=[
                ('initial_loan_payment_sap_posting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transfer_action_id', models.UUIDField(unique=True)),
                ('transfer_evidence_digest', models.CharField(max_length=64)),
                ('posting_status', models.CharField(db_index=True, default='pending', max_length=40)),
                ('sap_posting_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank_transfer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='initial_payment_sap_posting', to='disbursements.banktransfer')),
                ('disbursement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='initial_payment_sap_posting', to='disbursements.disbursement')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initial_payment_sap_postings', to='loans.loanaccount')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initial_payment_sap_postings', to='applications.loanapplication')),
                ('loan_register_update', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='initial_payment_sap_posting', to='disbursements.loanregisterupdate')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initial_payment_sap_postings', to='members.member')),
            ],
            options={
                'db_table': 'initial_loan_payment_sap_postings',
                'indexes': [models.Index(fields=['posting_status', 'created_at'], name='idx_initial_sap_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='initialloanpaymentsapposting',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='initial_sap_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='initialloanpaymentsapposting',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('posted_at__isnull', True), ('posting_status', 'pending'), ('sap_posting_reference__isnull', True)), models.Q(('posted_at__isnull', False), ('posting_status', 'posted'), ('sap_posting_reference__isnull', False)), _connector='OR'), name='initial_sap_posting_lifecycle'),
        ),
        migrations.AddConstraint(
            model_name='initialloanpaymentsapposting',
            constraint=models.CheckConstraint(check=models.Q(('transfer_evidence_digest', ''), _negated=True), name='initial_sap_evidence_present'),
        ),
    ]
