# Generated by Django 5.0.6 on 2026-07-16 00:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0017_bank_decision_terminal_sanction_snapshots'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0003_portal_member_auth'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapCustomerProfileRequest',
            fields=[
                ('sap_customer_profile_request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_status', models.CharField(db_index=True, default='draft', max_length=60)),
                ('farmer_full_name', models.CharField(max_length=255)),
                ('borrower_type', models.CharField(max_length=60)),
                ('folio_number', models.CharField(max_length=100)),
                ('aadhaar_number_encrypted', models.TextField(blank=True)),
                ('pan_number_encrypted', models.TextField()),
                ('address_text', models.TextField()),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('loan_application_number', models.CharField(max_length=40)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('sanction_date', models.DateField()),
                ('bank_account_last4', models.CharField(blank=True, max_length=4)),
                ('ifsc', models.CharField(blank=True, max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_sap_profiles', to='identity.user')),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_customer_profile_requests', to='documents.documentfile')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_customer_profile_requests', to='applications.loanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_customer_profile_requests', to='members.member')),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_sap_profiles', to='identity.user')),
            ],
            options={
                'db_table': 'sap_customer_profile_requests',
            },
        ),
        migrations.CreateModel(
            name='SapCustomerCode',
            fields=[
                ('sap_customer_code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sap_customer_code', models.CharField(max_length=120, unique=True)),
                ('sap_vendor_code', models.CharField(blank=True, max_length=120)),
                ('created_at_sap', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=40)),
                ('confirmation_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_sap_customer_codes', to='documents.documentfile')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sap_customer_codes', to='identity.user')),
                ('created_for_loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sap_customer_codes', to='applications.loanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sap_customer_codes', to='members.member')),
            ],
            options={
                'db_table': 'sap_customer_codes',
                'indexes': [models.Index(fields=['member', 'status'], name='idx_sap_code_member_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='sapcustomercode',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('member',), name='uniq_active_sap_code_member'),
        ),
        migrations.AddConstraint(
            model_name='sapcustomercode',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('active', 'inactive'))), name='sap_customer_code_status_valid'),
        ),
        migrations.AddIndex(
            model_name='sapcustomerprofilerequest',
            index=models.Index(fields=['loan_application'], name='idx_sap_req_application'),
        ),
        migrations.AddIndex(
            model_name='sapcustomerprofilerequest',
            index=models.Index(fields=['member'], name='idx_sap_req_member'),
        ),
        migrations.AddIndex(
            model_name='sapcustomerprofilerequest',
            index=models.Index(fields=['assigned_to_user', 'request_status'], name='idx_sap_req_assignee_status'),
        ),
        migrations.AddConstraint(
            model_name='sapcustomerprofilerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_status__in', ('draft', 'sent'))), fields=('loan_application',), name='uniq_active_sap_request_app'),
        ),
        migrations.AddConstraint(
            model_name='sapcustomerprofilerequest',
            constraint=models.CheckConstraint(check=models.Q(('request_status__in', ('draft', 'sent', 'completed'))), name='sap_request_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='sapcustomerprofilerequest',
            constraint=models.CheckConstraint(check=models.Q(('sanctioned_amount__gt', 0)), name='sap_request_amount_positive'),
        ),
    ]
