# Generated by Django 5.0.6 on 2026-07-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_sap_customer_code_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapcustomerprofilerequest',
            name='completion_input_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sapcustomerprofilerequest',
            name='delivery_assignee_id_snapshot',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sapcustomerprofilerequest',
            name='delivery_capability_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sapcustomerprofilerequest',
            name='delivery_capability_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sapcustomerprofilerequest',
            name='delivery_capability_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sapcustomerprofilerequest',
            name='delivery_checksum_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sapcustomerprofilerequest',
            name='delivery_file_id_snapshot',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sapcustomerprofilerequest',
            name='delivery_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
