# Generated by Django 5.0.6 on 2026-07-22 13:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('loans', '0009_dpd_pointer_integrity'),
        ('members', '0015_member_aadhaar_last4'),
        ('workflows', '0001_canonical_workflow_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanClosure',
            fields=[
                ('loan_closure_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closure_type', models.CharField(db_index=True, max_length=80)),
                ('closure_stage', models.CharField(db_index=True, max_length=80)),
                ('closure_notes', models.TextField()),
                ('principal_paid_flag', models.BooleanField()),
                ('interest_paid_flag', models.BooleanField()),
                ('charges_paid_flag', models.BooleanField()),
                ('total_outstanding_at_closure', models.DecimalField(decimal_places=2, max_digits=18)),
                ('readiness_snapshot_json', models.JSONField()),
                ('closed_by_role_code', models.CharField(max_length=100)),
                ('closed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('payload_digest', models.CharField(max_length=64)),
                ('close_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_closure', to='identity.auditlog')),
                ('closed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_loans', to='identity.user')),
                ('loan_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_closure', to='loans.loanaccount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_closures', to='members.member')),
                ('workflow_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_closure', to='workflows.workflowevent')),
            ],
            options={
                'db_table': 'loan_closures',
            },
        ),
        migrations.CreateModel(
            name='ClosureRequirement',
            fields=[
                ('closure_requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_type', models.CharField(db_index=True, max_length=60)),
                ('requirement_status', models.CharField(db_index=True, max_length=60)),
                ('applicability_snapshot_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_closure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='closure.loanclosure')),
            ],
            options={
                'db_table': 'closure_requirements',
            },
        ),
        migrations.AddConstraint(
            model_name='loanclosure',
            constraint=models.CheckConstraint(check=models.Q(('closure_type', 'full_repayment')), name='loan_closure_full_repayment_only'),
        ),
        migrations.AddConstraint(
            model_name='loanclosure',
            constraint=models.CheckConstraint(check=models.Q(('closure_stage', 'financially_closed')), name='loan_closure_financial_stage_only'),
        ),
        migrations.AddConstraint(
            model_name='loanclosure',
            constraint=models.CheckConstraint(check=models.Q(('principal_paid_flag', True), ('interest_paid_flag', True), ('charges_paid_flag', True), ('total_outstanding_at_closure', 0)), name='loan_closure_zero_balance_only'),
        ),
        migrations.AddConstraint(
            model_name='loanclosure',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('closure_notes', ''), _negated=True), models.Q(('closed_by_role_code', ''), _negated=True)), name='loan_closure_text_required'),
        ),
        migrations.AddConstraint(
            model_name='closurerequirement',
            constraint=models.UniqueConstraint(fields=('loan_closure', 'requirement_type'), name='uniq_closure_requirement_type'),
        ),
        migrations.AddConstraint(
            model_name='closurerequirement',
            constraint=models.CheckConstraint(check=models.Q(('requirement_type__in', ('noc', 'security_return', 'archive'))), name='closure_requirement_type_bounded'),
        ),
        migrations.AddConstraint(
            model_name='closurerequirement',
            constraint=models.CheckConstraint(check=models.Q(('requirement_status__in', ('pending', 'not_applicable'))), name='closure_requirement_status_bounded'),
        ),
    ]
