# Generated by Django 5.0.6 on 2026-07-22 16:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closure', '0001_initial'),
        ('communications', '0013_exception_provider_vocabulary'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('legal_documents', '0015_checklist_constraint_state_owner_anchor'),
        ('loans', '0009_dpd_pointer_integrity'),
        ('members', '0015_member_aadhaar_last4'),
        ('workflows', '0001_canonical_workflow_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='NocRecord',
            fields=[
                ('noc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_by_role_code', models.CharField(max_length=100)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('signatory_role_code', models.CharField(max_length=100)),
                ('signatory_name_snapshot', models.CharField(max_length=200)),
                ('delivery_mode', models.CharField(max_length=60)),
                ('delivery_status', models.CharField(max_length=60)),
                ('recipient_address', models.CharField(max_length=255)),
                ('document_template_id_snapshot', models.UUIDField()),
                ('document_template_version_snapshot', models.CharField(max_length=40)),
                ('renderer_contract_version_snapshot', models.CharField(max_length=64)),
                ('document_checksum_sha256_snapshot', models.CharField(max_length=128)),
                ('merge_values_sha256_snapshot', models.CharField(max_length=64)),
                ('borrower_name_snapshot', models.CharField(max_length=255)),
                ('loan_account_number_snapshot', models.CharField(max_length=80)),
                ('application_reference_snapshot', models.CharField(max_length=40)),
                ('disbursed_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=18)),
                ('full_repayment_at_snapshot', models.DateTimeField()),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('payload_digest', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'nocs',
            },
        ),
        migrations.RemoveConstraint(
            model_name='closurerequirement',
            name='closure_requirement_status_bounded',
        ),
        migrations.AddConstraint(
            model_name='closurerequirement',
            constraint=models.CheckConstraint(check=models.Q(('requirement_status__in', ('pending', 'not_applicable', 'completed'))), name='closure_requirement_status_bounded'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='communication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='noc', to='communications.communication'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='communication_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='noc', to='communications.communicationdeliveryjob'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='noc', to='documents.documentfile'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='generation_audit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generated_noc', to='identity.auditlog'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='issue_audit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='noc_issue', to='identity.auditlog'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='issue_workflow_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='noc_issue', to='workflows.workflowevent'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='issued_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_nocs', to='identity.user'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nocs', to='loans.loanaccount'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='loan_closure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='noc', to='closure.loanclosure'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='loan_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='noc', to='legal_documents.loandocument'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nocs', to='members.member'),
        ),
        migrations.AddField(
            model_name='nocrecord',
            name='signatory_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_nocs', to='identity.user'),
        ),
        migrations.AddConstraint(
            model_name='nocrecord',
            constraint=models.CheckConstraint(check=models.Q(('delivery_mode', 'email')), name='noc_delivery_mode_email'),
        ),
        migrations.AddConstraint(
            model_name='nocrecord',
            constraint=models.CheckConstraint(check=models.Q(('delivery_status__in', ('queued', 'sent', 'failed'))), name='noc_delivery_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='nocrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('issued_by_role_code', ''), _negated=True), models.Q(('signatory_role_code', ''), _negated=True), models.Q(('signatory_name_snapshot', ''), _negated=True), models.Q(('recipient_address', ''), _negated=True), models.Q(('borrower_name_snapshot', ''), _negated=True), models.Q(('loan_account_number_snapshot', ''), _negated=True), models.Q(('application_reference_snapshot', ''), _negated=True)), name='noc_required_text_complete'),
        ),
    ]
