# Generated by Django 5.0.6 on 2026-07-22 17:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closure', '0002_noc_issuance'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('security_instruments', '0006_migrate_opaque_field_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityReturn',
            fields=[
                ('security_return_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_status', models.CharField(db_index=True, max_length=40)),
                ('version', models.PositiveIntegerField(default=0)),
                ('recorded_by_role_code', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('payload_digest', models.CharField(max_length=64)),
                ('acknowledgement_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_return_acknowledgements', to='documents.documentfile')),
                ('loan_closure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='security_return', to='closure.loanclosure')),
                ('record_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='security_return_record', to='identity.auditlog')),
                ('recorded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_security_returns', to='identity.user')),
                ('security_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_returns', to='security_instruments.securitypackage')),
            ],
            options={
                'db_table': 'security_returns',
            },
        ),
        migrations.CreateModel(
            name='SecurityReturnItem',
            fields=[
                ('security_return_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=40)),
                ('item_status', models.CharField(db_index=True, max_length=40)),
                ('source_item_id', models.UUIDField(blank=True, null=True)),
                ('custody_location', models.CharField(blank=True, max_length=255, null=True)),
                ('returned_released_to', models.CharField(blank=True, max_length=255, null=True)),
                ('returned_released_at', models.DateTimeField(blank=True, null=True)),
                ('pending_reason', models.TextField(blank=True, null=True)),
                ('psn', models.CharField(blank=True, max_length=120, null=True)),
                ('urf_date', models.DateField(blank=True, null=True)),
                ('unpledge_type', models.CharField(blank=True, max_length=20, null=True)),
                ('pledgor_dp_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('pledgee_dp_acted_at', models.DateTimeField(blank=True, null=True)),
                ('pledgee_dp_outcome', models.CharField(blank=True, max_length=20, null=True)),
                ('auto_unpledge_flag', models.BooleanField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_return_item_acknowledgements', to='documents.documentfile')),
                ('completion_evidence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_return_completion_evidence', to='documents.documentfile')),
                ('returned_released_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_return_items_released', to='identity.user')),
                ('security_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='closure.securityreturn')),
                ('transition_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='security_return_item_transition', to='identity.auditlog')),
                ('urf_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_return_urfs', to='documents.documentfile')),
            ],
            options={
                'db_table': 'security_return_items',
            },
        ),
        migrations.CreateModel(
            name='SecurityReturnRequest',
            fields=[
                ('security_return_request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('payload_digest', models.CharField(max_length=64)),
                ('resulting_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('security_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='closure.securityreturn')),
            ],
            options={
                'db_table': 'security_return_requests',
            },
        ),
        migrations.AddConstraint(
            model_name='securityreturn',
            constraint=models.CheckConstraint(check=models.Q(('return_status__in', ('pending', 'completed'))), name='security_return_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='securityreturn',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completed_at__isnull', True), ('return_status', 'pending')), models.Q(('completed_at__isnull', False), ('return_status', 'completed')), _connector='OR'), name='security_return_completion_consistent'),
        ),
        migrations.AddConstraint(
            model_name='securityreturn',
            constraint=models.CheckConstraint(check=models.Q(('recorded_by_role_code', ''), _negated=True), name='security_return_role_required'),
        ),
        migrations.AddConstraint(
            model_name='securityreturnitem',
            constraint=models.UniqueConstraint(fields=('security_return', 'item_type'), name='uniq_security_return_item_type'),
        ),
        migrations.AddConstraint(
            model_name='securityreturnitem',
            constraint=models.CheckConstraint(check=models.Q(('item_type__in', ('sh4', 'blank_cheque', 'poa', 'cdsl'))), name='security_return_item_type_bounded'),
        ),
        migrations.AddConstraint(
            model_name='securityreturnitem',
            constraint=models.CheckConstraint(check=models.Q(('item_status__in', ('not_applicable', 'pending', 'returned', 'released', 'rejected', 'completed'))), name='security_return_item_status_bounded'),
        ),
    ]
