# Generated by Ralph slice 004B.

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualMemberProfile",
            fields=[
                (
                    "individual_member_profile_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "land_area_under_cultivation_acres",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("primary_crop", models.CharField(blank=True, max_length=100)),
                ("services_availed_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_profile",
                        to="members.member",
                    ),
                ),
            ],
            options={"db_table": "individual_member_profiles"},
        ),
        migrations.CreateModel(
            name="ProducerInstitutionProfile",
            fields=[
                (
                    "producer_institution_profile_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("institution_type", models.CharField(max_length=80)),
                (
                    "registration_number",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("authorised_signatory_name", models.CharField(max_length=200)),
                ("board_resolution_required_flag", models.BooleanField(default=False)),
                ("services_availed_flag", models.BooleanField(default=False)),
                (
                    "produce_supply_years",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producer_institution_profile",
                        to="members.member",
                    ),
                ),
            ],
            options={"db_table": "producer_institution_profiles"},
        ),
    ]
