# Generated by Ralph slice 004C.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_profile_shells"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualmemberprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualmemberprofile",
            name="employment_or_service_years",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="individualmemberprofile",
            name="first_name",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="individualmemberprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="individualmemberprofile",
            name="last_name",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="individualmemberprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="individualmemberprofile",
            name="occupation",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
