# Generated by Ralph slice 004D.

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_individual_profile_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nominee",
            fields=[
                (
                    "nominee_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("loan_application_id", models.UUIDField(blank=True, null=True)),
                ("nominee_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age_at_application", models.PositiveIntegerField(blank=True, null=True)),
                ("gender", models.CharField(max_length=40)),
                ("relationship_to_borrower", models.CharField(blank=True, max_length=100)),
                ("pan_encrypted", models.TextField()),
                ("pan_hash", models.CharField(db_index=True, max_length=128)),
                ("aadhaar_encrypted", models.TextField()),
                ("aadhaar_hash", models.CharField(db_index=True, max_length=128)),
                ("kyc_status", models.CharField(default="pending", max_length=60)),
                ("minor_flag", models.BooleanField(db_index=True, default=False)),
                ("signature_required_flag", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominees",
                        to="members.member",
                    ),
                ),
            ],
            options={"db_table": "nominees"},
        ),
        migrations.AddIndex(
            model_name="nominee",
            index=models.Index(fields=["member"], name="idx_nominees_member"),
        ),
        migrations.AddIndex(
            model_name="nominee",
            index=models.Index(fields=["minor_flag"], name="idx_nominees_minor_flag"),
        ),
        migrations.AddIndex(
            model_name="nominee",
            index=models.Index(fields=["pan_hash"], name="idx_nominees_pan_hash"),
        ),
        migrations.AddIndex(
            model_name="nominee",
            index=models.Index(fields=["aadhaar_hash"], name="idx_nominees_aadhaar_hash"),
        ),
    ]
