# Generated by Django 5.0.6 on 2026-07-09 07:06

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_nominee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholding',
            fields=[
                ('shareholding_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio_number', models.CharField(db_index=True, max_length=100)),
                ('number_of_shares', models.IntegerField()),
                ('holding_mode', models.CharField(db_index=True, max_length=40)),
                ('demat_account_id', models.UUIDField(blank=True, null=True)),
                ('latest_share_valuation_id', models.UUIDField(blank=True, null=True)),
                ('valuation_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valuation_effective_date', models.DateField(blank=True, null=True)),
                ('pledged_share_count', models.IntegerField(default=0)),
                ('available_share_count', models.IntegerField()),
                ('future_shares_pledge_flag', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholdings', to='members.member')),
            ],
            options={
                'db_table': 'shareholdings',
                'indexes': [models.Index(fields=['member'], name='idx_shareholdings_member'), models.Index(fields=['folio_number'], name='idx_shareholdings_folio'), models.Index(fields=['holding_mode'], name='idx_shareholdings_mode')],
            },
        ),
        migrations.AddConstraint(
            model_name='shareholding',
            constraint=models.CheckConstraint(check=models.Q(('number_of_shares__gte', 0)), name='shareholdings_non_negative_shares'),
        ),
        migrations.AddConstraint(
            model_name='shareholding',
            constraint=models.CheckConstraint(check=models.Q(('pledged_share_count__gte', 0)), name='shareholdings_non_negative_pledged'),
        ),
        migrations.AddConstraint(
            model_name='shareholding',
            constraint=models.CheckConstraint(check=models.Q(('pledged_share_count__lte', models.F('number_of_shares'))), name='shareholdings_pledged_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='shareholding',
            constraint=models.CheckConstraint(check=models.Q(('available_share_count', django.db.models.expressions.CombinedExpression(models.F('number_of_shares'), '-', models.F('pledged_share_count')))), name='shareholdings_available_derived'),
        ),
    ]
