# Generated by Django 5.0.6 on 2026-07-09 07:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_permission_rolepermission_and_more'),
        ('members', '0005_shareholding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandHolding',
            fields=[
                ('land_holding_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=80)),
                ('survey_number', models.CharField(blank=True, max_length=120)),
                ('village', models.CharField(blank=True, max_length=150)),
                ('taluka', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=150)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document_id', models.UUIDField()),
                ('verification_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_holdings', to='members.member')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_land_holdings', to='identity.user')),
            ],
            options={
                'db_table': 'land_holdings',
            },
        ),
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('crop_plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_application_id', models.UUIDField(blank=True, null=True)),
                ('crop_type', models.CharField(db_index=True, max_length=100)),
                ('season', models.CharField(blank=True, max_length=100)),
                ('planned_area_acres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('loan_purpose_alignment', models.CharField(max_length=60)),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('verification_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to='members.member')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_crop_plans', to='identity.user')),
            ],
            options={
                'db_table': 'crop_plans',
                'indexes': [models.Index(fields=['member'], name='idx_crop_plans_member'), models.Index(fields=['crop_type'], name='idx_crop_plans_crop_type'), models.Index(fields=['verification_status'], name='idx_crop_plans_verify')],
            },
        ),
        migrations.AddConstraint(
            model_name='cropplan',
            constraint=models.CheckConstraint(check=models.Q(('planned_area_acres__gt', 0)), name='crop_plans_positive_area'),
        ),
        migrations.AddIndex(
            model_name='landholding',
            index=models.Index(fields=['member'], name='idx_land_holdings_member'),
        ),
        migrations.AddIndex(
            model_name='landholding',
            index=models.Index(fields=['verification_status'], name='idx_land_holdings_verify'),
        ),
        migrations.AddConstraint(
            model_name='landholding',
            constraint=models.CheckConstraint(check=models.Q(('area_acres__gt', 0)), name='land_holdings_positive_area'),
        ),
    ]
