# Generated by Django 5.0.6 on 2026-07-09 08:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('identity', '0002_permission_rolepermission_and_more'),
        ('members', '0006_landholding_cropplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycProfile',
            fields=[
                ('kyc_profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_type', models.CharField(db_index=True, max_length=60)),
                ('party_id', models.UUIDField(db_index=True)),
                ('kyc_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('ckyc_identifier_encrypted', models.TextField(blank=True, null=True)),
                ('ckyc_consent_flag', models.BooleanField()),
                ('beneficial_ownership_verified_flag', models.BooleanField(blank=True, null=True)),
                ('risk_rating', models.CharField(blank=True, max_length=60, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('rekyc_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_verified_kyc_profiles', to='identity.user')),
            ],
            options={
                'db_table': 'kyc_profiles',
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('kyc_document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(db_index=True, max_length=80)),
                ('self_attested_flag', models.BooleanField()),
                ('verification_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_documents', to='documents.documentfile')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_kyc_documents', to='identity.user')),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.kycprofile')),
            ],
            options={
                'db_table': 'kyc_documents',
            },
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['party_type', 'party_id'], name='idx_kyc_profiles_party'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['kyc_status'], name='idx_kyc_profiles_status'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['rekyc_due_date'], name='idx_kyc_profiles_rekyc_due'),
        ),
        migrations.AddConstraint(
            model_name='kycprofile',
            constraint=models.UniqueConstraint(fields=('party_type', 'party_id'), name='kyc_profiles_unique_party'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['kyc_profile'], name='idx_kyc_documents_profile'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['document_type'], name='idx_kyc_documents_type'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['verification_status'], name='idx_kyc_documents_status'),
        ),
    ]
