# Generated by Django 5.0.6 on 2026-07-09 10:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_kycprofile_kycdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledCheque',
            fields=[
                ('cancelled_cheque_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_application_id', models.UUIDField(blank=True, null=True)),
                ('document_id', models.UUIDField()),
                ('account_number_encrypted', models.TextField()),
                ('account_number_hash', models.CharField(db_index=True, max_length=128)),
                ('account_number_last4', models.CharField(blank=True, max_length=4)),
                ('ifsc', models.CharField(db_index=True, max_length=20)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('verification_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('signature_mismatch_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_cheques', to='members.member')),
            ],
            options={
                'db_table': 'cancelled_cheques',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_party_type', models.CharField(db_index=True, max_length=60)),
                ('owner_party_id', models.UUIDField(db_index=True)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number_encrypted', models.TextField()),
                ('account_number_hash', models.CharField(db_index=True, max_length=128)),
                ('account_number_last4', models.CharField(blank=True, max_length=4)),
                ('ifsc', models.CharField(db_index=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('verification_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('signature_verified_flag', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='members.cancelledcheque')),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.AddIndex(
            model_name='cancelledcheque',
            index=models.Index(fields=['member'], name='idx_can_cheques_member'),
        ),
        migrations.AddIndex(
            model_name='cancelledcheque',
            index=models.Index(fields=['document_id'], name='idx_can_cheques_doc'),
        ),
        migrations.AddIndex(
            model_name='cancelledcheque',
            index=models.Index(fields=['account_number_hash'], name='idx_can_cheques_acct_hash'),
        ),
        migrations.AddIndex(
            model_name='cancelledcheque',
            index=models.Index(fields=['verification_status'], name='idx_can_cheques_verify'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['owner_party_type', 'owner_party_id'], name='idx_bank_accounts_owner'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_number_hash'], name='idx_bank_accounts_hash'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['ifsc'], name='idx_bank_accounts_ifsc'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['verification_status'], name='idx_bank_accounts_verify'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['status'], name='idx_bank_accounts_status'),
        ),
    ]
