# Generated by Django 5.0.6 on 2026-07-12 05:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_portal_member_auth'),
        ('members', '0010_member_identity_change_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceSupplyRecord',
            fields=[
                ('produce_supply_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(db_index=True, max_length=20)),
                ('supplied_to_entity_type', models.CharField(max_length=60)),
                ('supplied_to_entity_id', models.UUIDField(blank=True, null=True)),
                ('supply_route', models.CharField(max_length=60)),
                ('crop_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('value_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('verified_flag', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('captured_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_produce_supply_records', to='identity.user')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produce_supply_records', to='members.member')),
                ('producer_institution_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routed_produce_supply_records', to='members.member')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_produce_supply_records', to='identity.user')),
            ],
            options={
                'db_table': 'produce_supply_records',
                'ordering': ['-financial_year', 'produce_supply_record_id'],
                'indexes': [models.Index(fields=['member', 'financial_year'], name='idx_supply_member_year'), models.Index(fields=['member', 'verified_flag'], name='idx_supply_member_verified')],
            },
        ),
    ]
