# Generated by Django 5.0.6 on 2026-07-12 18:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_portal_member_auth'),
        ('members', '0011_producesupplyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberServiceEvidence',
            fields=[
                ('member_service_evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=60)),
                ('recipient_entity_type', models.CharField(max_length=60)),
                ('recipient_entity_id', models.UUIDField(blank=True, null=True)),
                ('service_from', models.DateField()),
                ('service_to', models.DateField()),
                ('evidence_reference', models.CharField(max_length=255)),
                ('verified_at', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_evidence', to='members.member')),
                ('verified_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_member_service_evidence', to='identity.user')),
            ],
            options={
                'db_table': 'member_service_evidence',
            },
        ),
        migrations.CreateModel(
            name='ActiveMemberStatus',
            fields=[
                ('active_member_status_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(db_index=True, max_length=60)),
                ('member_type', models.CharField(max_length=60)),
                ('services_availed_flag', models.BooleanField()),
                ('continuous_supply_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('supplied_to_company_flag', models.BooleanField(default=False)),
                ('supplied_to_subsidiary_flag', models.BooleanField(default=False)),
                ('supplied_to_stepdown_flag', models.BooleanField(default=False)),
                ('supplied_through_producer_institution_flag', models.BooleanField(default=False)),
                ('employment_service_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('relaxation_reason', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('evidence_snapshot', models.JSONField(default=dict)),
                ('verified_at', models.DateTimeField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_status_records', to='members.member')),
                ('verified_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_active_member_statuses', to='identity.user')),
            ],
            options={
                'db_table': 'active_member_statuses',
                'indexes': [models.Index(fields=['member', 'status'], name='idx_active_member_status'), models.Index(fields=['member', 'effective_from', 'effective_to'], name='idx_active_status_effective')],
            },
        ),
        migrations.AddConstraint(
            model_name='activememberstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('member',), name='uniq_current_active_member_status'),
        ),
        migrations.AddIndex(
            model_name='memberserviceevidence',
            index=models.Index(fields=['member', 'service_from', 'service_to'], name='idx_service_evidence_dates'),
        ),
    ]
