# Generated by Django 5.0.6 on 2026-07-12 23:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def backfill_service_evidence_makers(apps, schema_editor):
    evidence_model = apps.get_model('members', 'MemberServiceEvidence')
    through_model = evidence_model.maker_users.through
    through_model.objects.bulk_create([
        through_model(
            memberserviceevidence_id=row.member_service_evidence_id,
            user_id=row.verified_by_user_id,
        )
        for row in evidence_model.objects.all().iterator()
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_portal_member_auth'),
        ('members', '0012_memberserviceevidence_activememberstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberserviceevidence',
            name='maker_users',
            field=models.ManyToManyField(related_name='made_member_service_evidence', to='identity.user'),
        ),
        migrations.RunPython(backfill_service_evidence_makers, migrations.RunPython.noop),
        migrations.CreateModel(
            name='MemberScopeAssignment',
            fields=[
                ('member_scope_assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_code', models.CharField(db_index=True, max_length=120)),
                ('scope_type', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope_assignments', to='members.member')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_scope_assignments', to='identity.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_scope_assignments', to='identity.user')),
            ],
            options={
                'db_table': 'member_scope_assignments',
                'indexes': [models.Index(fields=['user', 'permission_code'], name='idx_member_scope_user_perm')],
            },
        ),
        migrations.AddConstraint(
            model_name='memberscopeassignment',
            constraint=models.UniqueConstraint(fields=('user', 'permission_code', 'scope_type', 'member', 'team'), name='uniq_member_scope_assignment'),
        ),
    ]
