# Generated by Django 5.0.6 on 2026-07-13 00:44

from django.db import migrations, models


def deduplicate_nullable_scope_assignments(apps, schema_editor):
    assignment = apps.get_model("members", "MemberScopeAssignment")
    seen = set()
    duplicate_ids = []
    for row in assignment.objects.order_by("created_at", "member_scope_assignment_id").iterator():
        key = (
            row.user_id,
            row.permission_code,
            row.scope_type,
            row.member_id,
            row.team_id,
        )
        if key in seen:
            duplicate_ids.append(row.member_scope_assignment_id)
        else:
            seen.add(key)
    assignment.objects.filter(member_scope_assignment_id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_portal_member_auth'),
        ('members', '0013_memberserviceevidence_maker_users_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='memberscopeassignment',
            name='uniq_member_scope_assignment',
        ),
        migrations.RunPython(
            deduplicate_nullable_scope_assignments,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='memberscopeassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('member__isnull', True), ('scope_type__in', ('global', 'created_by')), ('team__isnull', True)), models.Q(('member__isnull', False), ('scope_type', 'assigned'), ('team__isnull', True)), models.Q(('member__isnull', False), ('scope_type', 'team'), ('team__isnull', False)), _connector='OR'), name='member_scope_valid_shape'),
        ),
        migrations.AddConstraint(
            model_name='memberscopeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type__in', ('global', 'created_by'))), fields=('user', 'permission_code', 'scope_type'), name='uniq_member_scope_unbound'),
        ),
        migrations.AddConstraint(
            model_name='memberscopeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'assigned')), fields=('user', 'permission_code', 'member'), name='uniq_member_scope_assigned'),
        ),
        migrations.AddConstraint(
            model_name='memberscopeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'team')), fields=('user', 'permission_code', 'member', 'team'), name='uniq_member_scope_team'),
        ),
    ]
