# Generated by Django 5.0.6 on 2026-07-17 06:04

import django.db.models.deletion
from django.db import migrations, models


ENTITY_TYPE = "source_bank_account_governance"


def _iso(value):
    return value.isoformat().replace("+00:00", "Z")


def _active_evidence(row, predecessor_id):
    return {
        "governance_id": str(row.pk),
        "source_bank_account_id": str(row.bank_account_id),
        "predecessor_governance_id": (
            str(predecessor_id) if predecessor_id else None
        ),
        "source_facts_digest": row.source_facts_digest,
        "reason_digest": row.reason_digest,
        "request_id": row.request_id,
        "status": "active",
        "activated_by_user_id": str(row.activated_by_user_id),
        "activated_at": _iso(row.activated_at),
    }


def _inactive_evidence(row, predecessor_id, deactivated_at, successor_id):
    return {
        **_active_evidence(row, predecessor_id),
        "status": "inactive",
        "deactivated_at": _iso(deactivated_at),
        "successor_governance_id": str(successor_id),
    }


def _audit_evidence(evidence, row, roles, teams):
    return {
        **evidence,
        "actor_role_codes": roles,
        "actor_team_codes": teams,
        "reason": "sha256:" + row.reason_digest,
    }


def backfill_governance_history(apps, schema_editor):
    Governance = apps.get_model("configurations", "SourceBankAccountGovernance")
    VersionHistory = apps.get_model("configurations", "VersionHistory")
    AuditLog = apps.get_model("identity", "AuditLog")
    rows = list(Governance.objects.order_by("activated_at", "pk"))
    for index, row in enumerate(rows):
        predecessor = rows[index - 1] if index else None
        successor = rows[index + 1] if index + 1 < len(rows) else None
        predecessor_id = predecessor.pk if predecessor else None
        Governance.objects.filter(pk=row.pk).update(predecessor_id=predecessor_id)
        active = _active_evidence(row, predecessor_id)
        old = None
        if predecessor is not None:
            old = _inactive_evidence(
                predecessor,
                rows[index - 2].pk if index > 1 else None,
                row.activated_at,
                row.pk,
            )
        roles = list(
            row.activated_by_user.primary_role.__class__.objects.filter(
                pk=row.activated_by_user.primary_role_id
            ).values_list("role_code", flat=True)
        )
        teams = list(
            row.activated_by_user.team_memberships.filter(
                status="active", team__status="active"
            ).values_list("team__team_code", flat=True)
        )
        history = row.version_history
        if history is None:
            history = VersionHistory.objects.create(
                versioned_entity_type=ENTITY_TYPE,
                versioned_entity_id=row.pk,
                version_number="1",
                change_summary="Source-bank account activation evidence backfilled.",
                author_user_id=row.activated_by_user_id,
                approver_user_id=row.activated_by_user_id,
                approval_reference=row.request_id,
                approved_at=row.activated_at,
                effective_from=row.activated_at.date(),
                created_at=row.activated_at,
            )
        audit = row.activation_audit
        if audit is None:
            audit = AuditLog.objects.create(
                actor_user_id=row.activated_by_user_id,
                actor_type="user",
                action="config.changed",
                entity_type=ENTITY_TYPE,
                entity_id=row.pk,
                created_at=row.activated_at,
            )
        effective_to = successor.activated_at.date() if successor else None
        VersionHistory.objects.filter(pk=history.pk).update(
            old_value_json=old,
            new_value_json=active,
            effective_from=row.activated_at.date(),
            effective_to=effective_to,
        )
        AuditLog.objects.filter(pk=audit.pk).update(
            old_value_json=old,
            new_value_json=_audit_evidence(active, row, roles, teams),
        )
        updates = {
            "version_history_id": history.pk,
            "activation_audit_id": audit.pk,
        }
        if row.status == "inactive":
            deactivated_at = successor.activated_at if successor else row.activated_at
            successor_id = successor.pk if successor else row.pk
            deactivation_actor = successor or row
            deactivation_roles = [
                deactivation_actor.activated_by_user.primary_role.role_code
            ]
            deactivation_teams = list(
                deactivation_actor.activated_by_user.team_memberships.filter(
                    status="active", team__status="active"
                ).values_list("team__team_code", flat=True)
            )
            inactive = _inactive_evidence(
                row, predecessor_id, deactivated_at, successor_id
            )
            deactivation_history = VersionHistory.objects.create(
                versioned_entity_type=ENTITY_TYPE,
                versioned_entity_id=row.pk,
                version_number="2",
                change_summary="Source-bank account deactivation evidence backfilled.",
                author_user_id=(
                    successor.activated_by_user_id
                    if successor
                    else row.activated_by_user_id
                ),
                approver_user_id=(
                    successor.activated_by_user_id
                    if successor
                    else row.activated_by_user_id
                ),
                approval_reference=(successor.request_id if successor else row.request_id),
                approved_at=deactivated_at,
                old_value_json=active,
                new_value_json=inactive,
                effective_from=deactivated_at.date(),
                effective_to=deactivated_at.date(),
                created_at=deactivated_at,
            )
            deactivation_audit = AuditLog.objects.create(
                actor_user_id=(
                    successor.activated_by_user_id
                    if successor
                    else row.activated_by_user_id
                ),
                actor_type="user",
                action="config.changed",
                entity_type=ENTITY_TYPE,
                entity_id=row.pk,
                old_value_json=active,
                new_value_json=_audit_evidence(
                    inactive,
                    deactivation_actor,
                    deactivation_roles,
                    deactivation_teams,
                ),
                created_at=deactivated_at,
            )
            updates.update(
                deactivated_at=deactivated_at,
                deactivation_version_history_id=deactivation_history.pk,
                deactivation_audit_id=deactivation_audit.pk,
            )
        Governance.objects.filter(pk=row.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_source_bank_account_governance'),
        ('identity', '0003_portal_member_auth'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcebankaccountgovernance',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcebankaccountgovernance',
            name='deactivation_audit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_bank_governance_deactivation', to='identity.auditlog'),
        ),
        migrations.AddField(
            model_name='sourcebankaccountgovernance',
            name='deactivation_version_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_bank_governance_deactivation', to='configurations.versionhistory'),
        ),
        migrations.AddField(
            model_name='sourcebankaccountgovernance',
            name='predecessor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='configurations.sourcebankaccountgovernance'),
        ),
        migrations.RunPython(backfill_governance_history, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='sourcebankaccountgovernance',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activation_audit__isnull', False), ('deactivated_at__isnull', True), ('deactivation_audit__isnull', True), ('deactivation_version_history__isnull', True), ('status', 'active'), ('version_history__isnull', False)), models.Q(('activation_audit__isnull', False), ('deactivated_at__isnull', False), ('deactivation_audit__isnull', False), ('deactivation_version_history__isnull', False), ('status', 'inactive'), ('version_history__isnull', False)), _connector='OR'), name='source_bank_governance_complete_evidence'),
        ),
        migrations.AddConstraint(
            model_name='sourcebankaccountgovernance',
            constraint=models.CheckConstraint(check=models.Q(('deactivated_at__isnull', True), ('deactivated_at__gte', models.F('activated_at')), _connector='OR'), name='source_bank_governance_time_order'),
        ),
    ]
