# Generated by Django 5.0.6 on 2026-07-17

from django.db import migrations, models


def clear_false_source_bank_approval_claims(apps, schema_editor):
    VersionHistory = apps.get_model("configurations", "VersionHistory")
    VersionHistory.objects.filter(
        versioned_entity_type="source_bank_account_governance"
    ).update(
        approver_user_id=None,
        approval_reference="",
        approved_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0004_source_bank_governance_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcebankaccountgovernance",
            name="change_context_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="sourcebankaccountgovernance",
            name="change_context_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcebankaccountgovernance",
            name="reason",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(
            clear_false_source_bank_approval_claims,
            migrations.RunPython.noop,
        ),
    ]
