# Generated by Django 5.0.6 on 2026-07-19 23:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0013_exception_provider_vocabulary'),
        ('configurations', '0005_source_bank_reviewable_rationale'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('loans', '0008_subsidiary_deduction_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRateConfig',
            fields=[
                ('interest_rate_config_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(max_length=40, unique=True)),
                ('rate_type', models.CharField(default='floating', max_length=60)),
                ('effective_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('benchmark_name', models.CharField(blank=True, max_length=120, null=True)),
                ('spread_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('reset_frequency', models.CharField(blank=True, max_length=60, null=True)),
                ('communication_required', models.BooleanField(default=True)),
                ('board_approval_reference', models.CharField(max_length=255)),
                ('status', models.CharField(db_index=True, default='proposed', max_length=40)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activation_idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('activation_payload_digest', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_interest_rate_configs', to='identity.user')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_interest_rate_configs', to='identity.user')),
            ],
            options={
                'db_table': 'interest_rate_configs',
                'ordering': ['-effective_from', '-interest_rate_config_id'],
            },
        ),
        migrations.CreateModel(
            name='BorrowerRateNoticeObligation',
            fields=[
                ('borrower_rate_notice_obligation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_failure_code', models.CharField(blank=True, default='', max_length=80)),
                ('sms_failure_code', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_communication', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_rate_notice_obligation', to='communications.communication')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_notice_obligations', to='loans.loanaccount')),
                ('sms_communication', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sms_rate_notice_obligation', to='communications.communication')),
                ('interest_rate_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_notice_obligations', to='configurations.interestrateconfig')),
            ],
            options={
                'db_table': 'borrower_rate_notice_obligations',
                'ordering': ['interest_rate_config_id', 'loan_account_id'],
            },
        ),
        migrations.CreateModel(
            name='InterestRateConsumptionSnapshot',
            fields=[
                ('interest_rate_consumption_snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer_kind', models.CharField(max_length=60)),
                ('consumer_reference_id', models.UUIDField()),
                ('calculation_date', models.DateField()),
                ('version_number', models.CharField(max_length=40)),
                ('effective_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_rate_consumption_snapshots', to='loans.loanaccount')),
                ('rate_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_snapshots', to='configurations.interestrateconfig')),
            ],
            options={
                'db_table': 'interest_rate_consumption_snapshots',
            },
        ),
        migrations.CreateModel(
            name='InterestRateHistory',
            fields=[
                ('interest_rate_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('new_interest_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('effective_from', models.DateField(db_index=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('borrower_communication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interest_rate_histories', to='communications.communication')),
                ('changed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changed_interest_rate_histories', to='identity.user')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_rate_histories', to='loans.loanaccount')),
                ('rate_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_rate_histories', to='configurations.interestrateconfig')),
            ],
            options={
                'db_table': 'interest_rate_histories',
                'ordering': ['effective_from', 'interest_rate_history_id'],
            },
        ),
        migrations.AddIndex(
            model_name='interestrateconfig',
            index=models.Index(fields=['status', 'effective_from', 'effective_to'], name='idx_rate_status_period'),
        ),
        migrations.AddConstraint(
            model_name='interestrateconfig',
            constraint=models.CheckConstraint(check=models.Q(('rate_type', 'floating')), name='interest_rate_type_floating'),
        ),
        migrations.AddConstraint(
            model_name='interestrateconfig',
            constraint=models.CheckConstraint(check=models.Q(('effective_rate__gte', 0)), name='interest_rate_effective_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='interestrateconfig',
            constraint=models.CheckConstraint(check=models.Q(('spread_rate__isnull', True), ('spread_rate__gte', 0), _connector='OR'), name='interest_rate_spread_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='interestrateconfig',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='interest_rate_period_order'),
        ),
        migrations.AddConstraint(
            model_name='interestrateconfig',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('proposed', 'active'))), name='interest_rate_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='borrowerratenoticeobligation',
            constraint=models.UniqueConstraint(fields=('interest_rate_config', 'loan_account'), name='uniq_rate_notice_loan'),
        ),
        migrations.AddConstraint(
            model_name='interestrateconsumptionsnapshot',
            constraint=models.UniqueConstraint(fields=('consumer_kind', 'consumer_reference_id'), name='uniq_interest_rate_consumer'),
        ),
        migrations.AddConstraint(
            model_name='interestratehistory',
            constraint=models.UniqueConstraint(fields=('loan_account', 'rate_config'), name='uniq_loan_rate_config_history'),
        ),
    ]
