# Generated by Django 5.0.6 on 2026-07-21 09:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_current_rate_projection_decision'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentInstructionVersion',
            fields=[
                ('repayment_instruction_version_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=40, unique=True)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number_last4', models.CharField(max_length=4)),
                ('ifsc', models.CharField(max_length=20)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=20)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_repayment_instruction_versions', to='identity.user')),
            ],
            options={
                'db_table': 'repayment_instruction_versions',
            },
        ),
        migrations.AddConstraint(
            model_name='repaymentinstructionversion',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('active', 'retired'))), name='repayment_instruction_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='repaymentinstructionversion',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='repayment_instruction_period_order'),
        ),
        migrations.AddConstraint(
            model_name='repaymentinstructionversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='uniq_active_repayment_instruction'),
        ),
    ]
