# Generated by Django 5.0.6 on 2026-07-20 01:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0013_exception_provider_vocabulary'),
        ('configurations', '0006_interestrateconfig_borrowerratenoticeobligation_and_more'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('loans', '0008_subsidiary_deduction_reconciliation'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestInvoiceConfiguration',
            fields=[
                ('interest_invoice_configuration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(max_length=40, unique=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(db_index=True)),
                ('calculation_method', models.CharField(max_length=40)),
                ('day_count_basis', models.PositiveSmallIntegerField()),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('fixed_fee_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('owner_role_codes', models.JSONField(default=list)),
                ('status', models.CharField(db_index=True, max_length=40)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_interest_invoice_configurations', to='identity.user')),
                ('communication_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interest_invoice_configurations', to='communications.contenttemplate')),
            ],
            options={
                'db_table': 'interest_invoice_configurations',
                'ordering': ['-effective_from', '-interest_invoice_configuration_id'],
            },
        ),
        migrations.CreateModel(
            name='InterestInvoice',
            fields=[
                ('interest_invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_account_number', models.CharField(max_length=80)),
                ('member_number', models.CharField(blank=True, default='', max_length=80)),
                ('member_display_name', models.CharField(max_length=255)),
                ('financial_year', models.CharField(db_index=True, max_length=20)),
                ('invoice_number', models.CharField(max_length=80, unique=True)),
                ('invoice_date', models.DateField(db_index=True)),
                ('interest_period_start', models.DateField()),
                ('interest_period_end', models.DateField()),
                ('principal_base_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('rate_version_number', models.CharField(max_length=40)),
                ('calculation_version', models.CharField(max_length=40)),
                ('calculation_method', models.CharField(max_length=40)),
                ('day_count_basis', models.PositiveSmallIntegerField()),
                ('calculation_days', models.PositiveSmallIntegerField()),
                ('gross_interest_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_paid_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fixed_fee_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invoice_status', models.CharField(db_index=True, default='draft', max_length=60)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generation_idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('generation_payload_digest', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('issuance_idempotency_key_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('issuance_payload_digest', models.CharField(blank=True, default='', max_length=64)),
                ('communication', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interest_invoice', to='communications.communication')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interest_invoice', to='documents.documentfile')),
                ('generated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_interest_invoices', to='identity.user')),
                ('generation_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generated_interest_invoice', to='identity.auditlog')),
                ('issuance_audit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_interest_invoice', to='identity.auditlog')),
                ('issued_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_interest_invoices', to='identity.user')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_invoices', to='loans.loanaccount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_invoices', to='members.member')),
                ('rate_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_invoices', to='configurations.interestrateconfig')),
                ('calculation_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_invoices', to='interest.interestinvoiceconfiguration')),
            ],
            options={
                'db_table': 'interest_invoices',
                'ordering': ['-invoice_date', '-interest_invoice_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='interestinvoiceconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__gte', models.F('effective_from'))), name='interest_invoice_config_period_order'),
        ),
        migrations.AddConstraint(
            model_name='interestinvoiceconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('calculation_method', 'simple_daily')), name='interest_invoice_config_method'),
        ),
        migrations.AddConstraint(
            model_name='interestinvoiceconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('day_count_basis__gt', 0)), name='interest_invoice_day_basis_positive'),
        ),
        migrations.AddConstraint(
            model_name='interestinvoiceconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('tax_rate__gte', 0), ('fixed_fee_amount__gte', 0)), name='interest_invoice_config_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='interestinvoiceconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('status', 'active')), name='interest_invoice_config_active'),
        ),
        migrations.AddIndex(
            model_name='interestinvoice',
            index=models.Index(fields=['loan_account', 'invoice_status'], name='idx_interest_inv_loan_status'),
        ),
        migrations.AddIndex(
            model_name='interestinvoice',
            index=models.Index(fields=['financial_year', 'invoice_status'], name='idx_interest_inv_fy_status'),
        ),
        migrations.AddConstraint(
            model_name='interestinvoice',
            constraint=models.UniqueConstraint(fields=('loan_account', 'interest_period_start', 'interest_period_end'), name='uniq_interest_invoice_loan_period'),
        ),
        migrations.AddConstraint(
            model_name='interestinvoice',
            constraint=models.CheckConstraint(check=models.Q(('invoice_status__in', ('draft', 'issued'))), name='interest_invoice_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='interestinvoice',
            constraint=models.CheckConstraint(check=models.Q(('interest_period_end__gte', models.F('interest_period_start'))), name='interest_invoice_period_order'),
        ),
        migrations.AddConstraint(
            model_name='interestinvoice',
            constraint=models.CheckConstraint(check=models.Q(('principal_base_amount__gte', 0), ('interest_rate__gte', 0), ('gross_interest_amount__gte', 0), ('interest_paid_amount__gte', 0), ('tax_rate__gte', 0), ('tax_amount__gte', 0), ('fixed_fee_amount__gte', 0), ('interest_amount__gte', 0)), name='interest_invoice_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='interestinvoice',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('communication__isnull', True), ('document__isnull', True), ('invoice_status', 'draft'), ('issuance_audit__isnull', True), ('issuance_idempotency_key_digest__isnull', True), ('issuance_payload_digest', ''), ('issued_at__isnull', True), ('issued_by_user__isnull', True)), models.Q(('communication__isnull', False), ('document__isnull', False), ('invoice_status', 'issued'), ('issuance_audit__isnull', False), ('issuance_idempotency_key_digest__isnull', False), ('issued_at__isnull', False), ('issued_by_user__isnull', False)), _connector='OR'), name='interest_invoice_issue_evidence_complete'),
        ),
    ]
