# Generated by Django 5.0.6 on 2026-07-20 03:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_interestrateconfig_borrowerratenoticeobligation_and_more'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('interest', '0001_initial'),
        ('loans', '0008_subsidiary_deduction_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccrualEntry',
            fields=[
                ('accrual_entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accrual_month', models.CharField(db_index=True, max_length=7)),
                ('interest_period_start', models.DateField()),
                ('interest_period_end', models.DateField()),
                ('principal_base_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('rate_version_number', models.CharField(max_length=40)),
                ('calculation_version', models.CharField(max_length=40)),
                ('calculation_method', models.CharField(max_length=40)),
                ('day_count_basis', models.PositiveSmallIntegerField()),
                ('calculation_days', models.PositiveSmallIntegerField()),
                ('interest_accrued_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('posted_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('sap_entry_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generation_idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('generation_payload_digest', models.CharField(max_length=64)),
                ('posting_idempotency_key_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('posting_payload_digest', models.CharField(blank=True, default='', max_length=64)),
                ('calculation_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accrual_entries', to='interest.interestinvoiceconfiguration')),
                ('generated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_interest_accruals', to='identity.user')),
                ('generation_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generated_interest_accrual', to='identity.auditlog')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accrual_entries', to='loans.loanaccount')),
                ('posted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_interest_accruals', to='identity.user')),
                ('posting_audit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_interest_accrual', to='identity.auditlog')),
                ('rate_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accrual_entries', to='configurations.interestrateconfig')),
            ],
            options={
                'db_table': 'accrual_entries',
                'ordering': ['-accrual_month', '-accrual_entry_id'],
            },
        ),
        migrations.CreateModel(
            name='AccrualSapPostingObligation',
            fields=[
                ('accrual_sap_posting_obligation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('accrual_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sap_posting_obligation', to='interest.accrualentry')),
            ],
            options={
                'db_table': 'accrual_sap_posting_obligations',
            },
        ),
        migrations.AddIndex(
            model_name='accrualentry',
            index=models.Index(fields=['loan_account', 'posted_status'], name='idx_accrual_loan_status'),
        ),
        migrations.AddConstraint(
            model_name='accrualentry',
            constraint=models.UniqueConstraint(fields=('loan_account', 'accrual_month'), name='uniq_accrual_loan_month'),
        ),
        migrations.AddConstraint(
            model_name='accrualentry',
            constraint=models.CheckConstraint(check=models.Q(('posted_status__in', ('pending', 'posted', 'failed'))), name='accrual_posted_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='accrualentry',
            constraint=models.CheckConstraint(check=models.Q(('interest_period_end__gte', models.F('interest_period_start'))), name='accrual_period_order'),
        ),
        migrations.AddConstraint(
            model_name='accrualentry',
            constraint=models.CheckConstraint(check=models.Q(('principal_base_amount__gt', 0), ('interest_rate__gte', 0), ('interest_accrued_amount__gte', 0), ('day_count_basis__gt', 0), ('calculation_days__gt', 0)), name='accrual_calculation_values_valid'),
        ),
        migrations.AddConstraint(
            model_name='accrualentry',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('posted_at__isnull', True), ('posted_by_user__isnull', True), ('posted_status', 'pending'), ('posting_audit__isnull', True), ('posting_idempotency_key_digest__isnull', True), ('posting_payload_digest', ''), ('sap_entry_reference', '')), models.Q(('posted_status', 'posted'), models.Q(('sap_entry_reference', ''), _negated=True), ('posted_at__isnull', False), ('posted_by_user__isnull', False), ('posting_audit__isnull', False), ('posting_idempotency_key_digest__isnull', False)), models.Q(('posted_at__isnull', False), ('posted_by_user__isnull', False), ('posted_status', 'failed'), ('posting_audit__isnull', False), ('posting_idempotency_key_digest__isnull', False), ('sap_entry_reference', '')), _connector='OR'), name='accrual_posting_evidence_coherent'),
        ),
        migrations.AddConstraint(
            model_name='accrualsappostingobligation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resolved_at__isnull', True), ('status', 'pending')), models.Q(('resolved_at__isnull', False), ('status__in', ('posted', 'failed'))), _connector='OR'), name='accrual_sap_obligation_status_valid'),
        ),
    ]
