# Generated by Django 5.0.6 on 2026-07-20 04:03

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0013_exception_provider_vocabulary'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('interest', '0002_accrualentry_accrualsappostingobligation_and_more'),
        ('loans', '0008_subsidiary_deduction_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestCapitalisation',
            fields=[
                ('interest_capitalisation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(db_index=True, max_length=20)),
                ('eligibility_as_of_date', models.DateField()),
                ('capitalisation_date', models.DateField(db_index=True)),
                ('old_principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unpaid_interest_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('new_principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate_versions_json', models.JSONField(default=list)),
                ('calculation_versions_json', models.JSONField(default=list)),
                ('source_accrual_ids_json', models.JSONField(default=list)),
                ('status', models.CharField(db_index=True, default='capitalised', max_length=60)),
                ('capitalised_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('payload_digest', models.CharField(max_length=64)),
                ('borrower_intimation_email', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interest_capitalisation', to='communications.communication')),
                ('borrower_intimation_letter_document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interest_capitalisation_letter', to='documents.documentfile')),
                ('capitalisation_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interest_capitalisation', to='identity.auditlog')),
                ('capitalised_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_capitalisations', to='identity.user')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_capitalisations', to='loans.loanaccount')),
            ],
            options={
                'db_table': 'interest_capitalisations',
                'ordering': ['capitalisation_date', 'interest_capitalisation_id'],
            },
        ),
        migrations.CreateModel(
            name='InterestCapitalisationInvoiceEvidence',
            fields=[
                ('interest_capitalisation_invoice_evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unpaid_interest_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('capitalisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_evidence', to='interest.interestcapitalisation')),
                ('interest_invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='capitalisation_evidence', to='interest.interestinvoice')),
            ],
            options={
                'db_table': 'interest_capitalisation_invoice_evidence',
            },
        ),
        migrations.CreateModel(
            name='InterestCapitalisationLedgerEntry',
            fields=[
                ('interest_capitalisation_ledger_entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(db_index=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('principal_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('charges_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_outstanding', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actor_display_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_capitalisation_ledger_entries', to='identity.user')),
                ('capitalisation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='interest.interestcapitalisation')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_capitalisation_ledger_entries', to='loans.loanaccount')),
            ],
            options={
                'db_table': 'interest_capitalisation_ledger_entries',
                'ordering': ['created_at', 'interest_capitalisation_ledger_entry_id'],
            },
        ),
        migrations.AddIndex(
            model_name='interestcapitalisation',
            index=models.Index(fields=['loan_account', 'capitalisation_date'], name='idx_interest_cap_loan_date'),
        ),
        migrations.AddConstraint(
            model_name='interestcapitalisation',
            constraint=models.UniqueConstraint(fields=('loan_account', 'financial_year'), name='uniq_interest_cap_loan_fy'),
        ),
        migrations.AddConstraint(
            model_name='interestcapitalisation',
            constraint=models.CheckConstraint(check=models.Q(('status', 'capitalised')), name='interest_cap_status_final'),
        ),
        migrations.AddConstraint(
            model_name='interestcapitalisation',
            constraint=models.CheckConstraint(check=models.Q(('old_principal_amount__gte', 0), ('unpaid_interest_amount__gt', 0), ('new_principal_amount__gt', 0)), name='interest_cap_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='interestcapitalisation',
            constraint=models.CheckConstraint(check=models.Q(('new_principal_amount', django.db.models.expressions.CombinedExpression(models.F('old_principal_amount'), '+', models.F('unpaid_interest_amount')))), name='interest_cap_arithmetic'),
        ),
        migrations.AddConstraint(
            model_name='interestcapitalisationinvoiceevidence',
            constraint=models.CheckConstraint(check=models.Q(('unpaid_interest_amount__gt', 0)), name='interest_cap_invoice_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='interestcapitalisationledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('debit_amount__gt', 0), ('principal_balance__gte', 0), ('interest_balance__gte', 0), ('charges_balance__gte', 0), ('total_outstanding__gte', 0)), name='interest_cap_ledger_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='interestcapitalisationledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('total_outstanding', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('principal_balance'), '+', models.F('interest_balance')), '+', models.F('charges_balance')))), name='interest_cap_ledger_total_parts'),
        ),
    ]
