# Generated by Django 5.0.6 on 2026-07-20 09:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0013_exception_provider_vocabulary'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('interest', '0003_interestcapitalisation_and_more'),
        ('loans', '0008_subsidiary_deduction_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrualentry',
            name='calculation_segments_json',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='accrualentry',
            name='generation_original_response_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='accrualentry',
            name='posting_original_response_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='interestcapitalisation',
            name='original_response_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='interestinvoice',
            name='calculation_segments_json',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='interestinvoice',
            name='communication_template_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_interest_invoice_snapshots', to='communications.contenttemplate'),
        ),
        migrations.AddField(
            model_name='interestinvoice',
            name='generation_original_response_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='interestinvoice',
            name='issuance_original_response_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='interestinvoice',
            name='owner_role_codes_snapshot_json',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='InterestCapitalisationHardCopyTask',
            fields=[
                ('interest_capitalisation_hard_copy_task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('capitalisation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hard_copy_task', to='interest.interestcapitalisation')),
                ('letter_document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interest_capitalisation_hard_copy_task', to='documents.documentfile')),
            ],
            options={
                'db_table': 'interest_capitalisation_hard_copy_tasks',
            },
        ),
        migrations.CreateModel(
            name='InterestCapitalisationPaymentEvidence',
            fields=[
                ('interest_capitalisation_payment_evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest_applied_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('capitalisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_evidence', to='interest.interestcapitalisation')),
                ('interest_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capitalisation_payment_evidence', to='interest.interestinvoice')),
                ('repayment_allocation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interest_capitalisation_evidence', to='loans.repaymentallocation')),
            ],
            options={
                'db_table': 'interest_capitalisation_payment_evidence',
            },
        ),
        migrations.CreateModel(
            name='InterestCapitalisationScheduleEvidence',
            fields=[
                ('interest_capitalisation_schedule_evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest_reclassified_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('schedule_status_before', models.CharField(max_length=60)),
                ('schedule_status_after', models.CharField(max_length=60)),
                ('capitalisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_evidence', to='interest.interestcapitalisation')),
                ('repayment_schedule', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interest_capitalisation_evidence', to='loans.repaymentschedule')),
            ],
            options={
                'db_table': 'interest_capitalisation_schedule_evidence',
            },
        ),
        migrations.CreateModel(
            name='InterestInvoicePaymentEvidence',
            fields=[
                ('interest_invoice_payment_evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest_applied_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_evidence', to='interest.interestinvoice')),
                ('schedule_application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interest_invoice_evidence', to='loans.repaymentscheduleallocation')),
            ],
            options={
                'db_table': 'interest_invoice_payment_evidence',
            },
        ),
        migrations.AddConstraint(
            model_name='interestcapitalisationhardcopytask',
            constraint=models.CheckConstraint(check=models.Q(('status', 'pending')), name='interest_cap_hard_copy_pending'),
        ),
        migrations.AddConstraint(
            model_name='interestcapitalisationpaymentevidence',
            constraint=models.CheckConstraint(check=models.Q(('interest_applied_amount__gt', 0)), name='interest_cap_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='interestcapitalisationscheduleevidence',
            constraint=models.CheckConstraint(check=models.Q(('interest_reclassified_amount__gt', 0)), name='interest_cap_schedule_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='interestinvoicepaymentevidence',
            constraint=models.CheckConstraint(check=models.Q(('interest_applied_amount__gt', 0)), name='interest_invoice_payment_positive'),
        ),
    ]
