# Generated by Django 5.0.6 on 2026-07-14 09:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_loandocument'),
        ('identity', '0003_portal_member_auth'),
        ('legal_documents', '0003_loan_document_renderer_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='notarisation_status',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='stamp_status',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='NotarisationRecord',
            fields=[
                ('notarisation_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notary_registration_number', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('notarised_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, max_length=60)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documentfile')),
                ('loan_document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='notarisation_record', to='legal_documents.loandocument')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.user')),
            ],
            options={
                'db_table': 'notarisation_records',
            },
        ),
        migrations.CreateModel(
            name='StampDutyRecord',
            fields=[
                ('stamp_duty_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stamp_paper_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('stamp_type', models.CharField(max_length=60)),
                ('stamp_number', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('stamp_purchase_date', models.DateField(blank=True, null=True)),
                ('executed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, max_length=60)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stamp_duty_record', to='legal_documents.loandocument')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.user')),
            ],
            options={
                'db_table': 'stamp_duty_records',
            },
        ),
        migrations.AddConstraint(
            model_name='notarisationrecord',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'completed', 'rejected'])), name='notary_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='notarisationrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'completed'), _negated=True), models.Q(('evidence_document__isnull', False), ('notarised_date__isnull', False), ('notary_name__isnull', False), ('notary_registration_number__isnull', False), ('verified_by_user__isnull', False)), _connector='OR'), name='completed_notary_has_evidence_verifier'),
        ),
        migrations.AddConstraint(
            model_name='stampdutyrecord',
            constraint=models.CheckConstraint(check=models.Q(('stamp_paper_amount__gte', 0)), name='stamp_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stampdutyrecord',
            constraint=models.CheckConstraint(check=models.Q(('stamp_type__in', ['physical', 'electronic'])), name='stamp_type_bounded'),
        ),
        migrations.AddConstraint(
            model_name='stampdutyrecord',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'adequate', 'insufficient'])), name='stamp_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='stampdutyrecord',
            constraint=models.CheckConstraint(check=models.Q(('stamp_purchase_date__isnull', True), ('executed_date__isnull', True), ('stamp_purchase_date__lte', models.F('executed_date')), _connector='OR'), name='stamp_purchase_not_after_execution'),
        ),
        migrations.AddConstraint(
            model_name='stampdutyrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'adequate'), _negated=True), models.Q(('executed_date__isnull', False), ('verified_by_user__isnull', False)), _connector='OR'), name='adequate_stamp_has_execution_verifier'),
        ),
    ]
