# Generated by Django 5.0.6 on 2026-07-14 09:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_loandocument'),
        ('identity', '0003_portal_member_auth'),
        ('legal_documents', '0004_checklistitem_notarisation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('signature_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_party_type', models.CharField(max_length=80)),
                ('signer_party_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('signer_name_snapshot', models.CharField(max_length=255)),
                ('signature_method', models.CharField(max_length=60)),
                ('signature_status', models.CharField(db_index=True, max_length=60)),
                ('signature_mismatch_flag', models.BooleanField(default=False)),
                ('mismatch_resolution_type', models.CharField(blank=True, max_length=80, null=True)),
                ('mismatch_resolution_remarks', models.TextField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_records', to='legal_documents.loandocument')),
                ('mismatch_resolution_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signature_mismatch_resolutions', to='documents.documentfile')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.user')),
            ],
            options={
                'db_table': 'signature_records',
                'indexes': [models.Index(fields=['loan_document', 'signature_status'], name='idx_signature_doc_status'), models.Index(fields=['signer_party_type', 'signer_party_id'], name='idx_signature_signer')],
            },
        ),
        migrations.AddConstraint(
            model_name='signaturerecord',
            constraint=models.UniqueConstraint(fields=('loan_document', 'signer_party_type', 'signer_party_id'), name='unique_signature_document_signer'),
        ),
        migrations.AddConstraint(
            model_name='signaturerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('signer_party_id__isnull', True)), fields=('loan_document', 'signer_party_type'), name='unique_signature_null_signer'),
        ),
        migrations.AddConstraint(
            model_name='signaturerecord',
            constraint=models.CheckConstraint(check=models.Q(('signer_party_type__in', ['borrower', 'nominee', 'witness', 'user'])), name='signature_party_type_bounded'),
        ),
        migrations.AddConstraint(
            model_name='signaturerecord',
            constraint=models.CheckConstraint(check=models.Q(('signature_method__in', ['wet_ink', 'digital', 'scanned'])), name='signature_method_bounded'),
        ),
        migrations.AddConstraint(
            model_name='signaturerecord',
            constraint=models.CheckConstraint(check=models.Q(('signature_status__in', ['pending', 'signed', 'mismatch'])), name='signature_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='signaturerecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mismatch_resolution_document__isnull', True), ('mismatch_resolution_remarks__isnull', True), ('mismatch_resolution_type__isnull', True)), models.Q(('mismatch_resolution_document__isnull', False), ('mismatch_resolution_type__in', ['bank_verification_letter', 'borrower_declaration']), ('signature_mismatch_flag', True), ('signature_status', 'mismatch'), ('verified_at__isnull', False), ('verified_by_user__isnull', False)), _connector='OR'), name='signature_resolution_complete'),
        ),
        migrations.AddConstraint(
            model_name='signaturerecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mismatch_resolution_type__isnull', True), ('signature_mismatch_flag', False), ('signature_status', 'pending'), ('signed_at__isnull', True)), models.Q(('signature_mismatch_flag', False), ('signature_status', 'signed'), ('signed_at__isnull', False)), models.Q(('signature_mismatch_flag', True), ('signature_status', 'mismatch')), _connector='OR'), name='signature_status_facts_consistent'),
        ),
    ]
