# Generated by Django 5.0.6 on 2026-07-14 12:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_loanapplication_nominee'),
        ('identity', '0003_portal_member_auth'),
        ('legal_documents', '0007_signature_capture_maker'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='poa_execution_status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='poa_status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='SecurityPackage',
            fields=[
                ('security_package_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_account_id', models.UUIDField(blank=True, null=True)),
                ('security_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('physical_share_security_required_flag', models.BooleanField(default=False)),
                ('demat_pledge_required_flag', models.BooleanField(default=False)),
                ('poa_required_flag', models.BooleanField(default=True)),
                ('blank_cheque_required_flag', models.BooleanField(default=False)),
                ('cancelled_cheque_required_flag', models.BooleanField(default=False)),
                ('security_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='security_package', to='applications.loanapplication')),
            ],
            options={
                'db_table': 'security_packages',
            },
        ),
        migrations.CreateModel(
            name='PowerOfAttorney',
            fields=[
                ('power_of_attorney_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose_summary', models.TextField()),
                ('execution_status', models.CharField(db_index=True, max_length=60)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, max_length=60)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attorney_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attorney_appointments', to='identity.user')),
                ('borrower_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powers_of_attorney', to='members.member')),
                ('loan_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powers_of_attorney', to='legal_documents.loandocument')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powers_of_attorney', to='members.nominee')),
                ('notarisation_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powers_of_attorney', to='legal_documents.notarisationrecord')),
                ('prepared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_powers_of_attorney', to='identity.user')),
                ('stamp_duty_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powers_of_attorney', to='legal_documents.stampdutyrecord')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_powers_of_attorney', to='identity.user')),
                ('security_package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='power_of_attorney', to='legal_documents.securitypackage')),
            ],
            options={
                'db_table': 'power_of_attorneys',
            },
        ),
        migrations.AddIndex(
            model_name='securitypackage',
            index=models.Index(fields=['loan_application', 'security_status'], name='idx_security_pkg_app_status'),
        ),
        migrations.AddConstraint(
            model_name='securitypackage',
            constraint=models.CheckConstraint(check=models.Q(('security_status__in', ['pending', 'complete', 'released'])), name='security_package_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='securitypackage',
            constraint=models.CheckConstraint(check=models.Q(('loan_account_id__isnull', True)), name='security_package_account_requires_009c'),
        ),
        migrations.AddConstraint(
            model_name='securitypackage',
            constraint=models.CheckConstraint(check=models.Q(('poa_required_flag', True)), name='security_package_poa_always_required'),
        ),
        migrations.AddIndex(
            model_name='powerofattorney',
            index=models.Index(fields=['execution_status', 'status'], name='idx_poa_exec_status'),
        ),
        migrations.AddIndex(
            model_name='powerofattorney',
            index=models.Index(fields=['borrower_member', 'nominee'], name='idx_poa_parties'),
        ),
        migrations.AddConstraint(
            model_name='powerofattorney',
            constraint=models.CheckConstraint(check=models.Q(('execution_status__in', ['pending', 'executed'])), name='poa_execution_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='powerofattorney',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['draft', 'active'])), name='poa_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='powerofattorney',
            constraint=models.CheckConstraint(check=models.Q(('released_at__isnull', True)), name='poa_release_requires_later_slice'),
        ),
        migrations.AddConstraint(
            model_name='powerofattorney',
            constraint=models.CheckConstraint(check=models.Q(('status', 'draft'), models.Q(('effective_from__isnull', False), ('execution_status', 'executed'), ('status', 'active'), ('verified_by_user__isnull', False)), _connector='OR'), name='active_poa_has_execution_verifier'),
        ),
    ]
