# Generated by Django 5.0.6 on 2026-07-14 21:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_portal_member_auth'),
        ('legal_documents', '0010_stage4_maker_checker_constraints'),
        ('workflows', '0001_canonical_workflow_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistAction',
            fields=[
                ('checklist_action_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_index=True, max_length=80)),
                ('meaning', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('actor_user_name_snapshot', models.CharField(max_length=200)),
                ('canonical_role_code', models.CharField(max_length=80)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'checklist_actions',
                'ordering': ['signed_at', 'checklist_action_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='documentchecklist',
            name='document_checklist_valid_status',
        ),
        migrations.RemoveConstraint(
            model_name='documentchecklist',
            name='checklist_signatures_require_008k',
        ),
        migrations.RemoveField(
            model_name='documentchecklist',
            name='company_secretary_signature_id',
        ),
        migrations.RemoveField(
            model_name='documentchecklist',
            name='credit_manager_signature_id',
        ),
        migrations.RemoveField(
            model_name='documentchecklist',
            name='sanction_committee_signature_id',
        ),
        migrations.RemoveField(
            model_name='documentchecklist',
            name='senior_manager_finance_signature_id',
        ),
        migrations.AddField(
            model_name='checklistaction',
            name='actor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_actions', to='identity.user'),
        ),
        migrations.AddField(
            model_name='checklistaction',
            name='checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completion_actions', to='legal_documents.checklistitem'),
        ),
        migrations.AddField(
            model_name='checklistaction',
            name='document_checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='legal_documents.documentchecklist'),
        ),
        migrations.AddField(
            model_name='checklistaction',
            name='loan_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_actions', to='legal_documents.loandocument'),
        ),
        migrations.AddField(
            model_name='checklistaction',
            name='workflow_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_action', to='workflows.workflowevent'),
        ),
        migrations.AddField(
            model_name='documentchecklist',
            name='company_secretary_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_secretary_checklists', to='legal_documents.checklistaction'),
        ),
        migrations.AddField(
            model_name='documentchecklist',
            name='credit_manager_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_manager_checklists', to='legal_documents.checklistaction'),
        ),
        migrations.AddField(
            model_name='documentchecklist',
            name='sanction_committee_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanction_committee_checklists', to='legal_documents.checklistaction'),
        ),
        migrations.AddField(
            model_name='documentchecklist',
            name='senior_manager_finance_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='senior_manager_finance_checklists', to='legal_documents.checklistaction'),
        ),
        migrations.AddConstraint(
            model_name='documentchecklist',
            constraint=models.CheckConstraint(check=models.Q(('checklist_status__in', ['in_progress', 'cs_approved', 'credit_approved', 'sanction_approved', 'ready'])), name='document_checklist_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='documentchecklist',
            constraint=models.CheckConstraint(check=models.Q(('credit_manager_signature_id__isnull', True), ('company_secretary_signature_id__isnull', False), _connector='OR'), name='checklist_credit_requires_cs'),
        ),
        migrations.AddConstraint(
            model_name='documentchecklist',
            constraint=models.CheckConstraint(check=models.Q(('sanction_committee_signature_id__isnull', True), ('credit_manager_signature_id__isnull', False), _connector='OR'), name='checklist_sanction_requires_credit'),
        ),
        migrations.AddConstraint(
            model_name='documentchecklist',
            constraint=models.CheckConstraint(check=models.Q(('senior_manager_finance_signature_id__isnull', True)), name='checklist_finance_requires_epic_009'),
        ),
        migrations.AddIndex(
            model_name='checklistaction',
            index=models.Index(fields=['document_checklist', 'action_type'], name='idx_check_action_stage'),
        ),
        migrations.AddConstraint(
            model_name='checklistaction',
            constraint=models.UniqueConstraint(condition=models.Q(('action_type', 'item_completion')), fields=('checklist_item',), name='unique_checklist_item_completion'),
        ),
        migrations.AddConstraint(
            model_name='checklistaction',
            constraint=models.UniqueConstraint(condition=models.Q(('action_type', 'item_completion'), _negated=True), fields=('document_checklist', 'action_type'), name='unique_checklist_approval_stage'),
        ),
        migrations.AddConstraint(
            model_name='checklistaction',
            constraint=models.CheckConstraint(check=models.Q(('action_type__in', ['item_completion', 'company_secretary_approval', 'credit_manager_approval', 'sanction_committee_approval', 'disbursement_signature'])), name='checklist_action_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='checklistaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action_type', 'item_completion'), ('checklist_item__isnull', False), ('loan_document__isnull', False)), models.Q(models.Q(('action_type', 'item_completion'), _negated=True), ('checklist_item__isnull', True), ('loan_document__isnull', True)), _connector='OR'), name='checklist_action_target_consistent'),
        ),
        migrations.AddConstraint(
            model_name='checklistaction',
            constraint=models.CheckConstraint(check=models.Q(('action_type', 'item_completion'), models.Q(('comments__isnull', False), models.Q(('comments', ''), _negated=True)), _connector='OR'), name='checklist_approval_comments_required'),
        ),
    ]
