# Generated by Django 5.0.6 on 2026-07-14 16:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_witness'),
        ('identity', '0003_portal_member_auth'),
        ('legal_documents', '0010_stage4_maker_checker_constraints'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
        ('security_instruments', '0001_transfer_security_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SH4ShareTransferForm',
            fields=[
                ('sh4_share_transfer_form_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_count', models.PositiveIntegerField(blank=True, null=True)),
                ('form_status', models.CharField(db_index=True, max_length=60)),
                ('custody_location', models.CharField(blank=True, max_length=255, null=True)),
                ('signed_at', models.DateField(blank=True, null=True)),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('invocation_approval_case_id', models.UUIDField(blank=True, null=True)),
                ('custody_evidence_json', models.JSONField(blank=True, default=dict)),
                ('custody_workflow_event_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('custodian_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodied_sh4_forms', to='identity.user')),
                ('loan_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sh4_share_transfer_forms', to='legal_documents.loandocument')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sh4_share_transfer_forms', to='members.member')),
                ('prepared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_sh4_forms', to='identity.user')),
                ('security_package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sh4_share_transfer_form', to='security_instruments.securitypackage')),
                ('shareholding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sh4_share_transfer_forms', to='members.shareholding')),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sh4_share_transfer_forms', to='applications.witness')),
            ],
            options={
                'db_table': 'sh4_share_transfer_forms',
                'indexes': [models.Index(fields=['form_status', 'signed_at'], name='idx_sh4_status_signed'), models.Index(fields=['member', 'witness'], name='idx_sh4_parties')],
            },
        ),
        migrations.AddConstraint(
            model_name='sh4sharetransferform',
            constraint=models.CheckConstraint(check=models.Q(('form_status__in', ['held_in_custody', 'pending', 'signed'])), name='sh4_form_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='sh4sharetransferform',
            constraint=models.CheckConstraint(check=models.Q(('share_count__isnull', True), ('share_count__gt', 0), _connector='OR'), name='sh4_share_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='sh4sharetransferform',
            constraint=models.CheckConstraint(check=models.Q(('returned_at__isnull', True)), name='sh4_return_requires_later_slice'),
        ),
        migrations.AddConstraint(
            model_name='sh4sharetransferform',
            constraint=models.CheckConstraint(check=models.Q(('invocation_approval_case_id__isnull', True)), name='sh4_invocation_requires_later_slice'),
        ),
        migrations.AddConstraint(
            model_name='sh4sharetransferform',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('custodian_user__isnull', True), ('custody_location__isnull', True), ('custody_workflow_event_id__isnull', True), ('form_status', 'pending'), ('signed_at__isnull', True)), models.Q(('custodian_user__isnull', True), ('custody_location__isnull', True), ('custody_workflow_event_id__isnull', True), ('form_status', 'signed'), ('signed_at__isnull', False)), models.Q(('custodian_user__isnull', False), ('custody_location__isnull', False), ('custody_workflow_event_id__isnull', False), ('form_status', 'held_in_custody'), ('signed_at__isnull', False)), _connector='OR'), name='sh4_status_evidence_consistent'),
        ),
    ]
