# Generated by Django 5.0.6 on 2026-07-14 17:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [('documents', '0004_loandocument'), ('identity', '0003_portal_member_auth'), ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'), ('security_instruments', '0002_sh4sharetransferform_and_more')]

    operations = [
        migrations.CreateModel(
            name='CDSLSharePledge',
            fields=[
                ('cdsl_share_pledge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pledgee_entity_name', models.CharField(max_length=255)),
                ('pledgor_bo_account_encrypted', models.TextField()),
                ('pledgor_bo_account_hash', models.CharField(db_index=True, max_length=128)),
                ('pledgee_bo_account_encrypted', models.TextField(blank=True, null=True)),
                ('pledgee_bo_account_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('pledgor_dp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pledgee_dp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prf_status', models.CharField(db_index=True, max_length=60)),
                ('pledge_sequence_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('pledge_acceptance_status', models.CharField(db_index=True, max_length=60)),
                ('pledged_share_count', models.PositiveIntegerField(blank=True, null=True)),
                ('agreement_number', models.CharField(blank=True, max_length=120, null=True)),
                ('pledge_status', models.CharField(db_index=True, max_length=60)),
                ('future_shares_pledged_flag', models.BooleanField(default=True)),
                ('created_at_cdsl', models.DateTimeField(blank=True, null=True)),
                ('invoked_at', models.DateTimeField(blank=True, null=True)),
                ('unpledged_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_evidence_json', models.JSONField(blank=True, default=dict)),
                ('acceptance_workflow_event_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cdsl_share_pledges', to='documents.documentfile')),
                ('pledgor_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cdsl_share_pledges', to='members.member')),
                ('prepared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_cdsl_pledges', to='identity.user')),
                ('security_package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cdsl_share_pledge', to='security_instruments.securitypackage')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_cdsl_pledges', to='identity.user')),
            ],
            options={'db_table': 'cdsl_share_pledges', 'indexes': [models.Index(fields=['prf_status', 'pledge_acceptance_status'], name='idx_cdsl_prf_accept'), models.Index(fields=['pledge_status', 'created_at_cdsl'], name='idx_cdsl_status_created')]},
        ),
        migrations.AddConstraint(model_name='cdslsharepledge', constraint=models.CheckConstraint(check=models.Q(('prf_status__in', ['prepared', 'submitted'])), name='cdsl_prf_status_bounded')),
        migrations.AddConstraint(model_name='cdslsharepledge', constraint=models.CheckConstraint(check=models.Q(('pledge_acceptance_status__in', ['pending', 'accepted', 'rejected'])), name='cdsl_accept_status_bounded')),
        migrations.AddConstraint(model_name='cdslsharepledge', constraint=models.CheckConstraint(check=models.Q(('pledge_status__in', ['pending', 'created'])), name='cdsl_pledge_status_bounded')),
        migrations.AddConstraint(model_name='cdslsharepledge', constraint=models.CheckConstraint(check=models.Q(('pledged_share_count__isnull', True), ('pledged_share_count__gt', 0), _connector='OR'), name='cdsl_share_count_positive')),
        migrations.AddConstraint(model_name='cdslsharepledge', constraint=models.CheckConstraint(check=models.Q(('future_shares_pledged_flag', True)), name='cdsl_future_shares_pledged')),
        migrations.AddConstraint(model_name='cdslsharepledge', constraint=models.CheckConstraint(check=models.Q(('invoked_at__isnull', True)), name='cdsl_invocation_requires_011i')),
        migrations.AddConstraint(model_name='cdslsharepledge', constraint=models.CheckConstraint(check=models.Q(('unpledged_at__isnull', True)), name='cdsl_unpledge_requires_011i')),
        migrations.AddConstraint(model_name='cdslsharepledge', constraint=models.CheckConstraint(check=models.Q(('verified_by_user__isnull', True), models.Q(('verified_by_user', models.F('prepared_by_user')), _negated=True), _connector='OR'), name='cdsl_distinct_maker_checker')),
        migrations.AddConstraint(model_name='cdslsharepledge', constraint=models.CheckConstraint(check=models.Q(models.Q(('acceptance_workflow_event_id__isnull', True), ('created_at_cdsl__isnull', True), ('pledge_acceptance_status', 'pending'), ('pledge_status', 'pending'), ('verified_by_user__isnull', True)), models.Q(('acceptance_workflow_event_id__isnull', False), ('agreement_number__isnull', False), ('created_at_cdsl__isnull', False), ('evidence_document__isnull', False), ('pledge_acceptance_status', 'accepted'), ('pledge_sequence_number__isnull', False), ('pledge_status', 'created'), ('pledged_share_count__isnull', False), ('pledgee_bo_account_encrypted__isnull', False), ('pledgee_dp_name__isnull', False), ('pledgor_dp_name__isnull', False), ('prf_status', 'submitted'), ('verified_by_user__isnull', False)), models.Q(('acceptance_workflow_event_id__isnull', False), ('created_at_cdsl__isnull', True), ('evidence_document__isnull', False), ('pledge_acceptance_status', 'rejected'), ('pledge_sequence_number__isnull', False), ('pledge_status', 'pending'), ('pledgee_bo_account_encrypted__isnull', False), ('pledgee_dp_name__isnull', False), ('pledgor_dp_name__isnull', False), ('prf_status', 'submitted'), ('verified_by_user__isnull', False)), _connector='OR'), name='cdsl_terminal_evidence_consistent')),
    ]
