# Generated by Django 5.0.6 on 2026-07-14 20:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_loandocument'),
        ('identity', '0003_portal_member_auth'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
        ('security_instruments', '0004_migrate_cdsl_field_encryption'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankDatedCheque',
            fields=[
                ('blank_dated_cheque_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cheque_number_encrypted', models.TextField()),
                ('cheque_number_hash', models.CharField(max_length=128, unique=True)),
                ('cheque_status', models.CharField(db_index=True, max_length=60)),
                ('custody_location', models.CharField(blank=True, max_length=255, null=True)),
                ('collected_at', models.DateField()),
                ('custody_evidence_json', models.JSONField(blank=True, default=dict)),
                ('custody_workflow_event_id', models.UUIDField(blank=True, null=True)),
                ('invocation_approval_case_id', models.UUIDField(blank=True, null=True)),
                ('presented_date', models.DateField(blank=True, null=True)),
                ('amount_presented', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blank_dated_cheques', to='members.bankaccount')),
                ('cancelled_cheque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blank_dated_security_cheques', to='members.cancelledcheque')),
                ('custodian_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodied_blank_cheques', to='identity.user')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blank_dated_cheques', to='documents.documentfile')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blank_dated_cheques', to='members.member')),
                ('prepared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_blank_cheques', to='identity.user')),
                ('security_package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blank_dated_cheque', to='security_instruments.securitypackage')),
            ],
            options={
                'db_table': 'blank_dated_cheques',
                'indexes': [models.Index(fields=['cheque_status', 'collected_at'], name='idx_blank_cheque_status'), models.Index(fields=['member', 'bank_account'], name='idx_blank_cheque_bank')],
            },
        ),
        migrations.AddConstraint(
            model_name='blankdatedcheque',
            constraint=models.CheckConstraint(check=models.Q(('cheque_status__in', ['collected', 'held'])), name='blank_cheque_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='blankdatedcheque',
            constraint=models.CheckConstraint(check=models.Q(('invocation_approval_case_id__isnull', True)), name='blank_cheque_invocation_requires_later'),
        ),
        migrations.AddConstraint(
            model_name='blankdatedcheque',
            constraint=models.CheckConstraint(check=models.Q(('presented_date__isnull', True), ('amount_presented__isnull', True)), name='blank_cheque_presentment_requires_later'),
        ),
        migrations.AddConstraint(
            model_name='blankdatedcheque',
            constraint=models.CheckConstraint(check=models.Q(('returned_at__isnull', True)), name='blank_cheque_return_requires_later'),
        ),
        migrations.AddConstraint(
            model_name='blankdatedcheque',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cheque_status', 'collected'), ('custodian_user__isnull', True), ('custody_location__isnull', True), ('custody_workflow_event_id__isnull', True)), models.Q(('cheque_status', 'held'), ('custodian_user__isnull', False), ('custody_location__isnull', False), ('custody_workflow_event_id__isnull', False)), _connector='OR'), name='blank_cheque_custody_consistent'),
        ),
        migrations.AddConstraint(
            model_name='blankdatedcheque',
            constraint=models.CheckConstraint(check=models.Q(('custodian_user__isnull', True), models.Q(('custodian_user', models.F('prepared_by_user')), _negated=True), _connector='OR'), name='blank_cheque_distinct_maker_checker'),
        ),
    ]
