# Generated by Ralph slice 003J.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("job_type", models.CharField(db_index=True, max_length=120)),
                (
                    "status",
                    models.CharField(default="queued", db_index=True, max_length=40),
                ),
                ("due_at", models.DateTimeField(db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_entity_type",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "related_entity_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "scheduled_jobs",
                "ordering": ["due_at", "job_id"],
            },
        ),
        migrations.AddIndex(
            model_name="scheduledjob",
            index=models.Index(
                fields=["status", "due_at"], name="scheduled_j_status_c9e5df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledjob",
            index=models.Index(
                fields=["related_entity_type", "related_entity_id"],
                name="scheduled_j_related_b1389d_idx",
            ),
        ),
    ]
