# Generated by Django 5.0.6 on 2026-07-02 11:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=80, unique=True)),
                ('role_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('status', models.CharField(db_index=True, default='active', max_length=40)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_code', models.CharField(max_length=80, unique=True)),
                ('team_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=40)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=40)),
                ('approval_authority_type', models.CharField(blank=True, max_length=80)),
                ('password_hash', models.CharField(max_length=256)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_users', to='identity.user')),
                ('primary_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.role')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_users', to='identity.user')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(default='user', max_length=60)),
                ('action', models.CharField(db_index=True, max_length=150)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('old_value_json', models.JSONField(blank=True, null=True)),
                ('new_value_json', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='identity.user')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('user_session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(max_length=128)),
                ('session_status', models.CharField(db_index=True, default='active', max_length=40)),
                ('ip_address', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='identity.user')),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserTeamMembership',
            fields=[
                ('user_team_membership_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_role', models.CharField(default='member', max_length=80)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=40)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='identity.user')),
            ],
            options={
                'db_table': 'user_team_memberships',
            },
        ),
        migrations.AddConstraint(
            model_name='userteammembership',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='unique_user_team_membership'),
        ),
    ]
