# Generated by Django 5.0.6 on 2026-07-09 16:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_permission_rolepermission_and_more'),
        ('members', '0008_cancelledcheque_bankaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccount',
            fields=[
                ('portal_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='invited', max_length=40)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('otp_login_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_account', to='members.member')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_account', to='identity.user')),
            ],
            options={
                'db_table': 'portal_accounts',
            },
        ),
        migrations.CreateModel(
            name='PortalOtpChallenge',
            fields=[
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(db_index=True, max_length=40)),
                ('contact', models.CharField(max_length=255)),
                ('otp_hash', models.CharField(max_length=128)),
                ('status', models.CharField(db_index=True, default='pending', max_length=40)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_otp_challenges', to='members.member')),
                ('portal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otp_challenges', to='identity.portalaccount')),
            ],
            options={
                'db_table': 'portal_otp_challenges',
                'indexes': [models.Index(fields=['purpose', 'status'], name='idx_portal_otp_purpose_status'), models.Index(fields=['member', 'purpose'], name='idx_portal_otp_member_purpose')],
            },
        ),
    ]
