# Generated by Django 5.0.6 on 2026-07-09 11:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_permission_rolepermission_and_more'),
        ('members', '0008_cancelledcheque_bankaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('loan_application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_reference_number', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('borrower_type', models.CharField(db_index=True, max_length=60)),
                ('application_channel', models.CharField(default='assisted_digital', max_length=60)),
                ('application_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('required_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('requested_tenure_months', models.PositiveIntegerField(blank=True, null=True)),
                ('declared_purpose', models.TextField(blank=True)),
                ('purpose_category', models.CharField(blank=True, db_index=True, max_length=80)),
                ('loan_type_requested', models.CharField(blank=True, max_length=60)),
                ('borrower_request_notes', models.TextField(blank=True)),
                ('current_stage', models.CharField(db_index=True, default='initial_loan_request', max_length=80)),
                ('application_status', models.CharField(db_index=True, default='draft', max_length=80)),
                ('completeness_status', models.CharField(db_index=True, default='not_started', max_length=60)),
                ('terms_acceptance_flag', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='members.bankaccount')),
                ('cancelled_cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='members.cancelledcheque')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_loan_applications', to='identity.user')),
                ('crop_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='members.cropplan')),
                ('land_holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='members.landholding')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='members.member')),
                ('received_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_loan_applications', to='identity.user')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_loan_applications', to='identity.user')),
            ],
            options={
                'db_table': 'loan_applications',
                'indexes': [models.Index(fields=['application_status', 'current_stage'], name='idx_loan_apps_status_stage'), models.Index(fields=['member'], name='idx_loan_apps_member'), models.Index(fields=['application_date'], name='idx_loan_apps_app_date'), models.Index(fields=['application_reference_number'], name='idx_loan_apps_reference')],
            },
        ),
        migrations.AddConstraint(
            model_name='loanapplication',
            constraint=models.CheckConstraint(check=models.Q(('required_loan_amount__isnull', True), ('required_loan_amount__gt', 0), _connector='OR'), name='loan_apps_positive_required_amount'),
        ),
    ]
