# Generated by Django 5.0.6 on 2026-07-09 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('identity', '0002_permission_rolepermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='submitted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_loan_applications', to='identity.user'),
        ),
    ]
