# Generated by Django 5.0.6 on 2026-07-09 13:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_loanapplication_submitted_by_user'),
        ('identity', '0002_permission_rolepermission_and_more'),
        ('members', '0008_cancelledcheque_bankaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSequence',
            fields=[
                ('system_sequence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_code', models.CharField(max_length=80, unique=True)),
                ('prefix', models.CharField(max_length=20)),
                ('current_value', models.BigIntegerField(default=0)),
                ('padding_length', models.PositiveIntegerField(default=8)),
                ('last_generated_value', models.CharField(blank=True, max_length=80, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'system_sequences',
            },
        ),
        migrations.CreateModel(
            name='LoanRequestRegisterEntry',
            fields=[
                ('loan_request_register_entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_reference_number', models.CharField(db_index=True, max_length=40)),
                ('date_received', models.DateField(db_index=True)),
                ('reference_generated_date', models.DateField(db_index=True)),
                ('received_channel', models.CharField(max_length=60)),
                ('register_status', models.CharField(db_index=True, default='reference_generated', max_length=60)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('declared_purpose', models.TextField(blank=True)),
                ('purpose_category', models.CharField(blank=True, db_index=True, max_length=80)),
                ('borrower_name', models.CharField(blank=True, max_length=255)),
                ('folio_number', models.CharField(blank=True, max_length=120)),
                ('member_type', models.CharField(blank=True, max_length=60)),
                ('current_stage', models.CharField(blank=True, db_index=True, max_length=80)),
                ('current_owner_role', models.CharField(blank=True, max_length=120)),
                ('eligibility_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('sanction_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('documentation_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('disbursement_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('original_copy_reference', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_request_register_entry', to='applications.loanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_request_register_entries', to='members.member')),
                ('received_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_loan_request_register_entries', to='identity.user')),
            ],
            options={
                'db_table': 'loan_request_register_entries',
                'indexes': [models.Index(fields=['register_status', 'current_stage'], name='idx_lrr_status_stage'), models.Index(fields=['date_received'], name='idx_lrr_date_received'), models.Index(fields=['reference_generated_date'], name='idx_lrr_ref_gen_date')],
            },
        ),
    ]
