# Generated by Django 5.0.6 on 2026-07-09 14:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_systemsequence_loanrequestregisterentry'),
        ('documents', '0001_initial'),
        ('identity', '0002_permission_rolepermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('application_document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(db_index=True, max_length=80)),
                ('party_type', models.CharField(db_index=True, max_length=40)),
                ('party_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('required_flag', models.BooleanField(default=True)),
                ('submission_status', models.CharField(db_index=True, default='submitted', max_length=40)),
                ('verification_status', models.CharField(db_index=True, default='pending', max_length=40)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_application_documents', to='identity.user')),
                ('document_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to='documents.documentfile')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to='applications.loanapplication')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_application_documents', to='identity.user')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_application_documents', to='identity.user')),
            ],
            options={
                'db_table': 'application_documents',
                'ordering': ['loan_application_id', 'document_type', 'party_type', 'party_id', 'version_number'],
                'indexes': [models.Index(fields=['loan_application', 'document_type'], name='idx_app_docs_app_type'), models.Index(fields=['loan_application', 'submission_status', 'verification_status'], name='idx_app_docs_statuses')],
            },
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(fields=('loan_application', 'document_type', 'party_type', 'party_id', 'version_number'), name='unique_app_doc_party_version'),
        ),
    ]
