# Generated by Django 5.0.6 on 2026-07-09 15:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationdocument_and_more'),
        ('identity', '0002_permission_rolepermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDeficiency',
            fields=[
                ('deficiency_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(db_index=True, max_length=100)),
                ('deficiency_type', models.CharField(db_index=True, max_length=100)),
                ('source_reason_code', models.CharField(db_index=True, max_length=80)),
                ('description', models.TextField()),
                ('remarks', models.TextField(blank=True)),
                ('resolution_status', models.CharField(db_index=True, default='open', max_length=60)),
                ('raised_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('communication_mode', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deficiencies', to='applications.loanapplication')),
                ('raised_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_application_deficiencies', to='identity.user')),
                ('resolved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_application_deficiencies', to='identity.user')),
            ],
            options={
                'db_table': 'deficiencies',
                'ordering': ['loan_application_id', 'item_code', 'raised_at', 'deficiency_id'],
                'indexes': [models.Index(fields=['loan_application', 'resolution_status'], name='idx_def_app_status'), models.Index(fields=['loan_application', 'item_code'], name='idx_def_app_item')],
            },
        ),
    ]
