# Generated by Ralph on 2026-07-10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_application_deficiency"),
        ("identity", "0002_permission_rolepermission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectionNote",
            fields=[
                (
                    "rejection_note_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rejection_stage", models.CharField(db_index=True, max_length=80)),
                (
                    "rejection_reason_category",
                    models.CharField(db_index=True, max_length=100),
                ),
                ("detailed_reason", models.TextField()),
                ("reapply_allowed_flag", models.BooleanField(default=True)),
                ("note_status", models.CharField(db_index=True, default="draft", max_length=40)),
                ("communication_mode", models.CharField(max_length=60)),
                ("communication_id", models.UUIDField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_rejection_notes",
                        to="identity.user",
                    ),
                ),
                (
                    "loan_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rejection_note",
                        to="applications.loanapplication",
                    ),
                ),
                (
                    "prepared_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_rejection_notes",
                        to="identity.user",
                    ),
                ),
                (
                    "sent_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_rejection_notes",
                        to="identity.user",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_rejection_notes",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "rejection_notes",
                "ordering": ["loan_application_id", "created_at", "rejection_note_id"],
                "indexes": [
                    models.Index(
                        fields=["loan_application", "note_status"],
                        name="idx_rej_note_app_status",
                    ),
                    models.Index(fields=["rejection_stage"], name="idx_rej_note_stage"),
                    models.Index(
                        fields=["rejection_reason_category"],
                        name="idx_rej_note_reason",
                    ),
                ],
            },
        ),
    ]
