# Generated by Django 5.0.6 on 2026-07-09 22:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_rejection_note'),
        ('identity', '0003_portal_member_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityAssessment',
            fields=[
                ('eligibility_assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_active_check', models.CharField(max_length=60)),
                ('default_check', models.CharField(default='pending', max_length=60)),
                ('document_check', models.CharField(default='pending', max_length=60)),
                ('terms_acceptance_check', models.CharField(default='pending', max_length=60)),
                ('purpose_check', models.CharField(default='pending', max_length=60)),
                ('nominee_check', models.CharField(default='pending', max_length=60)),
                ('overall_result', models.CharField(db_index=True, max_length=60)),
                ('assessment_notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_assessments', to='identity.user')),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_assessment', to='applications.loanapplication')),
            ],
            options={
                'db_table': 'eligibility_assessments',
                'indexes': [models.Index(fields=['overall_result'], name='idx_eligibility_result'), models.Index(fields=['assessed_at'], name='idx_eligibility_assessed_at')],
            },
        ),
    ]
