# Generated by Django 5.0.6 on 2026-07-10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_eligibilityassessment"),
        ("identity", "0003_portal_member_auth"),
        ("members", "0008_cancelledcheque_bankaccount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanLimitAssessment",
            fields=[
                (
                    "loan_limit_assessment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number_of_shares", models.IntegerField()),
                (
                    "valuation_per_share",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "share_limit_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "per_share_cap_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "shareholding_based_limit_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "land_area_acres",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "scale_of_finance_per_acre_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "land_based_limit_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "final_eligible_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("amount_within_limit_flag", models.BooleanField(db_index=True)),
                ("exception_required_flag", models.BooleanField(db_index=True)),
                ("calculation_rule_version", models.CharField(max_length=80)),
                (
                    "calculated_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "calculated_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_limit_assessments",
                        to="identity.user",
                    ),
                ),
                (
                    "loan_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_limit_assessment",
                        to="applications.loanapplication",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_limit_assessments",
                        to="members.member",
                    ),
                ),
                (
                    "shareholding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_limit_assessments",
                        to="members.shareholding",
                    ),
                ),
            ],
            options={"db_table": "loan_limit_assessments"},
        ),
    ]
