# Generated by Django 5.0.6 on 2026-07-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_loanlimitassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanlimitassessment',
            name='board_approval_reference_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loanlimitassessment',
            name='policy_config_id_snapshot',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanlimitassessment',
            name='policy_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
