# Generated by Django 5.0.6 on 2026-07-10 18:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_loanapplication_nominee'),
        ('identity', '0003_portal_member_auth'),
        ('members', '0008_cancelledcheque_bankaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('witness_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('witness_name', models.CharField(max_length=255)),
                ('pan_encrypted', models.TextField()),
                ('pan_hash', models.CharField(db_index=True, max_length=128)),
                ('aadhaar_encrypted', models.TextField()),
                ('aadhaar_hash', models.CharField(db_index=True, max_length=128)),
                ('shareholder_verified_flag', models.BooleanField(default=False)),
                ('verification_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='witnesses', to='applications.loanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_witnesses', to='members.member')),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_witnesses', to='identity.user')),
            ],
            options={
                'db_table': 'witnesses',
                'indexes': [models.Index(fields=['loan_application'], name='idx_witnesses_application'), models.Index(fields=['pan_hash'], name='idx_witnesses_pan_hash'), models.Index(fields=['aadhaar_hash'], name='idx_witnesses_aadhaar_hash')],
            },
        ),
    ]
