# Generated by Django 5.0.6 on 2026-07-15 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

from sfpcl_credit.shared.migration_operations import AddFieldToAppModel


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_applicationdeficiencyresponse'),
        ('configurations', '0002_version_history_approval_evidence'),
        ('documents', '0004_loandocument'),
        ('identity', '0003_portal_member_auth'),
        ('members', '0014_remove_memberscopeassignment_uniq_member_scope_assignment_and_more'),
        ('legal_documents', '0012_portal_documentation_submission'),
        ('workflows', '0001_canonical_workflow_event'),
    ]

    operations = [
        AddFieldToAppModel(
            target_app_label='legal_documents',
            model_name='checklistaction',
            name='audit_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_action', to='identity.auditlog'),
        ),
        AddFieldToAppModel(
            target_app_label='legal_documents',
            model_name='checklistaction',
            name='version_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_action', to='configurations.versionhistory'),
        ),
        migrations.CreateModel(
            name='BankVerificationDecision',
            fields=[
                ('bank_verification_decision_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cancelled_cheque_checksum_sha256', models.CharField(max_length=128)),
                ('bank_account_hash_snapshot', models.CharField(max_length=128)),
                ('ifsc_snapshot', models.CharField(max_length=20)),
                ('branch_name_snapshot', models.CharField(blank=True, max_length=150)),
                ('decision_status', models.CharField(db_index=True, max_length=60)),
                ('verifier_role_code', models.CharField(max_length=80)),
                ('verified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('request_id', models.CharField(max_length=255)),
                ('decision_version', models.PositiveIntegerField()),
                ('evidence_digest', models.CharField(max_length=64)),
                ('audit_log', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_verification_decision', to='identity.auditlog')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_decisions', to='members.bankaccount')),
                ('cancelled_cheque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_decisions', to='members.cancelledcheque')),
                ('cancelled_cheque_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_verification_decisions', to='documents.documentfile')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_verification_decisions', to='applications.loanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_verification_decisions', to='members.member')),
                ('verifier_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_verification_decisions', to='identity.user')),
                ('version_history', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_verification_decision', to='configurations.versionhistory')),
                ('workflow_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_verification_decision', to='workflows.workflowevent')),
            ],
            options={
                'db_table': 'bank_verification_decisions',
                'ordering': ['decision_version', 'bank_verification_decision_id'],
                'indexes': [models.Index(fields=['loan_application', 'decision_status', 'verified_at'], name='idx_bank_verify_app_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='bankverificationdecision',
            constraint=models.UniqueConstraint(fields=('loan_application', 'decision_version'), name='unique_bank_verify_app_version'),
        ),
        migrations.AddConstraint(
            model_name='bankverificationdecision',
            constraint=models.CheckConstraint(check=models.Q(('decision_status__in', ['verified', 'rejected'])), name='bank_verify_status_bounded'),
        ),
    ]
