# Generated by Django 5.0.6 on 2026-07-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_bankverificationdecision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankverificationdecision',
            name='approval_case_id_snapshot',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bankverificationdecision',
            name='sanction_decision_id_snapshot',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
