# Generated by Django 5.0.6 on 2026-07-22 20:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0013_exception_provider_vocabulary'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('compliance_control_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_code', models.CharField(max_length=120, unique=True)),
                ('control_name', models.CharField(max_length=255)),
                ('control_area', models.CharField(db_index=True, max_length=100)),
                ('legal_basis', models.TextField()),
                ('control_type', models.CharField(max_length=60)),
                ('frequency', models.CharField(db_index=True, max_length=60)),
                ('owner_role_code', models.CharField(max_length=100)),
                ('first_due_date', models.DateField(db_index=True)),
                ('evidence_required', models.TextField()),
                ('risk_if_missed', models.TextField()),
                ('status', models.CharField(db_index=True, default='active', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_compliance_controls', to='identity.user')),
                ('reviewer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_compliance_controls', to='identity.user')),
            ],
            options={
                'db_table': 'compliance_controls',
                'ordering': ['control_code'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceControlVersion',
            fields=[
                ('compliance_control_version_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot_json', models.JSONField()),
                ('change_reason', models.TextField()),
                ('effective_from', models.DateField()),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_control_versions', to='identity.user')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='compliance.compliancecontrol')),
            ],
            options={
                'db_table': 'compliance_control_versions',
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('compliance_evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(db_index=True, max_length=100)),
                ('summary', models.TextField()),
                ('source_owner', models.CharField(max_length=80)),
                ('source_entity_type', models.CharField(max_length=100)),
                ('source_entity_id', models.UUIDField()),
                ('source_period', models.CharField(db_index=True, max_length=40)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_status', models.CharField(db_index=True, default='pending', max_length=60)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence', to='documents.documentfile')),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_compliance_evidence', to='identity.user')),
                ('submitted_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_compliance_evidence', to='identity.user')),
            ],
            options={
                'db_table': 'compliance_evidence',
                'ordering': ['submitted_at', 'compliance_evidence_id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidenceReview',
            fields=[
                ('compliance_evidence_review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=60)),
                ('comments', models.TextField()),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_history', to='compliance.complianceevidence')),
                ('reviewed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence_reviews', to='identity.user')),
            ],
            options={
                'db_table': 'compliance_evidence_reviews',
            },
        ),
        migrations.CreateModel(
            name='ComplianceTask',
            fields=[
                ('compliance_task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_period', models.CharField(db_index=True, max_length=40)),
                ('due_date', models.DateField(db_index=True)),
                ('task_status', models.CharField(db_index=True, max_length=60)),
                ('remarks', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_compliance_tasks', to='identity.user')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='compliance.compliancecontrol')),
                ('current_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_tasks', to='compliance.complianceevidence')),
                ('due_notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_due_task', to='communications.notification')),
                ('overdue_notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_overdue_task', to='communications.notification')),
                ('reviewer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_tasks_to_review', to='identity.user')),
            ],
            options={
                'db_table': 'compliance_tasks',
                'ordering': ['due_date', 'compliance_task_id'],
            },
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_submissions', to='compliance.compliancetask'),
        ),
        migrations.CreateModel(
            name='MoneyLendingLawReview',
            fields=[
                ('money_lending_law_review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(db_index=True, max_length=20)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('applicability', models.CharField(max_length=40)),
                ('exemption_applicable_flag', models.BooleanField()),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('board_note_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='money_lending_board_notes', to='documents.documentfile')),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='money_lending_review', to='compliance.complianceevidence')),
                ('legal_opinion_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='money_lending_legal_opinions', to='documents.documentfile')),
                ('reviewed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='money_lending_reviews', to='identity.user')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='money_lending_review', to='compliance.compliancetask')),
            ],
            options={
                'db_table': 'money_lending_law_reviews',
            },
        ),
        migrations.AddConstraint(
            model_name='compliancecontrol',
            constraint=models.CheckConstraint(check=models.Q(('control_type__in', ('preventive', 'detective'))), name='compliance_control_type_bounded'),
        ),
        migrations.AddConstraint(
            model_name='compliancecontrol',
            constraint=models.CheckConstraint(check=models.Q(('frequency__in', ('monthly', 'quarterly', 'annual', 'ongoing'))), name='compliance_control_frequency_bounded'),
        ),
        migrations.AddConstraint(
            model_name='compliancecontrol',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('active', 'disabled'))), name='compliance_control_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='compliancecontrol',
            constraint=models.CheckConstraint(check=models.Q(('owner_user', models.F('reviewer_user')), _negated=True), name='compliance_control_maker_checker'),
        ),
        migrations.AddConstraint(
            model_name='compliancecontrolversion',
            constraint=models.UniqueConstraint(fields=('control', 'version_number'), name='uniq_compliance_control_version'),
        ),
        migrations.AddConstraint(
            model_name='complianceevidencereview',
            constraint=models.CheckConstraint(check=models.Q(('decision__in', ('accepted', 'rejected'))), name='compliance_evidence_review_decision_bounded'),
        ),
        migrations.AddIndex(
            model_name='compliancetask',
            index=models.Index(fields=['task_status', 'due_date'], name='compliance__task_st_fc1198_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancetask',
            constraint=models.UniqueConstraint(fields=('control', 'task_period'), name='uniq_compliance_control_period'),
        ),
        migrations.AddConstraint(
            model_name='compliancetask',
            constraint=models.CheckConstraint(check=models.Q(('task_status__in', ('due', 'overdue', 'evidence_submitted', 'completed'))), name='compliance_task_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='compliancetask',
            constraint=models.CheckConstraint(check=models.Q(('assigned_to_user', models.F('reviewer_user')), _negated=True), name='compliance_task_maker_checker'),
        ),
        migrations.AddConstraint(
            model_name='complianceevidence',
            constraint=models.CheckConstraint(check=models.Q(('review_status__in', ('pending', 'accepted', 'rejected'))), name='compliance_evidence_review_bounded'),
        ),
        migrations.AddConstraint(
            model_name='moneylendinglawreview',
            constraint=models.UniqueConstraint(fields=('financial_year', 'state'), name='uniq_money_lending_year_state'),
        ),
        migrations.AddConstraint(
            model_name='moneylendinglawreview',
            constraint=models.CheckConstraint(check=models.Q(('applicability__in', ('applicable', 'exempt'))), name='money_lending_applicability_bounded'),
        ),
    ]
