# Generated by Django 5.0.6 on 2026-07-23 00:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_statutory_trackers'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('members', '0015_member_aadhaar_last4'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCReview',
            fields=[
                ('kyc_review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(db_index=True, default='rekyc', max_length=80)),
                ('cycle_key', models.CharField(max_length=80)),
                ('source_verified_at', models.DateTimeField()),
                ('due_date', models.DateField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_verified_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_status_before', models.CharField(max_length=60)),
                ('kyc_status_after', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(db_index=True, max_length=60)),
                ('completeness_snapshot_json', models.JSONField(default=dict)),
                ('completion_evidence_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_reviews', to='members.kycprofile')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_reviews', to='members.member')),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_kyc_reviews', to='identity.user')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_review', to='compliance.compliancetask')),
            ],
            options={
                'db_table': 'kyc_reviews',
                'ordering': ['due_date', 'kyc_review_id'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='idx_kyc_review_status_due'), models.Index(fields=['member', 'due_date'], name='idx_kyc_review_member_due')],
            },
        ),
        migrations.AddConstraint(
            model_name='kycreview',
            constraint=models.UniqueConstraint(fields=('member', 'cycle_key'), name='uniq_kyc_review_member_cycle'),
        ),
        migrations.AddConstraint(
            model_name='kycreview',
            constraint=models.CheckConstraint(check=models.Q(('review_type__in', ('onboarding', 'rekyc'))), name='kyc_review_type_bounded'),
        ),
        migrations.AddConstraint(
            model_name='kycreview',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('pending', 'warning', 'due', 'overdue', 'completed'))), name='kyc_review_status_bounded'),
        ),
    ]
