# Generated by Django 5.0.6 on 2026-07-23 11:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_bank_decision_terminal_sanction_snapshots'),
        ('communications', '0013_exception_provider_vocabulary'),
        ('compliance', '0003_kyc_review_tracker'),
        ('defaults', '0004_non_payment_note'),
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('loans', '0009_dpd_pointer_integrity'),
        ('members', '0016_kyc_correction_request'),
        ('recovery', '0002_recovery_action_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('grievance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grievance_reference', models.CharField(max_length=40, unique=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('request_digest', models.CharField(max_length=64)),
                ('grievance_category', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('received_date', models.DateField(db_index=True)),
                ('received_channel', models.CharField(max_length=60)),
                ('resolution_due_date', models.DateField(db_index=True)),
                ('status', models.CharField(db_index=True, default='open', max_length=60)),
                ('internal_notes', models.TextField(blank=True)),
                ('resolution_summary', models.TextField(blank=True)),
                ('resolution_idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('resolution_request_digest', models.CharField(blank=True, max_length=64)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('borrower_informed_at', models.DateTimeField(blank=True, null=True)),
                ('borrower_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('borrower_acknowledgement', models.TextField(blank=True)),
                ('escalation_count', models.PositiveIntegerField(default=0)),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_role_code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_grievances', to='identity.user')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_grievances', to='identity.user')),
                ('default_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='defaults.defaultcase')),
                ('loan_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='loans.loanaccount')),
                ('loan_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='applications.loanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='members.member')),
                ('notice_communication', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievance_notice', to='communications.communication')),
                ('recovery_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='recovery.recoveryaction')),
                ('resolution_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_grievances', to='documents.documentfile')),
                ('resolved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_grievances', to='identity.user')),
            ],
            options={
                'db_table': 'grievances',
                'ordering': ['-received_date', '-created_at', '-grievance_id'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceDocument',
            fields=[
                ('grievance_document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=40)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grievance_links', to='documents.documentfile')),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_links', to='compliance.grievance')),
                ('linked_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_grievance_documents', to='identity.user')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grievance_document_links', to='members.member')),
            ],
            options={
                'db_table': 'grievance_documents',
            },
        ),
        migrations.AddField(
            model_name='grievance',
            name='supporting_documents',
            field=models.ManyToManyField(related_name='supporting_grievances', through='compliance.GrievanceDocument', to='documents.documentfile'),
        ),
        migrations.CreateModel(
            name='GrievanceHistory',
            fields=[
                ('grievance_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=80)),
                ('previous_status', models.CharField(blank=True, max_length=60)),
                ('new_status', models.CharField(max_length=60)),
                ('note', models.TextField(blank=True)),
                ('actor_role_code', models.CharField(max_length=100)),
                ('evidence_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievance_history_events', to='identity.user')),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='compliance.grievance')),
            ],
            options={
                'db_table': 'grievance_history',
                'ordering': ['sequence', 'grievance_history_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='grievancedocument',
            constraint=models.UniqueConstraint(fields=('grievance', 'document', 'purpose'), name='uniq_grievance_document_purpose'),
        ),
        migrations.AddConstraint(
            model_name='grievancedocument',
            constraint=models.CheckConstraint(check=models.Q(('purpose__in', ('supporting', 'resolution'))), name='grievance_document_purpose_bounded'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['member', 'status'], name='idx_grievance_member_status'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['assigned_to_user', 'status'], name='idx_grievance_owner_status'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['status', 'resolution_due_date'], name='idx_grievance_status_due'),
        ),
        migrations.AddConstraint(
            model_name='grievance',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('open', 'investigating', 'escalated', 'resolved'))), name='grievance_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='grievance',
            constraint=models.CheckConstraint(check=models.Q(('grievance_category__in', ('application_issue', 'document_issue', 'approval_delay', 'disbursement_delay', 'interest_charge_dispute', 'repayment_adjustment_issue', 'recovery_conduct_issue', 'noc_closure_delay', 'kyc_data_correction_issue', 'other'))), name='grievance_category_bounded'),
        ),
        migrations.AddConstraint(
            model_name='grievance',
            constraint=models.CheckConstraint(check=models.Q(('received_channel__in', ('portal', 'form', 'phone'))), name='grievance_channel_bounded'),
        ),
        migrations.AddConstraint(
            model_name='grievance',
            constraint=models.CheckConstraint(check=models.Q(('resolution_due_date__gte', models.F('received_date'))), name='grievance_due_after_received'),
        ),
        migrations.AddConstraint(
            model_name='grievance',
            constraint=models.CheckConstraint(check=models.Q(('description', ''), _negated=True), name='grievance_description_required'),
        ),
        migrations.AddConstraint(
            model_name='grievance',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('closed_at__isnull', False), ('resolved_by_user__isnull', False), ('status', 'resolved'), models.Q(('resolution_summary', ''), _negated=True)), models.Q(models.Q(('status', 'resolved'), _negated=True), ('closed_at__isnull', True), ('resolution_summary', ''), ('resolved_by_user__isnull', True)), _connector='OR'), name='grievance_resolution_complete'),
        ),
        migrations.AddConstraint(
            model_name='grievancehistory',
            constraint=models.UniqueConstraint(fields=('grievance', 'sequence'), name='uniq_grievance_history_sequence'),
        ),
        migrations.AddConstraint(
            model_name='grievancehistory',
            constraint=models.CheckConstraint(check=models.Q(('new_status__in', ('open', 'investigating', 'escalated', 'resolved'))), name='grievance_history_status_bounded'),
        ),
    ]
