# Generated by Ralph slice 003F.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "content_template_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_code", models.CharField(max_length=120, unique=True)),
                ("template_name", models.CharField(max_length=255)),
                ("template_type", models.CharField(db_index=True, max_length=60)),
                (
                    "language_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("audience", models.CharField(db_index=True, max_length=80)),
                (
                    "subject_template",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("body_template", models.TextField()),
                ("variables_json", models.JSONField(blank=True, null=True)),
                ("approval_status", models.CharField(db_index=True, max_length=60)),
                ("template_version", models.CharField(max_length=40)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "content_templates",
                "ordering": ["template_code"],
            },
        ),
    ]
