# Generated by Ralph slice 003I.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
        ("identity", "0002_permission_rolepermission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "communication_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("related_entity_type", models.CharField(max_length=80)),
                ("related_entity_id", models.UUIDField()),
                ("recipient_party_type", models.CharField(max_length=80)),
                (
                    "recipient_party_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "recipient_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("channel", models.CharField(max_length=40)),
                (
                    "subject_snapshot",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("body_snapshot", models.TextField()),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "delivery_status",
                    models.CharField(db_index=True, default="pending", max_length=40),
                ),
                (
                    "acknowledgement_status",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "external_message_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "content_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communications",
                        to="communications.contenttemplate",
                    ),
                ),
                (
                    "sent_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_communications",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "communications",
                "ordering": ["communication_id"],
                "indexes": [
                    models.Index(
                        fields=["related_entity_type", "related_entity_id"],
                        name="communicati_related_0b9a6e_idx",
                    )
                ],
            },
        ),
    ]
