# Generated by Django 5.0.6 on 2026-07-06 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_communication'),
        ('identity', '0002_permission_rolepermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(db_index=True, default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('related_entity_type', models.CharField(blank=True, max_length=80)),
                ('related_entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action_label', models.CharField(blank=True, max_length=80)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('recipient_role_code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('recipient_team_code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('read_state_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='communications.communication')),
                ('read_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='read_notifications', to='identity.user')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='identity.user')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_notifications', to='identity.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at', '-notification_id'],
                'indexes': [models.Index(fields=['recipient_user', 'read_at'], name='notificatio_recipie_92825f_idx'), models.Index(fields=['recipient_role_code', 'read_at'], name='notificatio_recipie_323033_idx'), models.Index(fields=['recipient_team_code', 'read_at'], name='notificatio_recipie_a92079_idx')],
            },
        ),
    ]
