# Generated by Django 5.0.6 on 2026-07-18 07:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

from sfpcl_credit.processes.advice_evidence_migration import (
    backfill_advice_evidence,
    reverse_advice_evidence,
)


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_advice_outbox_and_receipt_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationProviderAttempt',
            fields=[
                ('provider_attempt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advice_intent_id', models.UUIDField()),
                ('communication_id', models.UUIDField()),
                ('idempotency_key', models.CharField(max_length=255)),
                ('payload_digest', models.CharField(max_length=64)),
                ('adapter_kind', models.CharField(max_length=255)),
                ('outcome', models.CharField(max_length=20)),
                ('provider_external_message_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('provider_delivery_status', models.CharField(blank=True, max_length=40, null=True)),
                ('provider_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence_digest', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'communication_provider_attempts',
            },
        ),
        migrations.RemoveConstraint(
            model_name='communicationdeliveryoutbox',
            name='communication_outbox_complete',
        ),
        migrations.RemoveConstraint(
            model_name='communicationdeliveryoutbox',
            name='communication_outbox_provider_result_complete',
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='body_template_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='delivery_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_outbox', to='communications.disbursementadvicedeliveryreceipt'),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='final_communication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_delivery_outbox', to='communications.communication'),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='subject_template_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='template_approval_status_snapshot',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='template_audience_snapshot',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='template_effective_from_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='template_effective_to_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='template_language_code_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='template_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='template_provenance_status',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='template_type_snapshot',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='template_variables_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communicationdeliveryoutbox',
            name='advice_intent',
            field=models.UUIDField(db_column='advice_intent_id', unique=True),
        ),
        migrations.AlterField(
            model_name='disbursementadvicedeliveryreceipt',
            name='advice_intent',
            field=models.UUIDField(db_column='advice_intent_id', unique=True),
        ),
        migrations.AddField(
            model_name='communicationproviderattempt',
            name='outbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_attempts', to='communications.communicationdeliveryoutbox'),
        ),
        migrations.AddField(
            model_name='communicationdeliveryoutbox',
            name='accepted_provider_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_outbox', to='communications.communicationproviderattempt'),
        ),
        migrations.RunPython(backfill_advice_evidence, reverse_advice_evidence),
        migrations.AlterField(
            model_name='communicationdeliveryoutbox',
            name='template_provenance_status',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='communicationdeliveryoutbox',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('idempotency_key', ''), _negated=True), models.Q(('channel', ''), _negated=True), models.Q(('recipient_address', ''), _negated=True), models.Q(('recipient_digest', ''), _negated=True), models.Q(('template_code_snapshot', ''), _negated=True), ('template_provenance_status__in', ('verified', 'legacy_partial')), models.Q(('template_version_snapshot', ''), _negated=True), models.Q(('template_checksum_sha256', ''), _negated=True), models.Q(('subject_snapshot', ''), _negated=True), models.Q(('body_snapshot', ''), _negated=True), models.Q(('payload_digest', ''), _negated=True), models.Q(('related_entity_type', ''), _negated=True), ('delivery_status__in', ('pending', 'sent'))), name='communication_outbox_complete'),
        ),
        migrations.AddConstraint(
            model_name='communicationdeliveryoutbox',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('body_template_snapshot__isnull', False), ('subject_template_snapshot__isnull', False), ('template_approval_status_snapshot__isnull', False), ('template_audience_snapshot__isnull', False), ('template_effective_from_snapshot__isnull', False), ('template_name_snapshot__isnull', False), ('template_provenance_status', 'verified'), ('template_type_snapshot__isnull', False), ('template_variables_snapshot__isnull', False)), ('template_provenance_status', 'legacy_partial'), _connector='OR'), name='communication_outbox_provenance_complete'),
        ),
        migrations.AddConstraint(
            model_name='communicationdeliveryoutbox',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('delivery_receipt__isnull', True), ('final_communication__isnull', True)), models.Q(('delivery_receipt__isnull', False), ('final_communication__isnull', False)), _connector='OR'), name='communication_outbox_final_chain_complete'),
        ),
        migrations.AddConstraint(
            model_name='communicationdeliveryoutbox',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('accepted_provider_attempt__isnull', True), ('delivery_status', 'pending'), ('provider_accepted_at__isnull', True), ('provider_delivery_status__isnull', True), ('provider_external_message_id__isnull', True)), models.Q(('accepted_provider_attempt__isnull', False), ('delivery_status', 'sent'), ('provider_accepted_at__isnull', False), ('provider_delivery_status__isnull', False), ('provider_external_message_id__isnull', False), models.Q(('provider_external_message_id', ''), _negated=True), models.Q(('provider_delivery_status', ''), _negated=True)), _connector='OR'), name='communication_outbox_provider_result_complete'),
        ),
        migrations.AddConstraint(
            model_name='communicationproviderattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('outcome', 'accepted')), fields=('outbox',), name='one_accepted_provider_attempt_per_outbox'),
        ),
        migrations.AddConstraint(
            model_name='communicationproviderattempt',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('idempotency_key', ''), _negated=True), models.Q(('payload_digest', ''), _negated=True), models.Q(('adapter_kind', ''), _negated=True), models.Q(('evidence_digest', ''), _negated=True), models.Q(models.Q(('outcome', 'accepted'), ('provider_accepted_at__isnull', False), ('provider_delivery_status', 'sent'), ('provider_external_message_id__isnull', False), models.Q(('provider_external_message_id', ''), _negated=True)), models.Q(('outcome', 'rejected'), ('provider_accepted_at__isnull', True), ('provider_delivery_status__isnull', True), ('provider_external_message_id__isnull', True)), _connector='OR')), name='communication_provider_attempt_complete'),
        ),
    ]
