# Generated by Django 5.0.6 on 2026-07-20 10:09

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('loans', '0008_subsidiary_deduction_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpdStatus',
            fields=[
                ('dpd_status_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField(db_index=True)),
                ('days_past_due', models.PositiveIntegerField()),
                ('sop_bucket', models.CharField(db_index=True, max_length=40)),
                ('standard_bucket', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('principal_overdue_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_overdue_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_overdue_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('earliest_unpaid_due_date', models.DateField(blank=True, null=True)),
                ('calculation_version', models.CharField(default='DPD-CALC-1', max_length=40)),
                ('calculation_inputs_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'dpd_statuses',
                'ordering': ['-as_of_date', '-created_at', '-dpd_status_id'],
            },
        ),
        migrations.CreateModel(
            name='DpdOperationalBucketScheme',
            fields=[
                ('dpd_operational_bucket_scheme_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=40, unique=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('first_upper_days', models.PositiveIntegerField(default=30)),
                ('second_upper_days', models.PositiveIntegerField(default=60)),
                ('third_upper_days', models.PositiveIntegerField(default=90)),
                ('status', models.CharField(db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'dpd_operational_bucket_schemes',
                'indexes': [models.Index(fields=['status', 'effective_from', 'effective_to'], name='idx_dpd_scheme_effective')],
            },
        ),
        migrations.AddConstraint(
            model_name='dpdoperationalbucketscheme',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='dpd_scheme_period_order'),
        ),
        migrations.AddConstraint(
            model_name='dpdoperationalbucketscheme',
            constraint=models.CheckConstraint(check=models.Q(('first_upper_days', 30), ('second_upper_days', 60), ('third_upper_days', 90)), name='dpd_scheme_bounds_order'),
        ),
        migrations.AddConstraint(
            model_name='dpdoperationalbucketscheme',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('active', 'retired'))), name='dpd_scheme_status_bounded'),
        ),
        migrations.AddField(
            model_name='dpdstatus',
            name='calculated_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculated_dpd_statuses', to='identity.user'),
        ),
        migrations.AddField(
            model_name='dpdstatus',
            name='calculation_audit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dpd_status', to='identity.auditlog'),
        ),
        migrations.AddField(
            model_name='dpdstatus',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dpd_statuses', to='loans.loanaccount'),
        ),
        migrations.AddField(
            model_name='dpdstatus',
            name='operational_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dpd_statuses', to='monitoring.dpdoperationalbucketscheme'),
        ),
        migrations.AddIndex(
            model_name='dpdstatus',
            index=models.Index(fields=['loan_account', 'as_of_date'], name='idx_dpd_account_asof'),
        ),
        migrations.AddConstraint(
            model_name='dpdstatus',
            constraint=models.UniqueConstraint(fields=('loan_account', 'as_of_date'), name='uniq_dpd_account_asof'),
        ),
        migrations.AddConstraint(
            model_name='dpdstatus',
            constraint=models.CheckConstraint(check=models.Q(('principal_overdue_amount__gte', 0), ('interest_overdue_amount__gte', 0), ('total_overdue_amount__gte', 0)), name='dpd_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dpdstatus',
            constraint=models.CheckConstraint(check=models.Q(('total_overdue_amount', django.db.models.expressions.CombinedExpression(models.F('principal_overdue_amount'), '+', models.F('interest_overdue_amount')))), name='dpd_total_matches_parts'),
        ),
    ]
