# Generated by Django 5.0.6 on 2026-07-20 22:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_deterministic_document_template_constraints'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('monitoring', '0003_reminder_eligibility_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('loan_portfolio_snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField(db_index=True)),
                ('period_start_date', models.DateField()),
                ('total_active_loans_count', models.PositiveIntegerField()),
                ('total_sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_disbursed_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('principal_outstanding_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_outstanding_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_overdue_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('dpd_bucket_summary_json', models.JSONField(default=dict)),
                ('default_cases_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extensions_count', models.PositiveIntegerField(blank=True, null=True)),
                ('recovery_cases_count', models.PositiveIntegerField(blank=True, null=True)),
                ('closed_loans_count', models.PositiveIntegerField(blank=True, null=True)),
                ('totals_json', models.JSONField(default=dict)),
                ('availability_json', models.JSONField(default=dict)),
                ('rows_json', models.JSONField(default=list)),
                ('source_manifest_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'loan_portfolio_snapshots',
                'indexes': [models.Index(fields=['as_of_date', 'created_at'], name='idx_portfolio_asof_created')],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyMisReport',
            fields=[
                ('quarterly_mis_report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(db_index=True, max_length=20)),
                ('quarter', models.CharField(db_index=True, max_length=10)),
                ('as_of_date', models.DateField(db_index=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(db_index=True, default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generation_idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('generation_payload_digest', models.CharField(max_length=64)),
                ('generation_original_response_json', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_idempotency_key_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('submission_payload_digest', models.CharField(blank=True, default='', max_length=64)),
                ('submission_original_response_json', models.JSONField(default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_idempotency_key_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('review_payload_digest', models.CharField(blank=True, default='', max_length=64)),
                ('review_original_response_json', models.JSONField(default=dict)),
                ('excel_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quarterly_mis_excel_report', to='documents.documentfile')),
                ('generation_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generated_quarterly_mis_report', to='identity.auditlog')),
                ('portfolio_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quarterly_mis_report', to='monitoring.portfoliosnapshot')),
                ('prepared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_quarterly_mis_reports', to='identity.user')),
                ('report_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quarterly_mis_pdf_report', to='documents.documentfile')),
                ('review_audit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_quarterly_mis_report', to='identity.auditlog')),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_quarterly_mis_reports', to='identity.user')),
                ('submission_audit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_quarterly_mis_report', to='identity.auditlog')),
                ('submitted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_quarterly_mis_reports', to='identity.user')),
                ('submitted_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quarterly_mis_reports_for_review', to='identity.user')),
            ],
            options={
                'db_table': 'quarterly_mis_reports',
                'ordering': ['-as_of_date', '-revision', '-quarterly_mis_report_id'],
                'indexes': [models.Index(fields=['financial_year', 'quarter', 'status'], name='idx_mis_period_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='quarterlymisreport',
            constraint=models.UniqueConstraint(fields=('financial_year', 'quarter', 'as_of_date', 'revision'), name='uniq_mis_period_revision'),
        ),
        migrations.AddConstraint(
            model_name='quarterlymisreport',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('draft', 'submitted', 'reviewed'))), name='mis_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='quarterlymisreport',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('review_audit__isnull', True), ('reviewed_at__isnull', True), ('reviewed_by_user__isnull', True), ('status', 'draft'), ('submission_audit__isnull', True), ('submitted_at__isnull', True), ('submitted_by_user__isnull', True), ('submitted_to_user__isnull', True)), models.Q(('review_audit__isnull', True), ('reviewed_at__isnull', True), ('reviewed_by_user__isnull', True), ('status', 'submitted'), ('submission_audit__isnull', False), ('submitted_at__isnull', False), ('submitted_by_user__isnull', False), ('submitted_to_user__isnull', False)), models.Q(('review_audit__isnull', False), ('reviewed_at__isnull', False), ('reviewed_by_user__isnull', False), ('status', 'reviewed'), ('submission_audit__isnull', False), ('submitted_at__isnull', False), ('submitted_by_user__isnull', False), ('submitted_to_user__isnull', False)), _connector='OR'), name='mis_transition_evidence_coherent'),
        ),
    ]
