# Generated by Django 5.0.6 on 2026-07-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_workflow', '0001_sap_model_owner_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapcustomerprofilerequest',
            name='delivery_storage_checksum_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
