from django.urls import path

from sfpcl_credit.applications import views as application_views
from sfpcl_credit.approvals import views as approval_views
from sfpcl_credit.communications import views as communication_views
from sfpcl_credit.closure import views as closure_views
from sfpcl_credit.compliance import views as compliance_views
from sfpcl_credit.configurations import views as configuration_views
from sfpcl_credit.dashboard import views as dashboard_views
from sfpcl_credit.documents import views as document_views
from sfpcl_credit.defaults import views as default_views
from sfpcl_credit.disbursements import views as disbursement_views
from sfpcl_credit.finance import views as finance_views
from sfpcl_credit.identity import admin_views, audit_views
from sfpcl_credit.interest import views as interest_views
from sfpcl_credit.identity.views import (
    login,
    logout,
    me,
    portal_activation_complete,
    portal_activation_start,
    portal_login,
    portal_password_change,
    portal_password_reset_complete,
    portal_password_reset_start,
    refresh,
)
from sfpcl_credit.legal_documents import views as legal_document_views
from sfpcl_credit.loans import views as loan_views
from sfpcl_credit.monitoring import views as monitoring_views
from sfpcl_credit.recovery import views as recovery_views
from sfpcl_credit.security_instruments import views as security_instrument_views
from sfpcl_credit.members import portal_views, views as member_views
from sfpcl_credit.ops import deep_health, live_health, ready_health
from sfpcl_credit.search_views import global_search_results
from sfpcl_credit.tracer import views as tracer_views
from sfpcl_credit.workflows import event_views


urlpatterns = [
    path("api/v1/compliance/nbfc-principal-tests/", compliance_views.nbfc_principal_tests, name="nbfc-principal-tests"),
    path("api/v1/compliance/nbfc-principal-tests/<uuid:nbfc_principal_test_id>/", compliance_views.nbfc_principal_test_detail, name="nbfc-principal-test-detail"),
    path("api/v1/compliance/nbfc-principal-tests/<uuid:nbfc_principal_test_id>/review/", compliance_views.nbfc_principal_test_review, name="nbfc-principal-test-review"),
    path("api/v1/compliance/nbfc-principal-tests/<uuid:nbfc_principal_test_id>/submit-for-review/", compliance_views.nbfc_principal_test_submit, name="nbfc-principal-test-submit"),
    path("api/v1/compliance/section-186-trackers/", compliance_views.section_186_trackers, name="section-186-trackers"),
    path("api/v1/compliance/section-186-trackers/<uuid:section_186_tracker_id>/", compliance_views.section_186_tracker_detail, name="section-186-tracker-detail"),
    path("api/v1/compliance/section-186-trackers/<uuid:section_186_tracker_id>/review/", compliance_views.section_186_tracker_review, name="section-186-tracker-review"),
    path("api/v1/compliance/section-186-trackers/<uuid:section_186_tracker_id>/submit-for-review/", compliance_views.section_186_tracker_submit, name="section-186-tracker-submit"),
    path("api/v1/compliance-controls/", compliance_views.controls, name="compliance-controls"),
    path("api/v1/compliance-controls/<uuid:compliance_control_id>/", compliance_views.control_detail, name="compliance-control-detail"),
    path("api/v1/compliance-tasks/", compliance_views.tasks, name="compliance-tasks"),
    path("api/v1/compliance-tasks/<uuid:compliance_task_id>/", compliance_views.task_detail, name="compliance-task-detail"),
    path("api/v1/compliance-tasks/<uuid:compliance_task_id>/evidence/", compliance_views.evidence_submit, name="compliance-evidence-submit"),
    path("api/v1/compliance-evidence/<uuid:compliance_evidence_id>/review/", compliance_views.evidence_review, name="compliance-evidence-review"),
    path("api/v1/compliance/money-lending-law-reviews/", compliance_views.money_lending_review, name="money-lending-law-review"),
    path(
        "api/v1/archive-records/",
        closure_views.archive_manifest,
        name="archive-record-manifest",
    ),
    path(
        "api/v1/loan-closures/<uuid:loan_closure_id>/archive/",
        closure_views.archive_record,
        name="loan-closure-archive-record",
    ),
    path(
        "api/v1/loan-closures/<uuid:loan_closure_id>/security-return/",
        closure_views.security_return_record,
        name="loan-closure-security-return-record",
    ),
    path(
        "api/v1/loan-closures/<uuid:loan_closure_id>/noc/download/",
        closure_views.noc_download,
        name="loan-closure-noc-download",
    ),
    path(
        "api/v1/loan-closures/<uuid:loan_closure_id>/noc/",
        closure_views.noc_issue,
        name="loan-closure-noc-issue",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/closure/",
        closure_views.loan_close,
        name="loan-account-close",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/closure-readiness/",
        closure_views.closure_readiness,
        name="loan-account-closure-readiness",
    ),
    path(
        "api/v1/recovery-actions/<uuid:recovery_action_id>/complete/",
        recovery_views.recovery_action_complete,
        name="recovery-action-complete",
    ),
    path(
        "api/v1/recovery-decisions/<uuid:recovery_decision_id>/actions/",
        recovery_views.recovery_action_create,
        name="recovery-action-create",
    ),
    path(
        "api/v1/default-cases/<uuid:default_case_id>/recovery-decision/",
        recovery_views.recovery_decision_create,
        name="default-case-recovery-decision",
    ),
    path(
        "api/v1/default-cases/<uuid:default_case_id>/non-payment-note/",
        recovery_views.non_payment_note_create,
        name="default-case-non-payment-note",
    ),
    path(
        "api/v1/non-payment-notes/<uuid:non_payment_note_id>/submit-to-sanction-committee/",
        recovery_views.non_payment_note_submit,
        name="non-payment-note-submit-to-sanction-committee",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/default-cases/open/",
        default_views.default_case_open,
        name="loan-account-default-case-open",
    ),
    path(
        "api/v1/default-cases/",
        default_views.default_case_list,
        name="default-case-list",
    ),
    path(
        "api/v1/default-cases/<uuid:default_case_id>/assess/",
        default_views.default_case_assess,
        name="default-case-assess",
    ),
    path(
        "api/v1/default-cases/<uuid:default_case_id>/grant-extension/",
        default_views.default_case_grant_extension,
        name="default-case-grant-extension",
    ),
    path(
        "api/v1/default-cases/<uuid:default_case_id>/",
        default_views.default_case_detail,
        name="default-case-detail",
    ),
    path("api/v1/global-search/", global_search_results, name="global-search"),
    path(
        "api/v1/quarterly-mis-reports/generate/",
        monitoring_views.quarterly_mis_generate,
        name="quarterly-mis-generate",
    ),
    path(
        "api/v1/quarterly-mis-reports/",
        monitoring_views.quarterly_mis_collection,
        name="quarterly-mis-collection",
    ),
    path(
        "api/v1/quarterly-mis-reports/<uuid:report_id>/",
        monitoring_views.quarterly_mis_detail,
        name="quarterly-mis-detail",
    ),
    path(
        "api/v1/quarterly-mis-reports/<uuid:report_id>/drill-down/",
        monitoring_views.quarterly_mis_drill_down,
        name="quarterly-mis-drill-down",
    ),
    path(
        "api/v1/quarterly-mis-reports/<uuid:report_id>/submit-to-cfo/",
        monitoring_views.quarterly_mis_submit,
        name="quarterly-mis-submit",
    ),
    path(
        "api/v1/quarterly-mis-reports/<uuid:report_id>/mark-reviewed/",
        monitoring_views.quarterly_mis_review,
        name="quarterly-mis-review",
    ),
    path(
        "api/v1/quarterly-mis-reports/<uuid:report_id>/export/",
        monitoring_views.quarterly_mis_export,
        name="quarterly-mis-export",
    ),
    path(
        "api/v1/reminders/quarter-end-runs/",
        monitoring_views.reminder_quarter_end_run,
        name="reminder-quarter-end-run",
    ),
    path("api/v1/reminders/", monitoring_views.reminder_list, name="reminder-list"),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/reminders/",
        monitoring_views.reminder_collection,
        name="loan-account-reminder-collection",
    ),
    path(
        "api/v1/reminders/<uuid:reminder_id>/send/",
        monitoring_views.reminder_send,
        name="reminder-send",
    ),
    path(
        "api/v1/dpd-statuses/",
        monitoring_views.dpd_portfolio,
        name="dpd-status-portfolio",
    ),
    path(
        "api/v1/dpd-statuses/bulk-calculate/",
        monitoring_views.dpd_bulk_calculate,
        name="dpd-status-bulk-calculate",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/dpd-status/",
        monitoring_views.dpd_status,
        name="loan-account-dpd-status",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/dpd-status/calculate/",
        monitoring_views.dpd_calculate,
        name="loan-account-dpd-calculate",
    ),
    path(
        "api/v1/interest-capitalisations/check/",
        interest_views.capitalisation_check,
        name="interest-capitalisation-check",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/interest-capitalisations/",
        interest_views.capitalisation_collection,
        name="loan-account-interest-capitalisations",
    ),
    path(
        "api/v1/accrual-entries/<uuid:accrual_entry_id>/mark-sap-posted/",
        interest_views.accrual_mark_sap_posted,
        name="accrual-entry-mark-sap-posted",
    ),
    path(
        "api/v1/accrual-entries/bulk-generate/",
        interest_views.accrual_bulk_generate,
        name="accrual-entry-bulk-generate",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/accrual-entries/",
        interest_views.accrual_collection,
        name="loan-account-accrual-entries",
    ),
    path(
        "api/v1/interest-invoices/",
        interest_views.invoice_list,
        name="interest-invoice-list",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/interest-invoices/",
        interest_views.invoice_collection,
        name="loan-account-interest-invoices",
    ),
    path(
        "api/v1/interest-invoices/<uuid:interest_invoice_id>/issue/",
        interest_views.invoice_issue,
        name="interest-invoice-issue",
    ),
    path(
        "api/v1/bank-statement-imports/",
        loan_views.bank_statement_import,
        name="bank-statement-import",
    ),
    path(
        "api/v1/bank-statement-lines/",
        loan_views.bank_statement_line_list,
        name="bank-statement-line-list",
    ),
    path(
        "api/v1/bank-statement-lines/<uuid:bank_statement_line_id>/match/",
        loan_views.bank_statement_line_match,
        name="bank-statement-line-match",
    ),
    path(
        "api/v1/bank-statement-lines/<uuid:bank_statement_line_id>/exception/",
        loan_views.bank_statement_line_exception,
        name="bank-statement-line-exception",
    ),
    path(
        "api/v1/disbursement-workspaces/",
        disbursement_views.workspace_list,
        name="disbursement-workspace-list",
    ),
    path(
        "api/v1/loan-accounts/",
        loan_views.account_list,
        name="loan-account-list",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/",
        loan_views.account_detail,
        name="loan-account-detail",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/repayment-schedule/",
        loan_views.repayment_schedule,
        name="loan-account-repayment-schedule",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/ledger/",
        loan_views.ledger,
        name="loan-account-ledger",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/ledger-statements/",
        loan_views.ledger_statement_request,
        name="loan-ledger-statement-request",
    ),
    path(
        "api/v1/loan-ledger-statements/<uuid:statement_job_id>/",
        loan_views.ledger_statement_status,
        name="loan-ledger-statement-status",
    ),
    path(
        "api/v1/loan-ledger-statements/<uuid:statement_job_id>/download/",
        loan_views.ledger_statement_download,
        name="loan-ledger-statement-download",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/repayments/",
        loan_views.direct_repayment,
        name="loan-account-direct-repayment",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/direct-repayment-command/",
        loan_views.direct_repayment_command,
        name="loan-account-direct-repayment-command",
    ),
    path(
        "api/v1/repayments/<uuid:repayment_id>/mark-sap-posted/",
        loan_views.repayment_mark_sap_posted,
        name="repayment-mark-sap-posted",
    ),
    path(
        "api/v1/repayments/<uuid:repayment_id>/verify-subsidiary-deduction/",
        loan_views.subsidiary_deduction_verify,
        name="repayment-subsidiary-deduction-verify",
    ),
    path(
        "api/v1/repayments/<uuid:repayment_id>/allocate/",
        loan_views.repayment_allocate,
        name="repayment-allocate",
    ),
    path(
        "api/v1/repayments/<uuid:repayment_id>/manual-allocation-approvals/",
        loan_views.repayment_manual_allocation_approve,
        name="repayment-manual-allocation-approve",
    ),
    path(
        "api/v1/repayments/<uuid:repayment_id>/manual-allocate/",
        loan_views.repayment_manual_allocate,
        name="repayment-manual-allocate",
    ),
    path(
        "api/v1/repayments/<uuid:repayment_id>/reverse/",
        loan_views.repayment_reverse,
        name="repayment-reverse",
    ),
    path(
        "api/v1/disbursements/<uuid:disbursement_id>/send-advice/",
        disbursement_views.send_disbursement_advice,
        name="disbursement-send-advice",
    ),
    path(
        "api/v1/disbursements/<uuid:disbursement_id>/mark-transfer-successful/",
        disbursement_views.mark_transfer_successful,
        name="disbursement-mark-transfer-successful",
    ),
    path(
        "api/v1/disbursements/<uuid:disbursement_id>/authorise/",
        disbursement_views.authorise_disbursement,
        name="disbursement-authorise",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/disbursements/initiate/",
        disbursement_views.initiate_disbursement,
        name="loan-account-disbursement-initiate",
    ),
    path(
        "api/v1/loan-accounts/<uuid:loan_account_id>/disbursement-readiness/",
        disbursement_views.readiness,
        name="loan-account-disbursement-readiness",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/create-loan-account/",
        loan_views.create_from_sanction,
        name="loan-application-create-loan-account",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/sap-customer-profile-request/",
        finance_views.sap_customer_profile_request,
        name="loan-application-sap-customer-profile-request",
    ),
    path(
        "api/v1/sap-customer-profile-requests/<uuid:sap_customer_profile_request_id>/send/",
        finance_views.sap_customer_profile_request_send,
        name="sap-customer-profile-request-send",
    ),
    path(
        "api/v1/sap-customer-profile-requests/<uuid:sap_customer_profile_request_id>/complete/",
        finance_views.sap_customer_profile_request_complete,
        name="sap-customer-profile-request-complete",
    ),
    path(
        "api/v1/sap-customer-profile-requests/"
        "<uuid:sap_customer_profile_request_id>/annexure-i-delivery-capability/",
        finance_views.sap_annexure_delivery_capability,
        name="sap-customer-profile-annexure-delivery-capability",
    ),
    path(
        "api/v1/sap-customer-profile-requests/"
        "<uuid:sap_customer_profile_request_id>/annexure-i/",
        finance_views.sap_annexure_download,
        name="sap-customer-profile-annexure-download",
    ),
    path(
        "api/v1/members/<uuid:member_id>/sap-customer-code/",
        finance_views.member_sap_customer_code,
        name="member-sap-customer-code",
    ),
    path(
        "api/v1/loan-documents/<uuid:loan_document_id>/verify/",
        legal_document_views.verify_loan_document,
        name="loan-document-verify",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/security-package/",
        security_instrument_views.security_package,
        name="loan-application-security-package",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/security-package/refresh/",
        security_instrument_views.security_package_refresh,
        name="loan-application-security-package-refresh",
    ),
    path(
        "api/v1/security-packages/<uuid:security_package_id>/power-of-attorney/",
        security_instrument_views.package_power_of_attorney,
        name="security-package-power-of-attorney",
    ),
    path(
        "api/v1/power-of-attorneys/<uuid:power_of_attorney_id>/",
        security_instrument_views.power_of_attorney_detail,
        name="power-of-attorney-detail",
    ),
    path(
        "api/v1/security-packages/<uuid:security_package_id>/sh4-share-transfer-form/",
        security_instrument_views.package_sh4,
        name="security-package-sh4-share-transfer-form",
    ),
    path(
        "api/v1/sh4-share-transfer-forms/<uuid:sh4_share_transfer_form_id>/",
        security_instrument_views.sh4_detail,
        name="sh4-share-transfer-form-detail",
    ),
    path(
        "api/v1/security-packages/<uuid:security_package_id>/cdsl-share-pledge/",
        security_instrument_views.package_cdsl_share_pledge,
        name="security-package-cdsl-share-pledge",
    ),
    path(
        "api/v1/cdsl-share-pledges/<uuid:cdsl_share_pledge_id>/",
        security_instrument_views.cdsl_share_pledge_detail,
        name="cdsl-share-pledge-detail",
    ),
    path(
        "api/v1/cdsl-share-pledges/<uuid:cdsl_share_pledge_id>/reveal-bo-accounts/",
        security_instrument_views.cdsl_share_pledge_reveal,
        name="cdsl-share-pledge-reveal-bo-accounts",
    ),
    path(
        "api/v1/security-packages/<uuid:security_package_id>/blank-dated-cheque/",
        security_instrument_views.package_blank_dated_cheque,
        name="security-package-blank-dated-cheque",
    ),
    path(
        "api/v1/blank-dated-cheques/<uuid:blank_dated_cheque_id>/",
        security_instrument_views.blank_dated_cheque_detail,
        name="blank-dated-cheque-detail",
    ),
    path(
        "api/v1/blank-dated-cheques/<uuid:blank_dated_cheque_id>/reveal-cheque-number/",
        security_instrument_views.blank_dated_cheque_reveal,
        name="blank-dated-cheque-reveal",
    ),
    path(
        "api/v1/loan-documents/<uuid:loan_document_id>/signatures/",
        legal_document_views.signature_record,
        name="loan-document-signature-record",
    ),
    path(
        "api/v1/signature-records/<uuid:signature_record_id>/resolve-mismatch/",
        legal_document_views.resolve_signature_mismatch,
        name="signature-record-resolve-mismatch",
    ),
    path(
        "api/v1/loan-documents/<uuid:loan_document_id>/stamp-duty-record/",
        legal_document_views.stamp_duty_record,
        name="loan-document-stamp-duty-record",
    ),
    path(
        "api/v1/loan-documents/<uuid:loan_document_id>/notarisation-record/",
        legal_document_views.notarisation_record,
        name="loan-document-notarisation-record",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/loan-documents/generate/",
        legal_document_views.generate_loan_document,
        name="loan-document-generate",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/loan-documents/",
        legal_document_views.loan_document_collection,
        name="loan-document-list",
    ),
    path(
        "api/v1/documentation-workspaces/",
        legal_document_views.documentation_workspace_queue,
        name="documentation-workspace-queue",
    ),
    path("api/v1/loan-applications/<uuid:loan_application_id>/documentation-workspace/", legal_document_views.documentation_workspace, name="loan-application-documentation-workspace"),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/documentation-workspace/actions/<str:action_id>/",
        legal_document_views.documentation_workspace_action,
        name="loan-application-documentation-workspace-action",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/documentation-workspace/<slug:item_code>/download/",
        legal_document_views.documentation_workspace_download,
        name="loan-application-documentation-workspace-download",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/sanction-decision/",
        approval_views.loan_application_sanction_decision,
        name="loan-application-sanction-decision",
    ),
    path(
        "api/v1/credit-sanction-register/",
        approval_views.credit_sanction_register_collection,
        name="credit-sanction-register-list",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/general-meeting-approval/",
        approval_views.loan_application_general_meeting_approval,
        name="loan-application-general-meeting-approval",
    ),
    path("api/v1/exception-register/", approval_views.exception_register_collection, name="exception-register-list"),
    path("api/v1/approval-cases/", approval_views.approval_case_collection, name="approval-case-list"),
    path("api/v1/approval-cases/<uuid:approval_case_id>/", approval_views.approval_case_detail, name="approval-case-detail"),
    path("api/v1/approval-cases/<uuid:approval_case_id>/approve/", approval_views.approval_case_approve, name="approval-case-approve"),
    path("api/v1/approval-cases/<uuid:approval_case_id>/reject/", approval_views.approval_case_reject, name="approval-case-reject"),
    path("api/v1/approval-cases/<uuid:approval_case_id>/return-for-clarification/", approval_views.approval_case_return, name="approval-case-return"),
    path("api/v1/approval-cases/<uuid:approval_case_id>/abstain/", approval_views.approval_case_abstain, name="approval-case-abstain"),
    path("api/v1/approval-matrix-rules/", approval_views.rule_collection, name="approval-matrix-rule-list-create"),
    path("api/v1/approval-matrix-rules/<uuid:approval_matrix_rule_id>/", approval_views.rule_detail, name="approval-matrix-rule-supersede"),
    path("api/v1/sanction-committees/", approval_views.committee_collection, name="sanction-committee-list-create"),
    path("api/v1/sanction-committees/<uuid:sanction_committee_id>/", approval_views.committee_detail, name="sanction-committee-supersede"),
    path("api/v1/approval-configuration-proposals/<uuid:approval_configuration_proposal_id>/", approval_views.proposal_detail, name="approval-configuration-proposal-detail"),
    path("api/v1/approval-configuration-proposals/<uuid:approval_configuration_proposal_id>/approve/", approval_views.proposal_approve, name="approval-configuration-proposal-approve"),
    path("api/v1/approval-configuration-proposals/<uuid:approval_configuration_proposal_id>/reject/", approval_views.proposal_reject, name="approval-configuration-proposal-reject"),
    path("api/v1/auth/login/", login, name="auth-login"),
    path("api/v1/auth/refresh/", refresh, name="auth-refresh"),
    path("api/v1/auth/logout/", logout, name="auth-logout"),
    path("api/v1/auth/me/", me, name="auth-me"),
    path(
        "api/v1/portal/auth/activation/start/",
        portal_activation_start,
        name="portal-activation-start",
    ),
    path(
        "api/v1/portal/auth/activation/complete/",
        portal_activation_complete,
        name="portal-activation-complete",
    ),
    path("api/v1/portal/auth/login/", portal_login, name="portal-auth-login"),
    path(
        "api/v1/portal/auth/password-reset/start/",
        portal_password_reset_start,
        name="portal-password-reset-start",
    ),
    path(
        "api/v1/portal/auth/password-reset/complete/",
        portal_password_reset_complete,
        name="portal-password-reset-complete",
    ),
    path(
        "api/v1/portal/auth/password/change/",
        portal_password_change,
        name="portal-password-change",
    ),
    path("api/v1/portal/dashboard/", portal_views.portal_dashboard, name="portal-dashboard"),
    path("api/v1/portal/profile/", portal_views.portal_profile, name="portal-profile"),
    path(
        "api/v1/portal/loan-accounts/",
        portal_views.portal_loan_accounts,
        name="portal-loan-account-list",
    ),
    path(
        "api/v1/portal/loan-accounts/<uuid:loan_account_id>/",
        portal_views.portal_loan_account_detail,
        name="portal-loan-account-detail",
    ),
    path(
        "api/v1/portal/loan-accounts/<uuid:loan_account_id>/schedule/",
        portal_views.portal_loan_account_schedule,
        name="portal-loan-account-schedule",
    ),
    path(
        "api/v1/portal/loan-accounts/<uuid:loan_account_id>/repayments/",
        portal_views.portal_loan_account_repayments,
        name="portal-loan-account-repayments",
    ),
    path(
        "api/v1/portal/loan-accounts/<uuid:loan_account_id>/invoices/",
        portal_views.portal_loan_account_invoices,
        name="portal-loan-account-invoices",
    ),
    path(
        "api/v1/portal/loan-accounts/<uuid:loan_account_id>/direct-instructions/",
        portal_views.portal_loan_account_direct_instructions,
        name="portal-loan-account-direct-instructions",
    ),
    path(
        "api/v1/portal/produce-supply/",
        portal_views.portal_produce_supply,
        name="portal-produce-supply",
    ),
    path(
        "api/v1/portal/application-limit-projection/",
        portal_views.portal_application_limit_projection,
        name="portal-application-limit-projection",
    ),
    path(
        "api/v1/portal/applications/",
        portal_views.portal_applications,
        name="portal-applications",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/",
        portal_views.portal_application_detail,
        name="portal-application-detail",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/submit/",
        portal_views.portal_application_submit,
        name="portal-application-submit",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/deficiencies/",
        portal_views.portal_application_deficiencies,
        name="portal-application-deficiencies",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/deficiencies/note/",
        portal_views.portal_application_deficiency_note,
        name="portal-application-deficiency-note",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/deficiencies/<uuid:deficiency_id>/draft/",
        portal_views.portal_application_deficiency_draft,
        name="portal-application-deficiency-draft",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/deficiencies/<uuid:deficiency_id>/upload/",
        portal_views.portal_application_deficiency_upload,
        name="portal-application-deficiency-upload",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/deficiencies/resubmit/",
        portal_views.portal_application_deficiency_resubmit,
        name="portal-application-deficiency-resubmit",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/deficiencies/<uuid:deficiency_id>/download/",
        portal_views.portal_application_deficiency_download,
        name="portal-application-deficiency-download",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/documentation-actions/",
        portal_views.portal_documentation_actions,
        name="portal-documentation-actions",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/disbursement-status/",
        portal_views.portal_application_disbursement_status,
        name="portal-application-disbursement-status",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/disbursement-advice/download-capability/",
        portal_views.portal_disbursement_advice_capability,
        name="portal-disbursement-advice-capability",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/disbursement-advice/content/",
        portal_views.portal_disbursement_advice_content,
        name="portal-disbursement-advice-content",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/documentation-actions/<slug:action_code>/upload/",
        portal_views.portal_documentation_action_upload,
        name="portal-documentation-action-upload",
    ),
    path(
        "api/v1/portal/applications/<uuid:loan_application_id>/documentation-actions/<slug:action_code>/download/",
        portal_views.portal_documentation_action_download,
        name="portal-documentation-action-download",
    ),
    path(
        "api/v1/loan-applications/",
        application_views.loan_application_collection,
        name="loan-application-list-create",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/",
        application_views.loan_application_detail,
        name="loan-application-detail",
    ),
    path(
        "api/v1/loan-request-register/",
        application_views.loan_request_register_collection,
        name="loan-request-register-list",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/submit/",
        application_views.loan_application_submit,
        name="loan-application-submit",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/generate-reference/",
        application_views.loan_application_generate_reference,
        name="loan-application-generate-reference",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/application-documents/",
        application_views.loan_application_documents,
        name="loan-application-documents",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/document-checklist/",
        legal_document_views.legal_document_checklist,
        name="loan-application-document-checklist",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/bank-verification-decision/",
        application_views.bank_verification_decision,
        name="loan-application-bank-verification-decision",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/document-checklist/refresh/",
        application_views.loan_application_document_checklist,
        name="loan-application-document-checklist-refresh",
    ),
    path(
        "api/v1/checklist-items/<uuid:checklist_item_id>/complete/",
        legal_document_views.complete_checklist_item,
        name="checklist-item-complete",
    ),
    path(
        "api/v1/document-checklists/<uuid:document_checklist_id>/approve-as-company-secretary/",
        legal_document_views.approve_checklist_company_secretary,
        name="document-checklist-approve-company-secretary",
    ),
    path(
        "api/v1/document-checklists/<uuid:document_checklist_id>/approve-as-credit-manager/",
        legal_document_views.approve_checklist_credit_manager,
        name="document-checklist-approve-credit-manager",
    ),
    path(
        "api/v1/document-checklists/<uuid:document_checklist_id>/approve-as-sanction-committee/",
        legal_document_views.approve_checklist_sanction_committee,
        name="document-checklist-approve-sanction-committee",
    ),
    path(
        "api/v1/document-checklists/<uuid:document_checklist_id>/sign-disbursement-complete/",
        legal_document_views.sign_checklist_disbursement_complete,
        name="document-checklist-sign-disbursement-complete",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/completeness-check/",
        application_views.loan_application_completeness_check,
        name="loan-application-completeness-check",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/completeness-check/pass/",
        application_views.loan_application_completeness_pass,
        name="loan-application-completeness-pass",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/eligibility-assessment/",
        application_views.loan_application_eligibility_assessment,
        name="loan-application-eligibility-assessment",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/eligibility-assessment/run/",
        application_views.loan_application_eligibility_assessment_run,
        name="loan-application-eligibility-assessment-run",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/loan-limit-assessment/",
        application_views.loan_application_loan_limit_assessment,
        name="loan-application-loan-limit-assessment",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/loan-limit-assessment/calculate/",
        application_views.loan_application_loan_limit_calculate,
        name="loan-application-loan-limit-calculate",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/appraisal-note/",
        application_views.loan_application_appraisal_note,
        name="loan-application-appraisal-note",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/submit-to-sanction-committee/",
        application_views.loan_application_submit_to_sanction,
        name="loan-application-submit-to-sanction",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/sanction-case/",
        application_views.loan_application_sanction_case,
        name="loan-application-sanction-case",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/approval-cases/",
        application_views.loan_application_approval_case,
        name="loan-application-approval-case",
    ),
    path(
        "api/v1/appraisal-notes/<uuid:loan_appraisal_note_id>/submit-for-review/",
        application_views.appraisal_note_submit_for_review,
        name="appraisal-note-submit-for-review",
    ),
    path(
        "api/v1/appraisal-notes/<uuid:loan_appraisal_note_id>/review/",
        application_views.appraisal_note_review,
        name="appraisal-note-review",
    ),
    path(
        "api/v1/appraisal-notes/<uuid:loan_appraisal_note_id>/revalidate-prerequisites/",
        application_views.appraisal_note_revalidate_prerequisites,
        name="appraisal-note-revalidate-prerequisites",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/return-with-deficiencies/",
        application_views.loan_application_return_with_deficiencies,
        name="loan-application-return-with-deficiencies",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/deficiencies/",
        application_views.loan_application_deficiencies,
        name="loan-application-deficiencies",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/rejection-note/",
        application_views.loan_application_rejection_note,
        name="loan-application-rejection-note",
    ),
    path(
        "api/v1/deficiencies/<uuid:deficiency_id>/resolve/",
        application_views.application_deficiency_resolve,
        name="application-deficiency-resolve",
    ),
    path(
        "api/v1/rejection-notes/<uuid:rejection_note_id>/send/",
        application_views.rejection_note_send,
        name="rejection-note-send",
    ),
    path(
        "api/v1/application-documents/<uuid:application_document_id>/verify/",
        application_views.application_document_verify,
        name="application-document-verify",
    ),
    path("api/v1/dashboard/", dashboard_views.dashboard_summary, name="dashboard-summary"),
    path("api/v1/admin/users/", admin_views.user_list, name="admin-user-list"),
    path(
        "api/v1/admin/users/<uuid:user_id>/",
        admin_views.user_detail,
        name="admin-user-detail",
    ),
    path(
        "api/v1/admin/users/<uuid:user_id>/roles/",
        admin_views.assign_role,
        name="admin-user-role-assign",
    ),
    path(
        "api/v1/admin/users/<uuid:user_id>/teams/",
        admin_views.add_team,
        name="admin-user-team-add",
    ),
    path(
        "api/v1/admin/users/<uuid:user_id>/teams/<str:team_code>/",
        admin_views.remove_team,
        name="admin-user-team-remove",
    ),
    path(
        "api/v1/admin/users/<uuid:user_id>/status/",
        admin_views.set_status,
        name="admin-user-status-set",
    ),
    path("api/v1/audit-logs/", audit_views.audit_log_list, name="audit-log-list"),
    path(
        "api/v1/workflow-events/",
        event_views.workflow_event_list,
        name="workflow-event-list",
    ),
    path(
        "api/v1/config/loan-policy/",
        configuration_views.loan_policy_collection,
        name="loan-policy-config-list-create",
    ),
    path(
        "api/v1/config/interest-rates/",
        configuration_views.interest_rate_collection,
        name="interest-rate-config-list-create",
    ),
    path(
        "api/v1/config/interest-rates/<uuid:interest_rate_config_id>/activate/",
        configuration_views.interest_rate_activate,
        name="interest-rate-config-activate",
    ),
    path(
        "api/v1/config/loan-policy/<uuid:loan_policy_config_id>/",
        configuration_views.loan_policy_detail,
        name="loan-policy-config-detail",
    ),
    path(
        "api/v1/config/loan-policy/<uuid:loan_policy_config_id>/activate/",
        configuration_views.loan_policy_activate,
        name="loan-policy-config-activate",
    ),
    path(
        "api/v1/version-histories/",
        configuration_views.version_history_list,
        name="version-history-list",
    ),
    path(
        "api/v1/content-templates/",
        communication_views.content_template_collection,
        name="content-template-list-create",
    ),
    path(
        "api/v1/content-templates/<uuid:content_template_id>/",
        communication_views.content_template_detail,
        name="content-template-detail",
    ),
    path(
        "api/v1/communications/",
        communication_views.communication_collection,
        name="communication-list",
    ),
    path(
        "api/v1/communications/send/",
        communication_views.communication_send,
        name="communication-send",
    ),
    path(
        "api/v1/communication-exceptions/",
        communication_views.communication_exception_collection,
        name="communication-exception-list",
    ),
    path(
        "api/v1/communication-exceptions/<uuid:communication_exception_id>/",
        communication_views.communication_exception_detail,
        name="communication-exception-detail",
    ),
    path(
        "api/v1/communication-exceptions/<uuid:communication_exception_id>/resolve/",
        communication_views.communication_exception_resolve,
        name="communication-exception-resolve",
    ),
    path(
        "api/v1/notifications/",
        communication_views.notification_collection,
        name="notification-list",
    ),
    path(
        "api/v1/notifications/<uuid:notification_id>/mark-read/",
        communication_views.notification_mark_read,
        name="notification-mark-read",
    ),
    path("api/v1/members/", member_views.member_collection, name="member-list"),
    path(
        "api/v1/members/<uuid:member_id>/reverification/",
        member_views.member_reverification,
        name="member-reverification",
    ),
    path("api/v1/members/<uuid:member_id>/identity-change-requests/", member_views.member_identity_change_requests, name="member-identity-change-request"),
    path("api/v1/member-identity-change-requests/<uuid:request_id>/approve/", member_views.approve_member_identity_change, name="member-identity-change-approve"),
    path(
        "api/v1/members/<uuid:member_id>/reveal-sensitive-field/",
        member_views.reveal_sensitive_field,
        name="member-reveal-sensitive-field",
    ),
    path(
        "api/v1/members/<uuid:member_id>/",
        member_views.member_detail,
        name="member-detail",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/witnesses/",
        application_views.loan_application_witnesses,
        name="loan-application-witnesses",
    ),
    path(
        "api/v1/loan-applications/<uuid:loan_application_id>/witnesses/<uuid:witness_id>/",
        application_views.loan_application_witness_detail,
        name="loan-application-witness-detail",
    ),
    path(
        "api/v1/members/<uuid:member_id>/nominees/",
        member_views.member_nominees,
        name="member-nominees",
    ),
    path(
        "api/v1/members/<uuid:member_id>/shareholdings/",
        member_views.member_shareholdings,
        name="member-shareholdings",
    ),
    path(
        "api/v1/members/<uuid:member_id>/produce-supply-records/",
        member_views.member_produce_supply_records,
        name="member-produce-supply-records",
    ),
    path(
        "api/v1/produce-supply-records/<uuid:record_id>/verify/",
        member_views.produce_supply_record_verify,
        name="produce-supply-record-verify",
    ),
    path(
        "api/v1/members/<uuid:member_id>/active-status/verify/",
        member_views.active_member_status_verify,
        name="active-member-status-verify",
    ),
    path(
        "api/v1/members/<uuid:member_id>/land-holdings/",
        member_views.member_land_holdings,
        name="member-land-holdings",
    ),
    path(
        "api/v1/members/<uuid:member_id>/crop-plans/",
        member_views.member_crop_plans,
        name="member-crop-plans",
    ),
    path(
        "api/v1/members/<uuid:member_id>/bank-accounts/",
        member_views.member_bank_accounts,
        name="member-bank-accounts",
    ),
    path(
        "api/v1/members/<uuid:member_id>/cancelled-cheques/",
        member_views.member_cancelled_cheques,
        name="member-cancelled-cheques",
    ),
    path(
        "api/v1/kyc-profiles/",
        member_views.kyc_profiles,
        name="kyc-profile-list-create",
    ),
    path(
        "api/v1/kyc-profiles/<uuid:kyc_profile_id>/",
        member_views.kyc_profile_detail,
        name="kyc-profile-detail",
    ),
    path(
        "api/v1/kyc-profiles/<uuid:kyc_profile_id>/documents/",
        member_views.kyc_profile_documents,
        name="kyc-profile-documents",
    ),
    path(
        "api/v1/kyc-documents/<uuid:kyc_document_id>/verify/",
        member_views.kyc_document_verify,
        name="kyc-document-verify",
    ),
    path(
        "api/v1/document-files/",
        document_views.upload_document_file,
        name="document-file-upload",
    ),
    path(
        "api/v1/document-files/<uuid:document_id>/download/",
        document_views.download_document_file,
        name="document-file-download",
    ),
    path(
        "api/v1/document-templates/",
        document_views.document_template_collection,
        name="document-template-list-create",
    ),
    path(
        "api/v1/document-templates/<uuid:document_template_id>/",
        document_views.document_template_detail,
        name="document-template-successor-create",
    ),
    path("api/v1/tracer/members/", tracer_views.create_member, name="tracer-member-create"),
    path(
        "api/v1/tracer/members/<uuid:member_id>/loan-applications/",
        tracer_views.create_application,
        name="tracer-application-create",
    ),
    path(
        "api/v1/tracer/loan-applications/<uuid:application_id>/sanction/",
        tracer_views.sanction_application,
        name="tracer-application-sanction",
    ),
    path(
        "api/v1/tracer/loan-applications/<uuid:application_id>/loan-account/",
        tracer_views.create_loan_account,
        name="tracer-loan-account-create",
    ),
    path(
        "api/v1/tracer/loan-accounts/<uuid:account_id>/disburse/",
        tracer_views.mark_disbursed,
        name="tracer-loan-account-disburse",
    ),
    path(
        "api/v1/tracer/loan-accounts/<uuid:account_id>/repayments/",
        tracer_views.post_repayment,
        name="tracer-repayment-post",
    ),
    path(
        "api/v1/tracer/loan-accounts/<uuid:account_id>/close/",
        tracer_views.close_loan,
        name="tracer-loan-account-close",
    ),
    path("api/v1/health/live/", live_health, name="health-live"),
    path("api/v1/health/ready/", ready_health, name="health-ready"),
    path("api/v1/health/deep/", deep_health, name="health-deep"),
]
