# Generated by Django 5.0.6 on 2026-07-22 03:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


DEFAULT_CASE_READ_ROLES = (
    'credit_manager',
    'company_secretary',
    'cfo',
    'director',
    'internal_auditor',
)


def grant_default_case_read(apps, schema_editor):
    Permission = apps.get_model('identity', 'Permission')
    Role = apps.get_model('identity', 'Role')
    RolePermission = apps.get_model('identity', 'RolePermission')
    permission, _ = Permission.objects.get_or_create(
        permission_code='defaults.case.read',
        defaults={
            'permission_name': 'View default cases',
            'module_name': 'defaults',
            'risk_level': 'medium',
        },
    )
    for role in Role.objects.filter(role_code__in=DEFAULT_CASE_READ_ROLES):
        RolePermission.objects.get_or_create(role=role, permission=permission)


def revoke_default_case_read(apps, schema_editor):
    RolePermission = apps.get_model('identity', 'RolePermission')
    RolePermission.objects.filter(
        role__role_code__in=DEFAULT_CASE_READ_ROLES,
        permission__permission_code='defaults.case.read',
    ).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('loans', '0009_dpd_pointer_integrity'),
        ('members', '0015_member_aadhaar_last4'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCase',
            fields=[
                ('default_case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_event', models.CharField(db_index=True, max_length=80)),
                ('scheduled_due_date', models.DateField(db_index=True)),
                ('default_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grace_period_start_date', models.DateField()),
                ('grace_period_end_date', models.DateField(db_index=True)),
                ('default_case_status', models.CharField(db_index=True, max_length=80)),
                ('reason', models.CharField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_cases', to='loans.loanaccount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_cases', to='members.member')),
                ('opened_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_default_cases', to='identity.user')),
                ('opening_audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opened_default_case', to='identity.auditlog')),
                ('repayment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_cases', to='loans.repaymentschedule')),
            ],
            options={
                'db_table': 'default_cases',
                'ordering': ['-default_detected_at', '-default_case_id'],
                'indexes': [models.Index(fields=['member', 'default_case_status'], name='idx_default_member_status'), models.Index(fields=['loan_account', 'default_case_status'], name='idx_default_loan_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='defaultcase',
            constraint=models.UniqueConstraint(fields=('repayment_schedule', 'trigger_event'), name='uniq_default_missed_obligation'),
        ),
        migrations.AddConstraint(
            model_name='defaultcase',
            constraint=models.CheckConstraint(check=models.Q(('trigger_event', 'missed_principal_repayment')), name='default_trigger_bounded'),
        ),
        migrations.AddConstraint(
            model_name='defaultcase',
            constraint=models.CheckConstraint(check=models.Q(('default_case_status__in', ('open', 'grace_period_active', 'grace_period_expired', 'assessment_in_progress', 'extension_granted', 'extension_expired', 'non_payment_under_review', 'recovery_decision_pending', 'recovery_approved', 'recovery_in_progress', 'resolved_by_repayment', 'closed'))), name='default_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='defaultcase',
            constraint=models.CheckConstraint(check=models.Q(('grace_period_start_date', models.F('scheduled_due_date'))), name='default_grace_starts_due'),
        ),
        migrations.AddConstraint(
            model_name='defaultcase',
            constraint=models.CheckConstraint(check=models.Q(('grace_period_end_date__gt', models.F('grace_period_start_date'))), name='default_grace_period_order'),
        ),
        migrations.RunPython(grant_default_case_read, revoke_default_case_read),
    ]
