# Generated by Django 5.0.6 on 2026-07-22 06:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


ASSESSOR_ROLES = ('credit_manager', 'deputy_manager_finance')


def grant_default_assessment_permissions(apps, schema_editor):
    Permission = apps.get_model('identity', 'Permission')
    Role = apps.get_model('identity', 'Role')
    RolePermission = apps.get_model('identity', 'RolePermission')
    assessment_permission, _ = Permission.objects.get_or_create(
        permission_code='defaults.assessment.create',
        defaults={
            'permission_name': 'Create default assessment',
            'module_name': 'defaults',
            'risk_level': 'high',
        },
    )
    read_permission, _ = Permission.objects.get_or_create(
        permission_code='defaults.case.read',
        defaults={
            'permission_name': 'View default cases',
            'module_name': 'defaults',
            'risk_level': 'medium',
        },
    )
    for role in Role.objects.filter(role_code__in=ASSESSOR_ROLES):
        RolePermission.objects.get_or_create(role=role, permission=assessment_permission)
        RolePermission.objects.get_or_create(role=role, permission=read_permission)


def revoke_default_assessment_permissions(apps, schema_editor):
    RolePermission = apps.get_model('identity', 'RolePermission')
    RolePermission.objects.filter(
        role__role_code__in=ASSESSOR_ROLES,
        permission__permission_code='defaults.assessment.create',
    ).delete()
    RolePermission.objects.filter(
        role__role_code='deputy_manager_finance',
        permission__permission_code='defaults.case.read',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0001_initial'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAssessment',
            fields=[
                ('default_assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(max_length=80)),
                ('payment_failure_classification', models.CharField(db_index=True, max_length=80)),
                ('reason_summary', models.TextField()),
                ('evidence_document_ids_json', models.JSONField(default=list)),
                ('borrower_interaction_summary', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recommended_action', models.CharField(max_length=100)),
                ('assessed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_assessments', to='identity.user')),
                ('default_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='defaults.defaultcase')),
            ],
            options={
                'db_table': 'default_assessments',
                'ordering': ['-assessed_at', '-default_assessment_id'],
            },
        ),
        migrations.AddField(
            model_name='defaultcase',
            name='current_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_cases', to='defaults.defaultassessment'),
        ),
        migrations.AddConstraint(
            model_name='defaultassessment',
            constraint=models.UniqueConstraint(fields=('default_case', 'assessment_type'), name='uniq_default_case_assessment_type'),
        ),
        migrations.AddConstraint(
            model_name='defaultassessment',
            constraint=models.CheckConstraint(check=models.Q(('assessment_type__in', ('post_grace', 'post_extension'))), name='default_assessment_type_bounded'),
        ),
        migrations.AddConstraint(
            model_name='defaultassessment',
            constraint=models.CheckConstraint(check=models.Q(('payment_failure_classification__in', ('intentional', 'non_intentional', 'unclear'))), name='default_classification_bounded'),
        ),
        migrations.AddConstraint(
            model_name='defaultassessment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('reason_summary', ''), _negated=True), models.Q(('recommended_action', ''), _negated=True)), name='default_assessment_text_required'),
        ),
        migrations.RunPython(
            grant_default_assessment_permissions,
            revoke_default_assessment_permissions,
        ),
    ]
