# Generated by Django 5.0.6 on 2026-07-22 07:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def grant_non_payment_note_permissions(apps, schema_editor):
    Permission = apps.get_model("identity", "Permission")
    Role = apps.get_model("identity", "Role")
    RolePermission = apps.get_model("identity", "RolePermission")
    grants = {
        "deputy_manager_finance": (
            "defaults.non_payment_note.create",
            "Create non-payment note",
        ),
        "credit_manager": (
            "defaults.non_payment_note.submit",
            "Submit to Sanction Committee",
        ),
    }
    for role_code, (permission_code, permission_name) in grants.items():
        permission, _ = Permission.objects.get_or_create(
            permission_code=permission_code,
            defaults={
                "permission_name": permission_name,
                "module_name": "defaults",
                "risk_level": "high",
            },
        )
        for role in Role.objects.filter(role_code=role_code):
            RolePermission.objects.get_or_create(role=role, permission=permission)


def revoke_non_payment_note_permissions(apps, schema_editor):
    RolePermission = apps.get_model("identity", "RolePermission")
    RolePermission.objects.filter(
        role__role_code="deputy_manager_finance",
        permission__permission_code="defaults.non_payment_note.create",
    ).delete()
    RolePermission.objects.filter(
        role__role_code="credit_manager",
        permission__permission_code="defaults.non_payment_note.submit",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0020_approvalaction_approver_display_name'),
        ('defaults', '0003_extension_note'),
        ('identity', '0004_auditlog_selector_manifest_sha256'),
        ('legal_documents', '0015_checklist_constraint_state_owner_anchor'),
        ('loans', '0009_dpd_pointer_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPaymentNote',
            fields=[
                ('non_payment_note_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_for_non_payment', models.TextField()),
                ('intentionality_assessment', models.CharField(max_length=80)),
                ('outstanding_principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('outstanding_interest_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('recommended_recovery_action', models.CharField(max_length=100)),
                ('evidence_document_ids_json', models.JSONField(default=list)),
                ('frozen_case_facts_json', models.JSONField(default=dict)),
                ('submitted_to_sanction_committee_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='draft', max_length=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recovery_non_payment_note', to='approvals.approvalcase')),
                ('current_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_payment_notes', to='defaults.defaultassessment')),
                ('default_case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='non_payment_note', to='defaults.defaultcase')),
                ('extension_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_payment_notes', to='defaults.extensionnote')),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_payment_notes', to='loans.loanaccount')),
                ('loan_document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='non_payment_note', to='legal_documents.loandocument')),
                ('prepared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_non_payment_notes', to='identity.user')),
            ],
            options={
                'db_table': 'non_payment_notes',
                'ordering': ['-created_at', '-non_payment_note_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='nonpaymentnote',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('draft', 'submitted', 'returned', 'reviewed'))), name='non_payment_note_status_bounded'),
        ),
        migrations.AddConstraint(
            model_name='nonpaymentnote',
            constraint=models.CheckConstraint(check=models.Q(('outstanding_principal_amount__gte', 0)), name='non_payment_principal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='nonpaymentnote',
            constraint=models.CheckConstraint(check=models.Q(('outstanding_interest_amount__gte', 0)), name='non_payment_interest_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='nonpaymentnote',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('reason_for_non_payment', ''), _negated=True), models.Q(('recommended_recovery_action', ''), _negated=True)), name='non_payment_note_text_required'),
        ),
        migrations.RunPython(
            grant_non_payment_note_permissions,
            revoke_non_payment_note_permissions,
        ),
    ]
